README.md
gulpfile.babel.js
projects/sw-appcache-behavior/README.md
projects/sw-appcache-behavior/package.json
projects/sw-appcache-behavior/src/appcache-behavior-import.js
templates/Project-README.hbs
templates/README.hbs

Fixes #12
This adds some additional automation of documentation, via the `documentation:repo` and `documentation:projects` tasks, along with some updates to the Handlebars templates.
It also pushes out the `demo` and `build` directories for each project to `gh-pages`, to ensure that we have a live demo to point folks to from the docs.
The `sw-appcache-behavior` documentation is also included in this PR.

Automation of generating project docs and demos.

---

gulpfile.babel.js
projects/sw-appcache-behavior/README.md
projects/sw-appcache-behavior/package.json
templates/Project-README.hbs

I had to change a few things with our template and build process to make the NPM project page look like it should.
Here's what the page looks like with these changes in place: https://www.npmjs.com/package/sw-appcache-behavior

Tweaks to produce a functional NPM project page.

---

gulpfile.babel.js
npm-shrinkwrap.json

Fixes #5
This updates the `gulp test` command to ensure that failures always cause the process to exit with a non-zero error code.
It also resolves an issue that was due to the `gh-pages` module pulling in a dependency that broke the newer `selenium-webdriver` modules.

gulpfile updates

---

projects/sw-appcache-behavior/README.md
projects/sw-appcache-behavior/package.json
projects/sw-appcache-behavior/src/client-runtime.js

R: @jakearchibald @addyosmani @wibblymat @gauntface
Fixes #18 
This code checks the age of the response from the AppCache manifest request, and if it's older than 24 hours, makes another request using `cache: reload` to (ideally) bypass the cache, to work around http://alistapart.com/article/application-cache-is-a-douchebag#section6
I'm using `cache: reload` here, which unfortunately isn't universally supported in browsers right now. The alternative would be to append cache-busting URL parameters to the request, but I feel like it's in keeping with the spirit of this library to use the primitives provided by the platform. This is also an additional nice-to-have feature beyond the core functionality of the library, so if `cache: reload` doesn't have an effect, we're no worse off than we …

Cache bust manifest request when the response is > 24 hours old.

---

README.md
gulpfile.babel.js
lib/browserify-tests.js
lib/idb-helper.js
lib/log.js
lib/scope.js
npm-shrinkwrap.json
package.json
projects/sw-offline-google-analytics/README.md
projects/sw-offline-google-analytics/demo/index.html
projects/sw-offline-google-analytics/demo/service-worker.js
projects/sw-offline-google-analytics/package.json
projects/sw-offline-google-analytics/src/lib/constants.js
projects/sw-offline-google-analytics/src/lib/enqueue-request.js
projects/sw-offline-google-analytics/src/lib/replay-queued-requests.js
projects/sw-offline-google-analytics/src/offline-google-analytics-import.js
projects/sw-offline-google-analytics/test/automated-suite.js
projects/sw-offline-google-analytics/test/unit/enqueue-request.js
projects/sw-offline-google-analytics/test/unit/index.html
projects/sw-offline-google-analytics/test/unit/replay-queued-requests.js
templates/README.hbs

CC: @philipwalton @igrigorik 
Fixes #8 #19 
This adds the code for a new `sw-offline-google-analytics` project, along with a quick demo and tests. The underlying code is conceptually similar to what's been deployed elsewhere as part of larger projects (like IOWA), and I've gotten some feedback on it from @igrigorik and @philipwalton in the past.
One of the larger changes to that existing codebase was to refactor the imported code into a couple of different modules that handle IndexedDB interactions. I then wrote some tests against those modules. Hopefully this makes up to some extent for not being able to put together a meaningful end-to-end automated test that simulates a lack of network connectivity.

sw-offline-google-analytics initial release

---

package.json
projects/sw-offline-google-analytics/package.json
projects/sw-offline-google-analytics/test/unit/replay-queued-requests.js

CC: @addyosmani @wibblymat @gauntface
Fixes #35 
Mocks Date.now() so that we can reliably test the `qt=` offset.
It also bumps the version in `package.json` to 1.0.1, to get it ready to be deployed.
Tests are still broken in Firefox; that's being tracked in #22

Fixes the test of the qt= parameter.

---

gulpfile.babel.js
package.json
projects/sw-appcache-behavior/test/automated-suite.js
projects/sw-offline-google-analytics/test/automated-suite.js

R: @gauntface 
CC: @ebidel @addyosmani @wibblymat 
Fixes #22
This updates the project to use the 0.1.1 release of `sw-testing-helpers` along with the new `selenium-assistant` dependency.
_Unforunately_, this still leads to broken tests with Firefox. While we are now using the Marionette driver, which works with Firefox 48+, the combination of Marionette + `selenium-webdriver` 2.53 makes it impossible to set the async script timeout. So the Travis CI tests are still failing.
https://github.com/GoogleChrome/sw-testing-helpers/issues/48 tracks updating `sw-testing-helpers` to use `selenenium-webdriver` 3.0 betas, which fixes the issue with timeouts.

Moves to sw-testing-helpers 0.1.1

---

gulp-tasks/serve.js

R: @jeffposnick @addyosmani @wibblymat @gauntface @ebidel
'gulp serve' currently serve out of projects folder where as I see all the code has moved to 'packages' folder

changing gulp serve directory

---

lib/.eslintrc
package.json
packages/sw-offline-google-analytics/.eslintrc
packages/sw-offline-google-analytics/.npmignore
packages/sw-offline-google-analytics/README.md
packages/sw-offline-google-analytics/build.js
packages/sw-offline-google-analytics/demo/index.html
packages/sw-offline-google-analytics/demo/service-worker.js
packages/sw-offline-google-analytics/package.json
packages/sw-offline-google-analytics/src/index.js
packages/sw-offline-google-analytics/src/lib/constants.js
packages/sw-offline-google-analytics/src/lib/enqueue-request.js
packages/sw-offline-google-analytics/src/lib/replay-queued-requests.js
packages/sw-offline-google-analytics/test/.eslintrc
packages/sw-offline-google-analytics/test/automated-suite.js
packages/sw-offline-google-analytics/test/unit/enqueue-request.js
packages/sw-offline-google-analytics/test/unit/index.html
packages/sw-offline-google-analytics/test/unit/replay-queued-requests.js

This adds the offline-analytics back in.
The major thing to change was the tests.
Previously everything was run through browserify. I've switched to include appropriate files in the HTML page directly rather than require them in and I've built the tested files at build time rather than in the test itself.
The tested files are built into `build/test/` in sw-offline-google-analytics and I've added that directory to npmignore.

Adding back in in the analytics suite

---

.travis.yml
README.md
gulp-tasks/test.js
packages/sw-lib/test/automated-test-suite.js
packages/sw-lib/test/browser-unit/sw-unit/cache-revisioned-assets.js
packages/sw-lib/test/browser-unit/sw-unit/router.js
templates/README.hbs

This is the first step in fixing the remaining issues on: #48
> I believe we currently only display a single build status for our CI for the overall repo. I'd like to suggest we also include badges for individual projects in the README so folks can instantly tell what is green and what is not.
This PR doesn't include the individual shields, but I will do that tomorrow in a follow up PR once I get the server accessible somewhere.

Adding matrix to travis

---

build-utils.js
package.json
packages/sw-appcache-behavior/build.js
packages/sw-background-sync-queue/build.js
packages/sw-background-sync-queue/package.json
packages/sw-broadcast-cache-update/build.js
packages/sw-cache-expiration/build.js
packages/sw-cli/build.js
packages/sw-lib/build.js
packages/sw-offline-google-analytics/build.js
packages/sw-offline-google-analytics/package.json
packages/sw-precaching/build.js
packages/sw-routing/build.js
packages/sw-runtime-caching/build.js

CC: @deanhume
This PR refactors much of the common build boilerplate into a helper method. That helper method also takes care of generating both minified and non-minified output, which fixes #31.
There are some packages that still require slightly different build setups, either due to their testing requirements or due to their legacy packaging requirements. In those cases I've switched over the part of the build that could be abstracted out into the general configuration, and left behind the things that needed to stay separate.

Refactor the build process; build minified + non-minified libraries

---

packages/sw-precaching/src/lib/revisioned-cache-manager.js

See https://github.com/GoogleChrome/sw-precache/pull/233
The same thing should apply here.

Explicitly set `redirect: follow` when precaching

---

packages/sw-cli/src/cli/index.js
packages/sw-cli/src/lib/errors.js
packages/sw-cli/src/lib/log-helper.js
packages/sw-cli/test/cli-file-extensions.js

Fixes #82
This adds in the ability to select file extensions that the developer would wish to cache under the current directory.
This may need changed if developers aren't a fan of it, but I think it matches precache in terms of just working (everything is selected by default) but adds a nice level of flexibility to cut out unexpected files.

Adding tests for file extension selection

---

packages/sw-runtime-caching/demo/service-worker.js
packages/sw-runtime-caching/src/lib/request-wrapper.js

Fixes #99
This adds a new `waitOnCache` option that can be passed to `RequestWrapper#fetchAndCache()`. I *think* that's enough to allow @gauntface to start using `RequestWrapper` inside the precaching code, which would be a nice thing to do to ensure that all fetches/caching goes through a common code path.
If there's anything else that's needed to make `RequestWrapper` usable, @gauntface, let me know and I'll adjust this PR.
This also fixes up some paths in the demo code, which is unfortunately how I'm testing the changes. (Real tests are forthcoming!)

Adds a waitOnCache parameter to fetchAndCache()

---

templates/Project-README.hbs

Tiny fix to the URLs we point to from the generated docs.

Use the master, instead of the future-of-sw-tooling, branch

---

packages/sw-lib/test/browser-unit/sw-unit/router.js
packages/sw-routing/demo/service-worker.js
packages/sw-routing/src/lib/express-route.js
packages/sw-routing/src/lib/regexp-route.js
packages/sw-routing/src/lib/route.js
packages/sw-routing/src/lib/router.js

Fixes #107 
This leads to less cruft being passed along to the handler's `params` when using the `RegExpRoute` or `ExpressRoute` classes along with capture groups/named parameters.
I've got some tests for this module in flight at https://github.com/GoogleChrome/sw-helpers/tree/sw-routing-tests and I'll add tests for this modified functionality as part of a PR for that branch.

Clean up the parameters that are passed to the handler

---

packages/sw-lib/test/browser-unit/sw-unit/caching-strategies.js

Fixes #122
Just removes a now unnecessary cacheName parameter.

Remove cacheName from sw-lib cachingStrategy.

---

build-utils.js

Diagnosed through memory snapshot
Fixes #149
This is just an initial PR to moving over to new doc site. I am expecting that being able to build all projects and update README's using handlebars will be desired so having current gulp documentation is desirable.

Fixes the stack issue with gulp-documentation

---

gulp-tasks/lint.js
packages/sw-cli/src/cli/index.js
packages/sw-cli/test/build-file-manifest.js
packages/sw-cli/test/end-to-end.js

This PR should filter out the manifest itself from the generated file manifest.
NOTE: This will need re-running on AppVeyor once #129 is landed.

Remove manifest

---

lib/error-factory.js
packages/sw-routing/src/lib/error-factory.js
packages/sw-routing/src/lib/express-route.js

Add in same-origin check for ExpressRoute

---

packages/sw-appcache-behavior/package.json
packages/sw-background-sync-queue/package.json
packages/sw-cli/package.json
packages/sw-lib/package.json
packages/sw-offline-google-analytics/package.json

Fixes #137
Just adds a files array to packages that don't currently have one (Mine and Prateeks ;) )

Excludes build.js and 'test/' from exported modules.

---

packages/sw-precaching/src/lib/controllers/base-cache-manager.js
packages/sw-precaching/src/lib/controllers/revisioned-cache-manager.js
packages/sw-precaching/test/browser-unit/cache-testing.js
packages/sw-runtime-caching/src/lib/error-factory.js
packages/sw-runtime-caching/src/lib/request-wrapper.js

Fixes #178 
The one behavior I'm unsure of is how to highlight that the cache of the response didn't occur because it was an invalid response.
For now I've implemented a check for (!cacheable && waitOnCache) => i.e. the developer wanted to wait on the cache.put() that is never going to happen so throw. Not the nicest solution, but not sure how else to approach this use case.

Fetch and cache

---

packages/sw-cli/src/lib/generate-sw.js

This is related to https://github.com/GoogleChrome/sw-helpers/pull/199, which I should have looked at when it came through.
I don't understand what this promise returns. It should say something like 'resolves to void', 'resolves to a boolean value indicating...', or 'resolves to a reference to the new `Widget` instance, for example.

Minor edits.

---

packages/sw-lib/build.js

R: @gauntface
Adding in `.mjs` output seems to work fine, and it's needed to consume `sw-lib` as an ES module.
Hopefully this was just an oversight and there isn't a technical reason why we can't output an ES module here.

Add ES2015 .mjs module output to the sw-lib build process

---

packages/sw-build/src/lib/errors.js
packages/sw-build/src/lib/generate-file-manifest.js
packages/sw-build/src/lib/templates/file-manifest-es2015.tmpl
packages/sw-build/src/lib/utils/write-file-manifest.js
packages/sw-build/test/lib-write-file-manifest.js

Fixes #221 
I've added an extra test to confirm that the exception we expect is thrown when a bad format is passed in. I didn't add an extra test to actually confirm that the output of the `writeFileManifest({format: 'es'})` command is a valid ES2015 file with the expected entries, though. I didn't see where the equivalent test was to confirm that the previous output was valid—if you could point me in the right direction, @gauntface, I'll add that test to this PR.

Adds a format option to writeFileManifest(), defaulting to 'iife'

---

lib/assert.js
package.json
utils/build.js

Fixes #98 
This might be a little controversial, so feel free to push back.
The changes here don't end up using `ErrorFactory` in the `assert` module. I think they add functionality to `assert` that brings it on par with what you'd get with `ErrorFactory`, without the overhead of explicitly maintaining a large mapping of error identifiers. Folks are obviously free to continue using `ErrorFactory` where appropriate, e.g. in contexts that assertions don't make sense.
With this change in place, failing assertions that were defined like:
```js
class Router {
registerRoutes({routes} = {}) {
assert.isInstance({routes}, Array);
// ...
}
}
```
produce `Error` objects that have fields like:
```json
{
"message": "Invalid call to Router.registerRoutes() — The 'routes' …
```

Make the Errors generated by assert more useful.

---

packages/sw-cacheable-response/src/lib/plugin.js
packages/sw-lib/src/lib/sw-lib.js
packages/sw-lib/test/browser-unit/cache-revisioned-e2e.js
packages/sw-lib/test/browser-unit/cache-unrevisioned-e2e.js
packages/sw-lib/test/browser-unit/library-namespace.js
packages/sw-lib/test/browser-unit/sw-unit/caching-strategies.js

This adds `sw-cachable-response` to sw-lib, just to make it friendly.
This is part of the writing up a doc on request support (https://github.com/GoogleChrome/sw-helpers/issues/78) and noticed it could be easier

Adding cacheable response plugin

---

lib/assert.js
packages/sw-routing/src/index.js
packages/sw-routing/src/lib/navigation-route.js
packages/sw-routing/src/lib/route.js
packages/sw-routing/test/browser/end-to-end.js
packages/sw-routing/test/browser/register-unit-tests.js
packages/sw-routing/test/static/navigation-route.js
packages/sw-routing/test/sw/namespace.js
packages/sw-routing/test/sw/navigation-route.js

This adds a new `NavigationRoute` class, fairly close to what's described in #169, which matches when `event.request.mode === 'navigate'` and the URL's pathname is in a whitelist (and not in a blacklist).
This lays the groundwork for App Shell routing. I think the next step would be to take this and add in some logic in `sw-lib` that made use of `NavigationRoute` coming after the route that matches precached assets, and allowed the developer to cleanly specify the URL that corresponds to their App Shell HTML.

Adds the NavigationRoute class

---

lib/assert.js
packages/sw-cache-expiration/src/lib/plugin.js
packages/sw-cacheable-response/src/lib/plugin.js
packages/sw-routing/src/lib/navigation-route.js
packages/sw-routing/src/lib/router.js
packages/sw-routing/test/sw/navigation-route.js
packages/sw-runtime-caching/src/lib/request-wrapper.js

This makes `assert` a little more helpful by allowing you to check not just whether a given parameter is an array, but whether the elements in the array are of the expected type/class. Along with the nicer error message formatting that recently landing, this should help developers who, e.g., mistakenly pass in an array of strings when we expect an array of RegExp.

Adds assertions to check the elements in an array

---

packages/sw-runtime-caching/src/lib/request-wrapper.js

Fixes #*259*
This sends a clone of request to plugins in `fetchDidFail` event

fixes bug #259, cloned request for every plugin

---

packages/sw-cache-expiration/src/lib/plugin.js
packages/sw-runtime-caching/src/lib/request-wrapper.js

I came across this when trying out cache expiration along with some opaque responses. We need to get the URL to use as the cache expiration key from the original `Request`, since an opaque `Response` doesn't even expose a URL.
This would have ideally been covered in an end-to-end test, and I've filed https://github.com/GoogleChrome/sw-helpers/issues/264 to track creating that.

Pass URL from original Request to cacheDidUpdate

---

packages/sw-broadcast-cache-update/demo/service-worker.js
packages/sw-broadcast-cache-update/src/index.js
packages/sw-broadcast-cache-update/src/lib/broadcast-cache-update-plugin.js
packages/sw-broadcast-cache-update/src/lib/broadcast-cache-update.js
packages/sw-broadcast-cache-update/src/lib/broadcast-update.js
packages/sw-broadcast-cache-update/src/lib/error-factory.js
packages/sw-broadcast-cache-update/test/browser/register-unit-tests.js
packages/sw-broadcast-cache-update/test/sw/broadcast-cache-update-plugin.js
packages/sw-broadcast-cache-update/test/sw/broadcast-cache-update.js
packages/sw-broadcast-cache-update/test/sw/namespace.js
packages/sw-lib/src/lib/sw-lib.js

It ended up touching many more files/docs/tests than I thought it would, so I've limited this PR to just handle it for the `BroadcastCacheUpdate` class. I'll do follow-up PRs for the other libraries, and use #282 to track all of them.

Refactoring of the Plugin class in BroadcastCacheUpdate

---

.travis.yml
package.json

I broke master branch travis builds with docs - I thought I'd be able to get token + repo url to work, but something has fallen apart - so I've added `npm run publish-gh-pages` and that'll go through the release process (super simple)

Building docs

---

packages/sw-runtime-caching/demo/service-worker.js
packages/sw-runtime-caching/src/lib/network-first.js

Fixes #246
This is code fundamentally the same as [`sw-toolbox`'s implementation](https://github.com/GoogleChrome/sw-toolbox/blob/master/lib/strategies/networkFirst.js#L35).
I feel bad about not having a test for the new functionality, but then I feel worse about not having written tests for any of the `sw-runtime-caching` classes yet. So it balances out?
(But I will write tests for them in a future PR.)

Adds a networkTimeoutSeconds option to the NetworkFirst strategy.

---

packages/sw-lib/src/lib/error-factory.js
packages/sw-lib/src/lib/router.js
packages/sw-lib/test/browser/index.html
packages/sw-lib/test/browser/navigation-route-e2e.js
packages/sw-lib/test/static/sw/navigation-route.js
packages/sw-lib/test/sw/router.js

Fixes #169
Adds support for `swLib.router.registerNavigationRoute('/app-shell-url');` and associated tests.

Adds registerNavigationRoute to sw-lib

---

README.md
docs/contributing.md
docs/examples.md
docs/getting-started/index.md
docs/getting-started/sw-cli.md
docs/index.md
templates/README.hbs

This just moves the sw-lib and sw-cli getting started guides into one place.

Demoting the sw-cli getting started

---

packages/sw-runtime-caching/src/lib/request-wrapper.js

Fixes #304
This leads to log messages along the lines of:
`[RequestWrapper] The response for https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js, with a status of 0, wasn't cached. By default, only responses with a status of 200 are cached. You can configure the cacheableResponse plugin to change this default.`

Adds a log message when a response isn't cached.

---

package.json
packages/sw-appcache-behavior/test/automated-suite.js
packages/sw-background-sync-queue/test/automated-suite.js
packages/sw-broadcast-cache-update/test/automated-test-suite.js
packages/sw-cache-expiration/test/automated-test-suite.js
packages/sw-lib/test/automated-test-suite.js
packages/sw-offline-google-analytics/test/automated-suite.js
packages/sw-routing/test/automated-test-suite.js

Non-important change - but requires are handled by selenium-assistant behind the scenes so we don't need to have them in our files.
Removed Opera because it's nothing but trouble (Driver + Browser seem to be not working together).

Removing unnessecary requires for drivers

---

packages/sw-routing/src/lib/router.js

The diff is pretty busy, but this is basically just shifting the `fetch` handler into the `Router` constructor, and storing the list of routes in a private member variable.
Fixes #354

Use a single fetch handler per Router

---

packages/sw-cacheable-response/src/index.js
packages/sw-cacheable-response/src/lib/cacheable-response-plugin.js
packages/sw-cacheable-response/src/lib/cacheable-response.js
packages/sw-cacheable-response/test/.eslintrc
packages/sw-cacheable-response/test/automated-test-suite.js
packages/sw-cacheable-response/test/browser/register-unit-tests.js
packages/sw-cacheable-response/test/sw/cacheable-response-plugin.js
packages/sw-cacheable-response/test/sw/cacheable-response.js
packages/sw-cacheable-response/test/sw/namespace.js
packages/sw-lib/src/lib/sw-lib.js

This is part of #282, in which the Plugin classes are refactored to extend a base class, and expose the lifecycle methods.
In addition to refactoring, it also adds tests, as this module was previously untested.

Refactor the CacheableResponsePlugin to a separate class

---

packages/sw-cache-expiration/src/index.js
packages/sw-cache-expiration/src/lib/cache-expiration-plugin.js
packages/sw-cache-expiration/src/lib/cache-expiration.js
packages/sw-cache-expiration/test/browser/register-unit-tests.js
packages/sw-cache-expiration/test/sw/cache-expiration-plugin.js
packages/sw-cache-expiration/test/sw/cache-expiration.js
packages/sw-cache-expiration/test/sw/namespace.js
packages/sw-lib/src/lib/strategies.js

R: @addyosmani @gauntface 
This is part of #282, in which the Plugin classes are refactored to extend a base class, and expose the lifecycle methods.

Split up the CacheExpiration and CacheExpirationPlugin classes.

---

utils/server-instance.js

Small change to account for the current URL pattern used for kicking off browser tests. This redirect is useful when manually browsing the directory listing page for a package and starting tests manually.

Small change to the redirected browser test URL

---

packages/sw-lib/test/sw/caching-strategies.js
packages/sw-runtime-caching/src/lib/request-wrapper.js

I'm addressing some of the feedback from https://github.com/GoogleChrome/sw-helpers/pull/399 out of band, as it extends past the boundaries of that PR.
This moves away from `RequestWrapper` saving and then invoking references to the bound functions exposed by plugins, and instead saves references to the plugins themselves, and calls the methods on the plugin instances directly.
The tests confirm that this shouldn't change any behavior.

Save plugin references and call methods on them

---

package.json
packages/sw-cache-expiration/package.json
packages/sw-cache-expiration/src/lib/cache-expiration-plugin.js
packages/sw-cache-expiration/src/lib/cache-expiration.js
packages/sw-cache-expiration/test/browser/end-to-end.js
packages/sw-cache-expiration/test/static/cache-expiration.js
packages/sw-runtime-caching/src/lib/request-wrapper.js

Fixes #437 
This was not fun to track down—the culprit was using `await` inside the function passed to `forEach()` not behaving like I thought. Switching to `for ... of` seems to have done the trick.
This also allows handlers that have opted-in to `waitForCache` behavior to wait until the cache expiration logic has completed before returning a response.
It adds some end-to-end tests to catch the original issue and as general hygiene.

Properly wait on IDB deletion & E2E tests for cache expiration

---

packages/sw-broadcast-cache-update/src/lib/broadcast-cache-update-plugin.js
packages/sw-broadcast-cache-update/src/lib/broadcast-cache-update.js
packages/sw-broadcast-cache-update/src/lib/responses-are-same.js
packages/sw-broadcast-cache-update/test/sw/broadcast-update.js
packages/sw-broadcast-cache-update/test/sw/responses-are-same.js
packages/sw-lib/src/lib/sw-lib.js
packages/sw-lib/test/sw/cache-id.js
packages/sw-lib/test/sw/precache-updates-channel.js
packages/sw-precaching/src/lib/controllers/base-cache-manager.js
packages/sw-precaching/src/lib/controllers/revisioned-cache-manager.js
packages/sw-precaching/src/lib/controllers/unrevisioned-cache-manager.js
packages/sw-precaching/test/sw/plugins.js
packages/sw-runtime-caching/src/lib/request-wrapper.js

Fixes #309, fixes #441
This adds support for a `BroadcastCacheUpdates` plugin that's enabled by default in `SWLib`, and announces when previously cached resources are updated.
I had to account for the fact that `precache()` might append a cache-busting URL parameter when retrieving responses from the network, so there needed to be a bit of massaging via the `cacheKey` parameter inside of `RequestWrapper.fetchAndCache()` to ensure that the proper responses were compared, and the proper URL reported to `BroadcastCacheUpdates`.

Support for a BroadcastCacheUpdate plugin for precached() assets

---

.travis.yml
packages/sw-build-webpack-plugin/build.js
packages/sw-build-webpack-plugin/index.js
packages/sw-build-webpack-plugin/package.json
packages/sw-build-webpack-plugin/test/.eslintrc
packages/sw-build-webpack-plugin/test/node/test.js

R: @prateekbh @addyosmani @gauntface
There are some linting errors in `sw-build-wepback-plugin` that prevent the `gulp test` portion of the `npm run publish-release` process from completing. This fixes those errors.
(I'm not sure why those errors weren't flagged in Travis CI to begin with?)

Build/linting fixes for sw-build-webpack-plugin

---

packages/sw-build-webpack-plugin/index.js
packages/sw-build-webpack-plugin/test/node/test.js
packages/sw-build/src/index.js
packages/sw-build/src/lib/errors.js
packages/sw-build/src/lib/generate-file-manifest.js
packages/sw-build/src/lib/generate-sw.js
packages/sw-build/src/lib/get-file-manifest-entries.js
packages/sw-build/src/lib/inject-manifest.js
packages/sw-build/src/lib/utils/copy-sw-lib.js
packages/sw-build/src/lib/utils/get-file-details.js
packages/sw-build/test/node/generate-file-manifest.js
packages/sw-build/test/node/generate-sw-e2e.js
packages/sw-build/test/node/generate-sw.js
packages/sw-build/test/node/get-file-manifest-entries.js
packages/sw-build/test/node/injection-manifest.js
packages/sw-cli/src/index.js
packages/sw-cli/src/lib/questions/ask-extensions-to-cache.js
packages/sw-cli/test/node/cli-file-extensions.js
packages/sw-cli/test/node/generate-sw-e2e.js
packages/sw-cli/test/static/example-project-1/index.html
packages/sw-cli/test/utils/e2e-sw-validator.js

R: @jeffposnick @addyosmani @prateekbh 
Fixes #451 #453 
This makes a few changes:
- rootDirectory is now globDirectory
- dest must now be a full path for the output file
- swFile is now swPath and is seperate from anything else.
This actually sanitzed a lot of logic which is normally a good sign that the API is a better way to go.
Let me know what you think (Prateek I changed the swFile to swPath in the plugin, please let me know if that's not ok).

Glob directory

---

package.json
packages/sw-precaching/src/lib/controllers/base-cache-manager.js
packages/sw-runtime-caching/src/lib/clean-response-copy.js
packages/sw-runtime-caching/src/lib/request-wrapper.js
packages/sw-runtime-caching/test/sw/request-wrapper.js

Fixes #173 
This is analogous to the change in https://github.com/GoogleChrome/sw-precache/pull/241

Clean redirected responses

---

packages/sw-runtime-caching/src/lib/stale-while-revalidate.js

Fixes #316 
Clarify that that staleWhileRevalidate() is the new fastest().
*Please ensure that `gulp lint test` passes locally prior to filing a PR!* 
__Fails on files that I'm not touching in this PR.__

staleWhileRevalidate() is the new fastest()

---

gulp-tasks/build.js
package.json
packages/sw-background-sync-queue/build.js
packages/sw-background-sync-queue/test/browser/background-sync-idb-helper.js
packages/sw-background-sync-queue/test/browser/background-sync-queue.js
packages/sw-background-sync-queue/test/browser/broadcast-manager.js
packages/sw-background-sync-queue/test/browser/queue-utils.js
packages/sw-background-sync-queue/test/browser/request-manager.js
packages/sw-background-sync-queue/test/browser/request-queue.js
packages/sw-background-sync-queue/test/browser/response-manager.js
packages/sw-background-sync-queue/test/config.json
packages/sw-broadcast-cache-update/build.js
packages/sw-cache-expiration/build.js
packages/sw-cacheable-response/build.js
packages/sw-lib/build.js
packages/sw-offline-google-analytics/build.js
packages/sw-offline-google-analytics/test/browser/enqueue-request.js
packages/sw-offline-google-analytics/test/browser/replay-queued-requests.js
packages/sw-precaching/build.js
packages/sw-routing/build.js
packages/sw-runtime-caching/build.js
utils/build.js

This is a substantial update to the build process, with the following changes:
- Moving from gulp wrappers on top of Rollup, babili, and others to directly using Rollup. This fixes #477, sourcemap generation.
- No longer including the async-to-generator transpilation, since async/await are natively supported in production Chrome and Firefox. We can turn this back on if we need.
- Changing the build process for `sw-offline-google-analytics` and `sw-background-sync-queue` to only generate unminimized `iife` bundles of the individual `.js` files that they need in order to run their tests, and to generate them all in parallel instead of sequentially.
- Adding in an `.npmignore` file to the directory that hosts the built tests for `sw-offline-google-analytics` and …

Major revamp of the build process

---

docs/index.md

In my feedback for the Occupop mockups I said that visual assets took too much space and pushed content that we want people to read off the visible area. I mentioned that thinning my own text would also help this.

Trim landing page text.

---

lib/assert-min.js
lib/assert.js
lib/error-stack-parser-no-op.js
package.json
packages/sw-broadcast-cache-update/test/sw/broadcast-cache-update-plugin.js
packages/sw-broadcast-cache-update/test/sw/broadcast-cache-update.js
packages/sw-broadcast-cache-update/test/sw/namespace.js
packages/sw-broadcast-cache-update/test/sw/responses-are-same.js
utils/build.js

This is based off the discussion in https://github.com/GoogleChrome/sw-helpers/issues/361#issuecomment-298640521
It swaps out the real [`error-stack-parser`](https://www.npmjs.com/package/error-stack-parser) module import for an import that has the same interface but is effectively a no-op. You lose a bit of context if an assertion fails without the real module, but our assertions are really meant to catch errors in a development environment, not after the service worker has been deployed.
This gets the production `sw-lib.min.js` bundle size down from 50249 bytes (14938 bytes gzip-ed) to 45450 bytes (13468 bytes gzip-ed).
I had to change a few of the tests that specifically examined the assertion failures to use the unminified bundle, but other than that, it's …

Omit error-stack-parser from the minified bundles

---

gulp-tasks/build.js
package.json
packages/sw-build-webpack-plugin/build.js
packages/sw-build-webpack-plugin/package.json
packages/sw-build/build.js
packages/sw-build/package.json
packages/sw-cli/build.js
packages/sw-cli/package.json

R: @prateekbh @gauntface
This is the first half of #502, with some small changes to the build and `npm` packaging for the projects that are consumed as CommonJS modules or are CLIs.
`fs-extra` v3+ [supports promises natively now](https://github.com/jprichardson/node-fs-extra#usage) (yay!) so I was able to get rid of some of the extra explicit promise wrapping.

Build output normalization for CommonJS/node projects.

---

.travis.yml
appveyor.yml
gulp-tasks/build.js
lerna.json
package.json
packages/sw-cli/test/node/generate-sw-e2e.js
utils/build.js

I **think** this ends up accomplishing what we want for publishing, via `gulp lerna-publish`.
It does it by:
1. Running the publishing flow with git and npm integration turned off. This updates the `package.json` and `lerna.json` `version` fields for the modified packages in the local working directory, without committing anything.
2. Automatically updating the `main` and `module` fields of all packages to pick up any modified versions.
3. Re-running the publishing flow, this time with git and npm enabled, but with a forced version passed in, read from the current `lerna.json`. This will then commit everything to GitHub and push to npm.
Rather than sprinkling some of the build steps in `package.json`'s `scripts` and others in `gulp`, I moved everything …

gulp wrappers for lerna boostrapping and publishing

---

lib/assert.js
lib/environment.js
lib/log-helper.js
packages/sw-background-sync-queue/build.js
packages/sw-lib/src/index.js
packages/sw-lib/src/lib/sw-lib.js
packages/sw-offline-google-analytics/build.js
packages/sw-precaching/src/index.js
utils/build.js

Fixes #444, fixes #487 
This adds a new `environment.js` module which exposes a few functions to interrogate the current runtime.
It uses the same `rollup-replace-plugin` method we're using elsewhere to determine whether we're in a production or development bundle.
It adds some logging to the `SWLib` constructor based on various combinations of localhost/prod and dev/prod bundles. Here's an example of the output for localhost + dev bundle combo:
Putting startup logging logic into `SWLib`'s constructor seemed like the cleanest approach, since we expect that to be the most typical entry point to the library. Putting the logic into a code path executed by the lower-level, standalone modules seemed like it would just confuse developers who were only using a smaller …

Dev + prod logging

---

packages/sw-build-webpack-plugin/package.json
packages/sw-build/package.json
packages/sw-build/test/node/dependency-check.js
packages/sw-cli/package.json
packages/sw-cli/test/node/dependency-check.js

Fixes #527
fs-extra is required but marked as devDep. Added some more tests to dependency checks unit tests to guard against this in the future.

Adding checks for dependencies and marking as required

---

packages/workbox-build/src/lib/generate-sw.js
packages/workbox-build/src/lib/templates/sw.js.tmpl
packages/workbox-build/src/lib/write-sw.js
packages/workbox-build/test/node/lib-write-sw.js

Realised I'd added this option to workbox-sw and *not* workbox-build.
Because JSON.stringify() prints regexes as "{}" I've had to do some hackery to get the right output.

Adding ignoreUrlParamsMatching to workbox-build

---

packages/workbox-cli/test/node/generate-sw-e2e.js

This is related to #516, but since there's still a `.catch()` in the `after()` block to account for an issue on Windows, I'm going to leave that open.
Hopefully this does it. It looks good on my local machine at least, though I'm still not sure why it was passing in the Travis CI environment before this change.
Let's see how the CI builds go with this PR.

Hopefully fix generate-sw-e2e.js

---

packages/workbox-sw/src/lib/strategies.js
packages/workbox-sw/test/sw/caching-strategies.js

The `NetworkFirst` constructor takes a `networkTimeoutSeconds` parameter, which wasn't being passed through when it was constructed via `workboxSW.strategies.networkFirst({networkTimeoutSeconds})`.
This PR causes the options that are passed in to `workboxSW.strategies.<strategy>(options)` to be passed through to the underlying Handler's constructor.

Pass through options to the Handler constructor.

---

packages/workbox-build/src/lib/templates/sw.js.tmpl
packages/workbox-build/src/lib/write-sw.js
packages/workbox-build/test/node/lib-write-sw.js

R: @gauntface
Fixes #535
I'm not sure if it was the switch from `rootDirectory` to `globDirectory`, or my fiddling with [`copy-workbox-sw.js`](https://github.com/GoogleChrome/workbox/blob/1697b830fb2b315d5a60f3e7eef0bad000ee1058/packages/workbox-build/src/lib/utils/copy-workbox-sw.js) that led to the breakage in #535 to begin with.
There's already a `path.relative()` performed at https://github.com/GoogleChrome/workbox/blob/1697b830fb2b315d5a60f3e7eef0bad000ee1058/packages/workbox-build/src/lib/generate-sw.js#L112, and the one I'm removing seems like it was actively causing trouble.
This *seems* to do the right thing for me now, in that when testing locally, basic use cases result in a generated service worker file that has a correct path in `importScripts()`
That being said, I'd really …

Don't calculate the relative path twice

---

.gitignore
packages/workbox-cli/src/index.js
packages/workbox-cli/src/lib/constants.js
packages/workbox-cli/src/lib/errors.js
packages/workbox-cli/src/lib/utils/get-config.js
packages/workbox-cli/src/lib/utils/save-config.js
packages/workbox-cli/test/node/generate-sw-e2e.js
packages/workbox-cli/test/node/inject-manifest-e2e.js
packages/workbox-cli/test/node/utils-get-config.js

R: @gauntface 
The general logic is:
- If `--config-file` isn't given, then attempt to read a `./workbox-cli-config.js` file.
- If that doesn't exist, then continue with the previous flow.
- If it does exist, then continue with the previous flow.
- If `--config-file` is given, then attempt to read it (supporting both relative and absolute paths).
- If that doesn't exist, then treat it as a fatal error.
- If it does exist, then treat it the same way we were previously treating the default config.
This also adds in a logging statement letting the developer know which config file is being read from, as a general heads-up.

Adds support for a --config-file CLI flag.

---

packages/workbox-precaching/src/index.js
packages/workbox-precaching/src/lib/controllers/base-cache-manager.js
packages/workbox-precaching/src/lib/controllers/revisioned-cache-manager.js
packages/workbox-precaching/test/browser/cache-testing.js
packages/workbox-precaching/test/sw/basic.js
packages/workbox-precaching/test/sw/cookies.js
packages/workbox-precaching/test/sw/failing-cache-tests.js
packages/workbox-precaching/test/sw/unrevisioned-caching.js

R: @jeffposnick @addyosmani @jpmedley 
Only possibly contentious aspect of this PR is that it removes the unrevisioned cache manager. It's not used anywhere and frankly has limited use. Rather than support it when it's not needed I've removed it and we can see if it serves a purpose and re-add in after launch if needed.

Precaching sweep

---

packages/workbox-cli/test/node/cli-file-extensions.js
packages/workbox-cli/test/node/cli-file-manifest-name.js
packages/workbox-cli/test/node/cli-root-dir.js
packages/workbox-cli/test/node/cli-save-config.js
packages/workbox-cli/test/node/cli-sw-dest.js
packages/workbox-cli/test/node/cli-sw-src.js
packages/workbox-google-analytics/test/browser/replay-queued-requests.js
packages/workbox-precaching/test/static/duplicate-entries/duplicate-entries-revisioned-sw.js
packages/workbox-precaching/test/static/duplicate-entries/duplicate-entries-unrevisioned-sw.js
packages/workbox-runtime-caching/test/sw/network-first.js
packages/workbox-runtime-caching/test/sw/network-only.js
packages/workbox-runtime-caching/test/sw/stale-while-revalidate.js
packages/workbox-sw/test/sw/claim-clients-false.js
packages/workbox-sw/test/sw/claim-clients-true.js
packages/workbox-sw/test/sw/directory-index-custom.js
packages/workbox-sw/test/sw/directory-index-default.js
packages/workbox-sw/test/sw/directory-index-false.js
packages/workbox-sw/test/sw/skip-waiting-false.js
packages/workbox-sw/test/sw/skip-waiting-true.js
packages/workbox-webpack-plugin/test/node/test.js

I ran https://github.com/hurrymaplelad/sinon-codemod against our codebase to automatically update to the currently-supported syntax.
This fixes the
```
sinon.stub(obj, 'meth', fn) is deprecated and will be removed from the public API in a future version of sinon.
Use stub(obj, 'meth').callsFake(fn).
Codemod available at https://github.com/hurrymaplelad/sinon-codemod
```
noise in our test output.

Moves to the current sinon syntax.

---

packages/workbox-build/src/lib/errors.js
packages/workbox-build/src/lib/utils/runtime-caching-converter.js
packages/workbox-build/src/lib/write-sw.js
packages/workbox-build/test/node/lib-write-sw.js
packages/workbox-build/test/node/utils-runtime-caching-converter.js

Fixes #574 
This should give us parity with the full set of options that `runtimeCaching` in `sw-precache` supported.

More robust runtimeCaching conversion.

---

packages/workbox-build/src/lib/constants.js
packages/workbox-build/src/lib/generate-sw.js
packages/workbox-build/src/lib/get-file-manifest-entries.js
packages/workbox-cli/src/index.js
packages/workbox-cli/test/static/example-project-1/.hidden-directory/hello.html
packages/workbox-cli/test/static/example-project-1/.hidden-directory/hello.js
packages/workbox-cli/test/static/example-project-1/node_modules/subdirectory/test-subdirectory.html
packages/workbox-cli/test/static/example-project-1/node_modules/subdirectory/test-subdirectory.js
packages/workbox-cli/test/static/example-project-1/node_modules/test-top-level.html
packages/workbox-cli/test/static/example-project-1/node_modules/test-top-level.js
packages/workbox-cli/test/utils/validator/fake-run-and-compare.js

Fixes #326
Ignore node_modules by default

Default cli ignores

---

packages/workbox-build/src/lib/utils/filter-files.js
packages/workbox-build/test/node/generate-sw-e2e.js
packages/workbox-build/test/node/get-file-manifest-entries.js
packages/workbox-build/test/node/injection-manifest.js
packages/workbox-build/test/node/utils-filter-files.js
packages/workbox-cli/test/node/inject-manifest-e2e.js
packages/workbox-cli/test/utils/e2e-sw-validator.js
packages/workbox-cli/test/utils/validator/fake-run-and-compare.js
packages/workbox-cli/test/utils/validator/test-in-browser.js
packages/workbox-webpack-plugin/test/node/e2etest.js

Fixes #560
This fixes up the remaining tests from @happyahluwalia's PR

Temp leading slash

---

packages/workbox-cli/src/lib/questions/ask-root-of-web-app.js

Fixes #356
Somewhat tentative. Not sure what the best behavior is in this scenario. It is possible a developer has a flat directory structure, in which case this would work perfect for them, but this is a rare case, and in this scenario, we could just assume the directory is the current directory given we know that there are no subdirectories.
What do others think?

Fixes #356

---

gulp-tasks/test.js
package.json
packages/workbox-background-sync/src/lib/request-manager.js
packages/workbox-background-sync/src/lib/request-queue.js
packages/workbox-background-sync/test/browser/background-sync-queue-plugin.js
packages/workbox-background-sync/test/browser/background-sync-queue.js
packages/workbox-background-sync/test/browser/request-manager.js
packages/workbox-background-sync/test/browser/request-queue.js

Fixes #597
After this PR if during the entire replay process any request fails, we'll be passing a rejected promise to `event.waitUntil` of `sync` event, so that browser can replay the failed requests

Bg sync replay fix

---

packages/workbox-routing/src/lib/router.js
packages/workbox-routing/test/sw/router.js
packages/workbox-sw/src/lib/router.js
packages/workbox-sw/test/sw/router.js

There weren't any existing unit tests for `Router`, so I added a few of those, too.
Fixes #390

Support for unregistering routes & returning routes registered by workbox-sw

---

packages/workbox-precaching/src/lib/controllers/base-cache-manager.js
packages/workbox-sw/src/lib/error-factory.js
packages/workbox-sw/src/lib/router.js
packages/workbox-sw/src/lib/workbox-sw.js
packages/workbox-sw/test/sw/router.js

CC: @jmtt89 @mikefowler
This is an alternative to https://github.com/GoogleChrome/workbox/pull/639, as discussed in that PR.
Fixes #385 and fixes #636

Cleaner way to create generic Route instances via registerRoute()

---

packages/workbox-build/src/lib/errors.js
packages/workbox-build/src/lib/utils/runtime-caching-converter.js
packages/workbox-build/test/node/lib-write-sw.js
packages/workbox-build/test/node/utils-runtime-caching-converter.js

CC: @samthor 
Fixes #661
This follows from #644, since we can now support passing in non-GET methods via `workboxSW.registerRoute()`.

Support for registering non-GET via runtimeCaching

---

gulp-tasks/build.js
gulp-tasks/lerna.js
gulpfile.js
lerna.json
packages/workbox-precaching/test/sw/revisioned-caching.js

Publishing is currently broken for test:dev. This PR also pulls out the available lerna tasks to a seperate file and resets the current lerna version.

Moving lerna tasks out into seperate file and fixing tests

---

packages/workbox-build/src/index.js
packages/workbox-build/src/lib/generate-file-manifest.js
packages/workbox-build/src/lib/generate-sw.js
packages/workbox-build/src/lib/get-file-manifest-entries.js
packages/workbox-build/src/lib/inject-manifest.js
packages/workbox-build/src/lib/log-helper.js
packages/workbox-build/src/lib/utils/copy-workbox-sw.js
packages/workbox-build/src/lib/utils/filter-files.js
packages/workbox-build/src/lib/utils/get-composite-details.js
packages/workbox-build/src/lib/utils/get-file-hash.js
packages/workbox-build/src/lib/utils/get-file-size.js
packages/workbox-build/src/lib/utils/get-string-details.js
packages/workbox-build/src/lib/utils/get-string-hash.js
packages/workbox-build/src/lib/utils/modify-url-prefix.js
packages/workbox-build/src/lib/utils/runtime-caching-converter.js
packages/workbox-build/src/lib/utils/write-file-manifest.js
packages/workbox-build/src/lib/write-sw.js

Add use strict to generate-sw for Node 4 support

---

.eslintrc.js
packages/workbox-precaching/src/lib/controllers/base-cache-manager.js
packages/workbox-precaching/src/lib/controllers/revisioned-cache-manager.js
packages/workbox-precaching/test/static/skip-and-claim.js
packages/workbox-precaching/test/sw/revisioned-caching.js
utils/test-runner.js

This adds some logging for pre-cached assets letting developers know which urls were updated and which were already up to date.

Adding some logging for the precache details

---

packages/workbox-background-sync/src/lib/request-queue.js
packages/workbox-background-sync/test/browser/request-queue.js

Fixes #674 
Fixes the repopulation of the list and also adds test coverage for it

fixing queue initialization bug

---

packages/workbox-cache-expiration/src/lib/cache-expiration-plugin.js
packages/workbox-cache-expiration/src/lib/cache-expiration.js
packages/workbox-cache-expiration/test/browser/end-to-end.js
packages/workbox-cache-expiration/test/static/cache-first-max-age-seconds.js
packages/workbox-runtime-caching/src/lib/request-wrapper.js
utils/server-instance.js

CC: @pbakaus
Fixes #691
This fixes a bug that would prevent a response used in a cache-first handler from properly triggering `maxAgeSeconds`-based expiration iff that response lacked a `Date:` header. A CORS-response without the `Date:` header specifically whitelisted via [`Access-Control-Expose-Headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers) could trigger this scenario, as @pbakaus encountered.
This also changes the method signature of the `cacheWillMatch` lifecycle callback to be `async` (i.e. return a `Promise`), since we now want to wait for it to complete before returning a cached response to the client (to ensure that any expiration that's necessary gets performed). That should (arguably) be …

Fixes a bug with cacheFirst handler + maxAgeSeconds + CORS request

---

packages/workbox-sw/package.json

Fixes #703 
I *think* this is the right approach to ensure that Lerna properly bumps the `workbox-sw` version whenever any of the packages that it depends on also changes. We'll see if that's actually the case when I do a patch-level publish right after merging this.
Any feedback about whether I should be doing this different is appreciated.

Add all of workbox-sw's devDependencies to fix Lerna's versioning.

---

.eslintrc.js
packages/workbox-sw/test/browser/cache-revisioned-e2e.js
packages/workbox-sw/test/browser/ignore-url-params.js
packages/workbox-sw/test/browser/library-namespace.js
packages/workbox-sw/test/browser/navigation-route-e2e.js
packages/workbox-sw/test/sw/basic.js
packages/workbox-sw/test/sw/cache-id.js
packages/workbox-sw/test/sw/cache-revisioned-assets.js
packages/workbox-sw/test/sw/caching-strategies.js
packages/workbox-sw/test/sw/claim-clients-false.js
packages/workbox-sw/test/sw/claim-clients-true.js
packages/workbox-sw/test/sw/claim-clients.js
packages/workbox-sw/test/sw/directory-index-custom.js
packages/workbox-sw/test/sw/directory-index-default.js
packages/workbox-sw/test/sw/directory-index-false.js
packages/workbox-sw/test/sw/directory-index.js
packages/workbox-sw/test/sw/precache-updates-channel.js
packages/workbox-sw/test/sw/router.js
packages/workbox-sw/test/sw/skip-waiting-false.js
packages/workbox-sw/test/sw/skip-waiting-true.js
packages/workbox-sw/test/sw/skip-waiting.js

Address the issue in #716, unfortunately it seems like the bundling is causes issues since some tests don't run with a clean slate.
Currently there are two tests failing, and I can confirm both of them pass if they're the only tests included in the bundle.

Update workbox-sw tests to support bundling

---

packages/workbox-build/src/lib/utils/filter-files.js

Fixes issue of custom `manifestTransforms` never being ran as described here: https://github.com/GoogleChrome/workbox/pull/712/files#r131218250
If you'd rather fix it as part of the other PR feel free to close this one, just figured I'd throw it out there if you folks wanted to fix this in a hurry.

fixed: bug that causes passed in manifestTransforms not to run

---

package-lock.json
packages/workbox-sw/src/lib/strategies.js
packages/workbox-sw/src/lib/workbox-sw.js
packages/workbox-sw/test/sw/cache-id.js

R: @addyosmani @gauntface 
CC: @HenrikJoreteg @liuruoran88
This fixes #714 by explicitly changing the method call inside of `WorkboxSW` to indicate that for the internal `CacheOnly` handler use for precached requests, `cacheId` shouldn't be prepended when determining the corresponding cache name.
I decided to go with that approach rather than making a chance in the `RequestWrapper` constructor that checked to see if `cacheId` was already present in the `cacheName`, since you could theoretically imagine calling
```js
new RequestWrapper({
cacheName: 'my-prefix',
cacheId: 'my-prefix',
}});
```
In that situation, the user would expect the effective cache name to be `'my-prefix-my-prefix'`, and we'd want to still allow that.

Fix for multiple cacheId prefixes in the precache handler

---

packages/workbox-routing/src/lib/router.js

I noticed that the JSDocs for `handleFetch` were missing when responding to https://github.com/GoogleChrome/workbox/issues/721

Adds JSDocs for the handleFetch parameter

---

packages/workbox-runtime-caching/src/lib/request-wrapper.js

Fixes #709, fixes #533 
`await` is nice in that it doesn't require the expression to actually evaluate to a promise So both `await Promise.resolve(true)` and `await true` are both valid.
Because of this, I just had to change the code that calls the lifecycle methods to consistently use `await`, and the existing plugins that don't need to do anything asynchronous don't have to be updated.
This opens the doors for new plugins that weren't previously able to return promises, like the Range request helper in #710.
I took the opportunity to add in formal JSDoc for the lifecycle methods, via `@callback`, since that was a longstanding issue.

Adds JSDocs for the lifecycle methods, and awaits the return of each.

---

.eslintrc.js
gulp-tasks/analyze-properties.js
gulpfile.js
infra/tools/analyse-properties.js
package-lock.json
package.json

Here it comes . . . . . . I promise I'm not crazy :-/
This is a tool that pulls out property names and function names. The idea being that if we have a tonne of variables being used that are public or not marked as private, the minifier is unable to rename it. This means the end file size will be larger than it needs to be.
I have no idea if this will be used going forward or not. But after manually going through some of the workbox-core code's and refactor slightly to shave off bundle size ~850 bytes to ~ 750 bytes. Moving forward with much larger code, I suspect that this **might** be useful.
I'd like to keep this in the infra directory just in case it does proof handy and I've added a comment to remove if it doesn't get used / isn't useful.
It …

V3 Analyse Browser Bundles

---

packages/workbox-cli/package.json
packages/workbox-cli/src/bin.js
packages/workbox-cli/src/cli-help.js
packages/workbox-cli/test/static/example-cli-command/example-command.txt
packages/workbox-sw/src/index.js
packages/workbox-sw/src/lib/workbox-sw.js

I've added `workbox` as an additional alias for the CLI. `workbox-cli` is still supported, but there's a console warning logged when it's used with additional context. I've also updated a few places where `workbox-cli` was referenced in comments.
This is the first part of #730, for inclusion in the upcoming `v2.0.0` release.

Move towards using 'workbox' over 'workbox-cli'.

---

packages/workbox-cache-expiration/src/lib/cache-expiration-plugin.js
packages/workbox-cache-expiration/test/sw/cache-expiration-plugin.js
packages/workbox-range-requests/src/lib/cached-range-response-plugin.js
packages/workbox-range-requests/test/sw/cached-range-response-plugin.js
packages/workbox-range-requests/test/sw/handle-range-request.js
packages/workbox-runtime-caching/src/lib/constants.js
packages/workbox-runtime-caching/src/lib/error-factory.js
packages/workbox-runtime-caching/src/lib/request-wrapper.js
packages/workbox-runtime-caching/test/sw/request-wrapper.js
packages/workbox-sw/src/lib/workbox-sw.js

Rename cacheWillMatch to cachedResponseWillBeUsed

---

gulp-tasks/utils/github-helper.js

R: @gauntface
Otherwise, none of the `gulp` tasks will load if you don't have `process.env.GITHUB_TOKEN` set.

Only call github.authenticate() when it's needed.

---

packages/workbox-build/src/lib/utils/get-file-details.js
packages/workbox-build/src/lib/utils/no-revision-for-urls-matching-transform.js

> /home/travis/build/twbs/bootstrap/node_modules/workbox-build/build/lib/utils/get-file-details.js:9
let globbedFiles;
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
build failed on node 4, due to "let".
this should fix it!

use strict to support Node 4

---

packages/workbox-range-requests/src/index.js
packages/workbox-range-requests/src/lib/cached-range-response-plugin.js
packages/workbox-range-requests/src/lib/handle-range-request.js

Current docs for range-request plugin are making jsdocs cranky :( 
Just needed to move the `@module` definition to below the comment.

Adding fixes to the range requests

---

gulp-tasks/build-packages.js
packages/workbox-core/index.mjs
packages/workbox-core/package.json

My previous PR would generate the browser bundle. This PR changes rollup to dynamically mark modules and external modules and will dynamically replace the module import with a global namespace value.
This should be the last piece of infra to support the proposed build flow in: https://github.com/GoogleChrome/workbox/wiki/V3-:-ES2015-Modules-&-Browser-Bundles.
I'll look at CommonJS ASAP.

V3 globals

---

packages/workbox-build/src/lib/utils/filter-files.js

This resulted in backslashes in the URL entries on Windows.
Fixes #771

Fix backslashes replacement.

---

packages/workbox-sw/src/lib/workbox-sw.js
packages/workbox-sw/test/sw/directory-index-custom.js

Fixes #758
This fixes a small bug due to using the wrong variable inside of our WorkboxSW precache route.

Ensure that ignoreUrlParametersMatching works with directoryIndex

---

packages/workbox-background-sync/test/browser/background-sync-queue.js

Fixes #754 and unblocks any pending PRs.
P.S. I'll look into it if I can get more verbose test around this

avoiding flaky test to unblock PRs

---

package-lock.json
package.json
utils/build.js

R: @philipwalton  @addyosmani @gauntface
CC: @poshaughnessy @HenrikJoreteg 
Fixes #812 
I'm hopeful that this should lead to compatibility with Samsung Browser 5, as it's based on Chrome 51. Assuming this is merged, we can publish a pre-release tag of `v2.0.2-alpha` if folks want to test against that in the real world and confirm compatibility prior to the official release.
While we're touching the Babel configs, I took the opportunity to switch from the deprecated `babili` package to its current incarnation, `babel-minify`.
The final, gzipped payload size of the `workbox-sw.prod.js` bundle is 14,560 bytes after applying the transpilation, which is an increase of only ~260 bytes vs. the previous `2.0.1` bundle.

Uses babel-preset-env to transpile our bundled code

---

test/workbox-routing/node/normalizeHandler.mjs
test/workbox-routing/node/route.mjs

Solves point 3 of #814
I know this PR looks like a complete change but thats because I've removed the iffe and indented each line.
Changes are:
- Removed iife
- Moved imports to before where the ENV is changed - this ensures that the import is using the correct NODE_ENV
- Cleared the require cache (workbox-core doesn't expose the assert library in prod and if you require it once with prod, it'll never expose assert).
- Changed the await wrapping to import module and then reference default.
This will likely changed based on discussion in #814 but I really don't want this pattern to be continued, hence this PR.

Tweaking tests to not use the iife

---

packages/workbox-sw/src/lib/workbox-sw.js
packages/workbox-sw/test/sw/cache-id.js

Fixes #839
This change should lead to the cache-first route for precached assets always having precedence over runtime caching routes.
I think this sort of change is safe to roll out as part of a minor release, since while we are changing existing behavior, we're changing it in a way that fixes a previously introduced bug and brings us in line with our documented behavior.

Give a precache-specific Router precedence

---

gulp-tasks/test-integration.js
gulp-tasks/utils/rollup-helper.js
infra/testing/env-it.js
infra/testing/test-server.js
test/workbox-precaching/integration/precache-and-update.js

Found a bug in precaching / core (The `_private` value was being mangled but needed to be reliable in all modules). This integration reproduced the bug and this PR contains the fix.
Also had to move to passing the seleniumAssistant browser (instead of the webdriver instance) so tests can close / reopen browsers - useful to start with clean profile / service worker state.

_private Fix and Precaching Integration Test

---

.eslintrc.js
gulp-tasks/publish-cdn.js
gulp-tasks/test-integration.js
gulp-tasks/utils/build-browser-package.js
gulp-tasks/utils/rollup-helper.js
infra/testing/sw-env.js
lerna.json
packages/workbox-build/src/entry-points/options/base-options.js
packages/workbox-core/utils/cacheWrapper.mjs
packages/workbox-core/utils/indexedDBHelper.mjs
packages/workbox-precaching/models/PrecacheEntry.mjs
packages/workbox-routing/lib/Route.mjs
packages/workbox-sw/index.mjs
packages/workbox-sw/package.json
test/workbox-sw/node/test-WorkboxSW.mjs
test/workbox-sw/static/example.css
test/workbox-sw/static/example.js
test/workbox-sw/static/index.html
test/workbox-sw/static/sw.js

- Adds ability to load modules in workbox-sw
- Three options around this:
1. `modulePathPrefix` allows you to customise the path workbox-sw uses to import modules.
2. `modulePathCb` allows a developers to completely control where a module is looked up.
3. `disableModuleImports` force the library to only use globals and throw an error otherwise.
- Adds new line after description lint rule
- Allows deploying the v3 branch to the CDN regardless of whether it's already deployed or not (Will be helpful for testing)
Biggest question I have with this PR is around how we manage versions on CDN vs NPM.
At the moment we version modules separately so we avoid needless update churn. The CDN updates whenever a new git tag is released.
In this PR, I'm assuming …

V3 sw load mod

---

package-lock.json
package.json
packages/workbox-core/utils/cacheWrapper.mjs
packages/workbox-runtime-caching/CacheFirst.mjs
packages/workbox-runtime-caching/index.mjs
packages/workbox-runtime-caching/package.json
test/workbox-runtime-caching/node/test-CacheFirst.mjs
test/workbox-runtime-caching/utils/response-comparisons.mjs

Adds CacheFirst Strategy.
- Uses the default runtime cache name
- Can be override with options.cacheName in constructor
- plugins can be added to override caching logic etc
- Removed waitOnCache in favor of using event.waitUntil and fixing tests to support this.

V3 CacheFirst

---

gulp-tasks/build.js

R: @addyosmani  @addyosmani @gauntface
Switching to the promise-based `readJSON()`/`writeJSON()` and using `await`/`async` inside the task seems to have cleared up the task completion issues I was seeing.

Use await/async inside of build:update-cdn-details

---

gulp-tasks/publish-cdn.js
gulp-tasks/publish-github.js

This is only useful for us testing stuff out between full publishes, but I just hit it with one of the demos so would be good to land.

For the temporary github and CDN stuff, remove the generated files

---

packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-precaching/default-precaching-export.mjs
test/workbox-precaching/node/test-precaching-module.mjs

This implements #886 minus tests. Wanted to get a gut check on the approach and will add tests in a follow up PR.

Adding the route logic

---

packages/workbox-sw/index.mjs
test/workbox-sw/node/test-WorkboxSW.mjs
test/workbox-sw/static/sw.js

This uses the proxy stuff to make it possible to dynamically pull in workbox modules via importScripts and via the need to know about the `workbox` namespace and 'default' export name.
See what you think. I am slightly concerned that the list of modules is manually curated and not tested, so I will likely change the list to come from a auto-generated build step that will look for modules that have namespaces different to their module name and add only those to the mapping.
I also am concerned that any value will result in an attempted network request - this will likely just lead to some super unnecessary hits on storage that could be prevented. BUT for now I'll leave as is.

V3 sw proxy

---

.eslintrc.js
gulp-tasks/test-node.js
infra/testing/auto-stub-logger.mjs
package.json
packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-precaching/default.mjs
packages/workbox-precaching/index.mjs
packages/workbox-precaching/utils/printCleanupDetails.mjs
packages/workbox-precaching/utils/printInstallDetails.mjs
test/workbox-core/node/utils/test-logger.mjs
test/workbox-precaching/node/controllers/test-PrecacheController.mjs
test/workbox-precaching/node/controllers/test-default.mjs
test/workbox-precaching/node/utils/test-cleanRedirect.mjs
test/workbox-precaching/node/utils/test-printCleanupDetails.mjs
test/workbox-precaching/node/utils/test-printInstallDetails.mjs
test/workbox-precaching/node/utils/test-showWarningsIfNeeded.mjs
test/workbox-routing/node/test-Router.mjs

- Adds tests for the default export logic
- Fixes a few bugs
- Adds an auto-logger stub that basically silences a big chunk of the output from the library (I need to find a solution for the workbox-core welcome message that is clogging up tests)

Precaching coverage

---

infra/testing/auto-stub-logger.mjs
packages/workbox-core/utils/logger.mjs
packages/workbox-core/workboxCore.mjs
packages/workbox-routing/Router.mjs
test/workbox-core/node/utils/test-logger.mjs
test/workbox-core/static/logger.html

Once I started adding logs for the router (and I had some quirks with the precaching), I quickly wanted to print to the console without any 'workbox' branding because the logs were nested in a group that had the workbox label. I cheated and just used the console.
The down side of this is it went outside the logger filtering and it resulted in some hella messy logs in the test console.
This PR adds a set of methods to `logger.unprefixed.*` that match `logger.* / console.*` that will still go through the workbox filters but will exclude the workbox label.
Also changed up the logger stub to silence all logs in the tests from Workbox-core.
Fixes #930

Direct logs

---

packages/workbox-precaching/_default.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-precaching/utils/showWarningsIfNeeded.mjs
test/workbox-precaching/node/controllers/test-PrecacheController.mjs
test/workbox-precaching/node/controllers/test-default.mjs
test/workbox-precaching/node/test-precaching-module.mjs
test/workbox-precaching/node/utils/test-showWarningsIfNeeded.mjs

- This swaps out the hella long precaching warnig with a link to docs (This will need to be substituted for a d.g.c link but for now it gets the point across
- Also added the ability to surpess this warning in case developers who are revisioning assets that are revisioned want to shut it up. I doubt it'll get much use but I know I'd want it if I used this.
This is the last bit of precaching I want to touch. I'll add some integration tests for workbox routing and upgrading / changing service workers, but that'll be it apart from docs.

Precaching warning tweaks

---

packages/workbox-google-analytics/_default.mjs

Fixes issues where importing select exports from a public namespace would lead to larger webpack builds (since webpack won't tree-shake them).

Revert imports from _public

---

demos/functions/views/demo/workbox-cache-expiration.hbs
demos/functions/views/demo/workbox-cache-expiration/sw.hbs
demos/functions/views/demo/workbox-precaching/sw-1.hbs
demos/functions/views/demo/workbox-precaching/sw-2.hbs
demos/functions/views/demo/workbox-routing/sw.hbs
demos/functions/views/demo/workbox-runtime-caching.hbs
demos/functions/views/demo/workbox-runtime-caching/sw.hbs
packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-core/_private/fetchWrapper.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-precaching/utils/openInstallLogGroup.mjs
packages/workbox-runtime-caching/CacheFirst.mjs
packages/workbox-runtime-caching/CacheOnly.mjs
packages/workbox-runtime-caching/NetworkFirst.mjs
packages/workbox-runtime-caching/NetworkOnly.mjs
packages/workbox-runtime-caching/StaleWhileRevalidate.mjs
test/workbox-precaching/node/utils/test-openInstallLogGroup.mjs

I noticed that after updating the demos that logging from fetch and cache wrappers were very verbose in precaching so I took another stab at them.
- precaching and runtime caching modules will create groups that will "group" the relevant logs from fetch and cache wrappers under the appropriate request heading
- fetch and cache wrapper now print logs to debug. This means by default they won't be seen. This means developers / bug traces can include all of the fetch and cache wrapper info if needed.
- runtime caching has some more specific logs for each strategy that they didn't have before.

Logging changes

---

packages/workbox-cache-expiration/CacheExpirationPlugin.mjs
test/workbox-cache-expiration/node/test-CacheExpirationPlugin.mjs

If I've understood the logic for CacheExpirationPlugin the only time expireEntries is called is when there is no date or a cache entry is updated
This isn't such a bad problem for maxEntries, but for maxAgeSeconds it has the following negative side effects:
- If there is a date header but it can't be parsed, it'll be treated as fresh, but never expired.
- If the date header can be parsed, we'll mark the response as fresh or not, but we won't remove it from the cache because we never expire it (meaning Cache and iDB will grow).

Ensure expireEntries is called

---

packages/workbox-webpack-plugin/index.js

R: @philipwalton  @addyosmani @gauntface
Fixes #950 
I've tested this locally with an `nvm` installed version of `node` 4.x, which is the level we say we support in our `package.json`.
(As mentioned, this isn't a concern in the v3 codebase, as we're transpiling with `@babel/preset-env` against our `node` 4.x target.)

Ensure untranspiled node 4+ compat for the v2 webpack plugin

---

packages/workbox-core/models/messages/messages.mjs
packages/workbox-routing/_default.mjs
test/workbox-routing/node/test-default.mjs

In workbox-sw we have a Wrapper Router, all it does is manipulate input into a Route class for developers.
I've moved this into the Default export, it can just as easily live in the Router class it self if people think the API should be available in the class itself.

Adding the helper version of registerRoute

---

infra/testing/sw-env.js
packages/workbox-routing/NavigationRoute.mjs
packages/workbox-routing/_default.mjs
test/workbox-routing/node/test-default.mjs

R: @jeffposnick @addyosmani @philipwalton
Adds the workbox-sw style registerNavigationRoute() method.
Only thing to comment is that I had rejig code in the NavigationRoute to test the whitelist and blacklist and I had to alter caches.match to get around an issue in service worker mock library.

Nav route helper

---

gulp-tasks/docs.js
infra/templates/reference-docs/jsdoc/lang/en.yaml
infra/templates/reference-docs/jsdoc/lib/publishjob.js
infra/templates/reference-docs/jsdoc/publish.js
infra/templates/reference-docs/jsdoc/static/jsdoc.css
infra/templates/reference-docs/jsdoc/views/augments.hbs
infra/templates/reference-docs/jsdoc/views/classes-links.hbs
infra/templates/reference-docs/jsdoc/views/details-table-row.hbs
infra/templates/reference-docs/jsdoc/views/details-table.hbs
infra/templates/reference-docs/jsdoc/views/implements.hbs
infra/templates/reference-docs/jsdoc/views/index-all.hbs
infra/templates/reference-docs/jsdoc/views/index.hbs
infra/templates/reference-docs/jsdoc/views/layout.hbs
infra/templates/reference-docs/jsdoc/views/params.hbs
infra/templates/reference-docs/jsdoc/views/properties.hbs
infra/templates/reference-docs/jsdoc/views/see.hbs
infra/templates/reference-docs/jsdoc/views/signature.hbs
infra/templates/reference-docs/jsdoc/views/symbol-content.hbs
infra/templates/reference-docs/jsdoc/views/symbol-detail.hbs
infra/templates/reference-docs/jsdoc/views/symbol-header.hbs
infra/templates/reference-docs/jsdoc/views/symbol-index-section.hbs
infra/templates/reference-docs/jsdoc/views/symbol-index.hbs
infra/templates/reference-docs/jsdoc/views/symbol-labels.hbs
infra/templates/reference-docs/jsdoc/views/symbol-overview.hbs
infra/templates/reference-docs/jsdoc/views/toc-yaml.hbs
package-lock.json
package.json
packages/workbox-core/_private/DBWrapper.mjs

I noticed the docs on WebFundamentals are more "loose" with respect to showing functions or Classes that aren't assigned a module.
This theme is more inline with WebFundamentals, although it's ugly as hell.
I've added a `--pretty` option to make it possible to switch to jsdocs theme for reviews etc.

Adding a more accurate theme for web fundamentals

---

packages/workbox-cli/src/lib/questions/ask-extensions-to-cache.js
packages/workbox-core/_default.mjs
packages/workbox-core/index.mjs
packages/workbox-core/models/LogLevels.mjs
packages/workbox-precaching/_default.mjs
packages/workbox-precaching/_types.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-precaching/index.mjs
packages/workbox-precaching/models/PrecachedDetailsModel.mjs
test/all/node/test-exports.mjs

Precaching was exposing private docs - new theme exposed it.
Also tried namespace instead of module syntax and it actually reads a little better. Got the idea from firebase reference docs: https://firebase.google.com/docs/reference/js/

Switching to namespace and tidying precaching docs

---

packages/workbox-core/_private/fetchWrapper.mjs
packages/workbox-runtime-caching/CacheFirst.mjs
packages/workbox-runtime-caching/CacheOnly.mjs
packages/workbox-runtime-caching/NetworkFirst.mjs
packages/workbox-runtime-caching/NetworkOnly.mjs
packages/workbox-runtime-caching/StaleWhileRevalidate.mjs
packages/workbox-runtime-caching/_default.mjs
packages/workbox-runtime-caching/_types.mjs
packages/workbox-runtime-caching/index.mjs
packages/workbox-runtime-caching/plugins/cacheOkAndOpaquePlugin.mjs
test/workbox-runtime-caching/node/test-CacheFirst.mjs
test/workbox-runtime-caching/node/test-StaleWhileRevalidate.mjs
test/workbox-runtime-caching/node/test-cacheOkAndOpaquePlugin.mjs

Extend coverage for runtime-caching and sort out docs to namespace and document default exports.

Runtime-caching Docs + Coverage.

---

gulp-tasks/demos.js
gulp-tasks/utils/analyse-properties.js
gulp-tasks/utils/build-browser-bundle.js
gulp-tasks/utils/constants.js
gulp-tasks/utils/publish-helpers.js
infra/pr-bot/aggregate-size-plugin.js
infra/testing/test-server.js
packages/workbox-background-sync/package.json
packages/workbox-build/src/entry-points/generate-sw.js
packages/workbox-build/src/lib/copy-workbox-libraries.js
packages/workbox-cache-expiration/package.json
packages/workbox-core/package.json
packages/workbox-google-analytics/package.json
packages/workbox-precaching/package.json
packages/workbox-routing/package.json
packages/workbox-runtime-caching/package.json
packages/workbox-sw/package.json
test/all/node/test-package.mjs

Fixes #911
While moving from `browser` to `main`, I've also taken the opportunity to remove the `browser/` subdirectory from `build/`. I don't think there are any packages that have both browser and non-browser builds, so it doesn't seem necessary.

pkg.browser => pkg.main, and update the build path.

---

gulp-tasks/utils/cdn-helper.js

Without this, a failure looks like:
```sh
[15:41:34] Starting 'publish-cdn:temp-v3'...
(node:12502) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, access '/Users/jeffy/git/workbox/workbox-9d39634504ad.json'
(node:12502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Workbox Log]: Error: ENOENT: no such file or directory, open '/Users/jeffy/git/workbox/workbox-9d39634504ad.json'
[15:41:34] 'publish-cdn:temp-v3' errored after 13 ms
```
The custom `ERROR_SERVICE_ACCOUNT` message never gets logged since the exception isn't thrown synchronously.

Use accessSync to ensure ERROR_SERVICE_ACCOUNT is logged

---

packages/workbox-sw/controllers/WorkboxSW.mjs
packages/workbox-sw/index.mjs

Just moving docs over to a namespace and exposing the `loadModule` function just to account for scenarios where a developer wants to pre-emptively load a module that isn't in the main flow.

Moving to namespace and exposing loadModule

---

packages/workbox-webpack-plugin/src/index.js
packages/workbox-webpack-plugin/src/lib/generate-manifest-with-webpack.js
packages/workbox-webpack-plugin/src/lib/generate-or-copy-sw.js
packages/workbox-webpack-plugin/src/lib/get-manifest-entries-with-webpack.js
packages/workbox-webpack-plugin/src/lib/utils/read-file.js
packages/workbox-webpack-plugin/src/lib/utils/resolve-webpack-url.js
packages/workbox-webpack-plugin/src/lib/utils/webpack-asset.js

R: @jeffposnick @addyosmani @goldhand 
My understanding is that the Webpack plugin exports *just* the `WorkboxWebpackPlugin`. This PR will expose only this class and alters the docs to call out that the class the only thing exported.

webpack-docs

---

packages/workbox-build/src/lib/runtime-caching-converter.js
packages/workbox-core/models/messages/messages.mjs
packages/workbox-routing/RegExpRoute.mjs
packages/workbox-routing/_default.mjs
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-build/node/lib/runtime-caching-converter.js
test/workbox-routing/node/test-default.mjs

Support for registerRoute(<string>)

---

gulp-tasks/utils/get-packages-of-type.js
gulp-tasks/utils/publish-helpers.js

I could take a different approach to this, but using the `packageType` in `package.json` to determine which packages got picked up for CDN publishing made sense to me.

Check packageType in package.json to figure out whether we should publish

---

infra/testing/env-it.js
test/workbox-webpack-plugin/node/index.js

In the course of looking into some of the webpack issues, I realized that the existing webpack plugin test wasn't failing when it should be.
The underlying issue was that the `env-it` module didn't pass through the `done` callback to the wrapped test case.
I've fixed that bug in `env-it`, and also cleaned up in the webpack plugin test so that it's legitimately working with the new v3 service worker format.
I've also modified the test so that it includes an asset with a `[chunkhash]`, in preparation for some further work.

Fix env-it to pass through done(), and fix up webpack plugin test

---

packages/workbox-core/_private/cacheWrapper.mjs

@jeffposnick is there anywhere else you think it would be helpful to log when we are working with opaque responses and drop them?

Adding log for opaque responses

---

infra/testing/validator/compare-manifest-entries.js
package-lock.json
package.json
packages/workbox-webpack-plugin/src/lib/get-manifest-entries-with-webpack.js
test/workbox-webpack-plugin/node/index.js

R: @goldhand @addyosmani @gauntface
Fixes #939, perhaps somewhat naively.
If a URL contains either a `hash`/`fullHash`/`renderedHash` that's associated with the Webpack build, then I *think* it's safe to assume that it is being versioned by webpack, and we don't need to maintain a separate revision field for it.
There's a very small chance of strings that are not actually hashes being present in both the filename and being used internally by webpack, but I don't think that's worth worrying about. This approach seems less likely to lead to false positives than what we were doing with `sw-precache`, where a [basic RegExp](https://github.com/GoogleChromeLabs/sw-precache#dontcachebusturlsmatching-regex) was used to detect hashes and omit revisioning info.
This isn't ready to be merged yet, as …

Exclude revision info when the URL includes a known hash.

---

infra/testing/sw-env-mocks/Headers.js
infra/testing/sw-env-mocks/Response.js
infra/testing/sw-env.js
packages/workbox-cache-expiration/CacheExpirationPlugin.mjs
test/workbox-precaching/node/utils/test-cleanRedirect.mjs

This brings the `Response` mock into closer compliance to the spec than what `service-worker-mocks` offers.
It also fixes some unit tests that relied on the old, incorrectly mocked behavior.
Once this is merged I can get rid of some [hacks](https://github.com/GoogleChrome/workbox/pull/1057#pullrequestreview-76995397) in the `workbox-cacheable-response` tests.

More compliant Response mock

---

packages/workbox-sw/src/lib/router.js

Fixes #1011 
Using `warn()` vs. a lower log level is up for negotiation.
I was planning on writing a test to make sure that `logHelper.warn()` was getting called, but then I realized we had issues in v2 with stubbing out code that is internal to the bundle. I can't find any examples of stubbing out `logHelper` methods, but if someone knows of some prior art, I'll copy it and add in some tests.

v2: Warn on usage of Express-style wildcard characters

---

infra/pr-bot/aggregate-size-plugin.js
packages/workbox-cacheable-response/CacheableResponse.mjs
packages/workbox-cacheable-response/CacheableResponsePlugin.mjs
packages/workbox-cacheable-response/_public.mjs
packages/workbox-cacheable-response/_version.mjs
packages/workbox-cacheable-response/browser.mjs
packages/workbox-cacheable-response/index.mjs
packages/workbox-cacheable-response/package.json
packages/workbox-core/models/messages/messages.mjs
packages/workbox-strategies/package.json
packages/workbox-strategies/utils/pluginBuilder.mjs
test/workbox-build/node/lib/runtime-caching-converter.js
test/workbox-cacheable-response/node/CacheableResponse.mjs
test/workbox-cacheable-response/node/CacheableResponsePlugin.mjs
test/workbox-cacheable-response/node/index.mjs

This re-adds `workbox-cacheable-response` for v3.
An open question I had is whether [`cacheOkAndOpaquePlugin.mjs`](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-strategies/plugins/cacheOkAndOpaquePlugin.mjs) should stick around, or whether it should be replaced by an instance of `CacheableResponsePlugin`.

v3: workbox-cacheable-response

---

demos/functions/cdn-details.json
lerna.json
packages/workbox-background-sync/_version.mjs
packages/workbox-background-sync/package.json
packages/workbox-broadcast-cache-update/_version.mjs
packages/workbox-broadcast-cache-update/package.json
packages/workbox-build/package.json
packages/workbox-build/src/cdn-details.json
packages/workbox-cache-expiration/_version.mjs
packages/workbox-cache-expiration/package.json
packages/workbox-cacheable-response/_version.mjs
packages/workbox-cacheable-response/package.json
packages/workbox-cli/package.json
packages/workbox-core/_version.mjs
packages/workbox-core/package.json
packages/workbox-google-analytics/_version.mjs
packages/workbox-google-analytics/package.json
packages/workbox-precaching/_version.mjs
packages/workbox-precaching/package.json
packages/workbox-routing/_version.mjs
packages/workbox-routing/package.json
packages/workbox-strategies/_version.mjs
packages/workbox-strategies/package.json
packages/workbox-sw/_version.mjs
packages/workbox-sw/package.json
packages/workbox-webpack-plugin/package.json

We haven't actually been publishing the v3 stuff to git or NPM, just to the CDN.
I'd like to reset the version numbers so the release on NPM and docs etc are 3.0.0-alpha.0 or .1.

Reset for v3 alpha

---

packages/workbox-build/src/entry-points/inject-manifest.js
packages/workbox-build/src/entry-points/options/base-schema.js
packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/entry-points/options/defaults.js
packages/workbox-build/src/entry-points/options/generate-sw-schema.js
packages/workbox-build/src/lib/errors.js

Fixes #1053
In the course of addressing the issue I ended up refactoring how defaults are passed through to `joi`, keeping them in an external module instead of inline. That made it easier to tell whether the effective option that we were dealing with was overridden by the developer, or was the default value, which in turn made it possible to customize the error message accurately.

Refactor workbox-build defaults, and update the injection-point-not-found message

---

packages/workbox-background-sync/models/StorableRequest.mjs
packages/workbox-webpack-plugin/src/lib/utils/read-file.js

Globals were being documented when they shouldn't - will add a link check for this.

doc-global-removal

---

.travis.yml
gulp-tasks/docs.js
gulp-tasks/test-node.js
jsdoc.conf
package-lock.json
test/all/node/test-jsdocs.mjs

This will fail the test until #1080 is merged, then we can re-run and check the tests pass.
Checks for:
- No globals
- No module.exports (Something that is showing up in the WebFundamentals build for v3.0.0-alpha.1) at the moment.

Adding JSDocs checks

---

packages/workbox-build/src/entry-points/options/defaults.js
packages/workbox-build/src/entry-points/options/generate-sw-string-schema.js
packages/workbox-webpack-plugin/src/index.js
packages/workbox-webpack-plugin/src/lib/generate-or-copy-sw.js
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-webpack-plugin/node/index.js

R: @goldhand @addyosmani @gauntface
CC: @anilanar 
Fixes #934 
As an initial implementation, it should provide flexibility to handle both webpack-specific precaching as well as take advantage of `runtimeCaching`, `templatedUrls`, and the other options exposed via `workbox-build`.
(This might not be the 100% final interface, as folks who start using the webpack plugin might have feedback about certain options that feel awkward when used in this context.)

Pass through all webpack config options to generateSWString()

---

packages/workbox-build/src/templates/sw-template.js
packages/workbox-cli/src/lib/help-text.js
packages/workbox-cli/src/lib/run-wizard.js
packages/workbox-precaching/utils/showWarningsIfNeeded.mjs
packages/workbox-routing/RegExpRoute.mjs
packages/workbox-strategies/NetworkFirst.mjs
packages/workbox-strategies/StaleWhileRevalidate.mjs

This updates short links to d.g.c where appropriate., Plugins is still missing a doc so will point to drive until we actually write up the content and post.
There is also a short link pointing to a 404 URL at the moment but it will be valid once: https://github.com/google/WebFundamentals/pull/5397 lands.

Updating references to point to new docs pages

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/lib/errors.js
packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-build/node/lib/runtime-caching-converter.js

Revamp runtimeCaching.options to account for new plugins usage.

---

packages/workbox-cli/src/lib/questions/ask-questions.js
packages/workbox-cli/src/lib/questions/ask-sw-dest.js

Better swDest default value when using workbox-cli wizard

---

infra/testing/sw-env-mocks/Blob.js
packages/workbox-core/models/messages/messages.mjs
packages/workbox-range-requests/Plugin.mjs
packages/workbox-range-requests/_public.mjs
packages/workbox-range-requests/_version.mjs
packages/workbox-range-requests/browser.mjs
packages/workbox-range-requests/createPartialResponse.mjs
packages/workbox-range-requests/index.mjs
packages/workbox-range-requests/package.json
packages/workbox-range-requests/utils/calculateEffectiveBoundaries.mjs
packages/workbox-range-requests/utils/parseRangeHeader.mjs
packages/workbox-sw/controllers/WorkboxSW.mjs
test/workbox-range-requests/node/Plugin.mjs
test/workbox-range-requests/node/createPartialResponse.mjs
test/workbox-range-requests/node/exports.mjs
test/workbox-range-requests/node/utils/calculateEffectiveBoundaries.mjs
test/workbox-range-requests/node/utils/parseRangeHeader.mjs

Fairly straightforward port of the `workbox-range-requests` code from v2, with some test changes to accommodate the mocked interfaces, and some additional error messages.
I updated the `workbox-sw` mapping, but I might be missing some other "meta" things that need to be changed when we add a new library.

v3: workbox-range-requests module

---

packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-precaching/utils/printInstallDetails.mjs
test/workbox-precaching/node/utils/test-printInstallDetails.mjs

R: @jeffposnick @addyosmani @beatrizdemiguelperez 
Fixes #1114
This should fix the issue of the grouping getting out of sync in precaching (I looked through the rest of the code base and it shouldn't be an issue.).

Fixing the log grouping

---

test/workbox-precaching/integration/precache-and-update.js

This just checks IDB has what is expected in precaching.

Check idb entries in integration test

---

test/workbox-strategies/integration/test-cacheOnly.js
test/workbox-strategies/static/cache-only/index.html
test/workbox-strategies/static/cache-only/sw.js

Just a simple test for CacheOnly.

Adding a CacheOnly integration test

---

test/workbox-routing/integration/navigation-route.js
test/workbox-routing/integration/routing-regex.js
test/workbox-routing/static/routing-navigation/index.html
test/workbox-routing/static/routing-navigation/sw.js

Adds an integration test for NavigationRoute.

Adding navigation route test

---

packages/workbox-build/src/entry-points/generate-sw.js
packages/workbox-build/src/entry-points/options/defaults.js
packages/workbox-build/src/entry-points/options/generate-sw-schema.js
packages/workbox-build/src/lib/copy-workbox-libraries.js
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-build/node/entry-points/get-manifest.js
test/workbox-build/node/entry-points/inject-manifest.js

R: @gauntface
This is part of the work for #933.
I wanted to break it into multiple PRs, which this one just covering the removal of `importWorkboxFromCDN` and addition of `importWorkboxFrom`.
I'll put together a separate PR to support `importWorkboxFrom` in the `workbox-webpack-plugin`, since that requires introducing `joi` as a dependency in the webpack package, and will end up being a fair chunk of independent work to modify how we deal with options there.

Use importWorkboxFrom instead of importWorkboxFromCDN

---

packages/workbox-precaching/_default.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
test/workbox-precaching/node/controllers/test-PrecacheController.mjs
test/workbox-precaching/node/controllers/test-default.mjs
test/workbox-precaching/node/test-precaching-module.mjs

This adds plugins to precaching so a developer could add in the broadcast cache update behavior if they want it.
```javascript
workbox.precaching.addPlugins([
new workbox.broadcastUpdate.Plugin({ channelName: 'example-channel' })
]);
```

Adds ability to add plugins to precaching lifecycle

---

package-lock.json
packages/workbox-precaching/models/PrecachedDetailsModel.mjs
test/workbox-precaching/node/models/test-PrecachedDetailsModel.mjs

More changes to ensure idb works.
In IndexedDB version 1, we used two object stores 'workbox-precaching' and 'precaching-details-models'. In IndexedDB version 2 we only use 'precaching-details-models'. To ensure we are upgrading to a clean working state, this PR removes any old object stores and creates a new one.

Precaching idb fix

---

packages/workbox-build/src/entry-points/options/defaults.js
packages/workbox-webpack-plugin/src/index.js
packages/workbox-webpack-plugin/src/lib/generate-or-copy-sw.js
packages/workbox-webpack-plugin/src/lib/get-manifest-entries-with-webpack.js
test/workbox-build/node/entry-points/options/validate.js
test/workbox-webpack-plugin/node/index.js

R: @prateekbh @gauntface @goldhand 
This is another follow-up to #933, but doesn't close it yet, as there's still a TODO: to implement `importWorkboxFrom: 'local'`. This PR was large enough already so I wanted to break it up further.
I included a refactoring of a decent chunk of `get-manifest-entries-with-webpack.js` in this PR, because I discovered that it wasn't properly filtering out all assets based on the `chunks`/`excludeChunks` whitelist/blacklist. That became an issue since `importWorkboxFrom: <chunkname>` is supposed to implicitly add `<chunkname>` to the blacklist.
This also includes a few more relevant tests, both to ensure that `importWorkboxFrom: <chunkname>` works as expected, as well as ensure that whitelist/blacklist behavior works in general.
Finally, I discovered that …

Support for importWorkboxFrom: <chunkname> and associated fixes

---

packages/workbox-build/src/entry-points/options/generate-sw-string-schema.js
packages/workbox-webpack-plugin/src/generate-sw.js
packages/workbox-webpack-plugin/src/inject-manifest.js
packages/workbox-webpack-plugin/src/lib/get-workbox-sw-imports.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

R: @goldhand @addyosmani @gauntface
With this PR, I think we have enough to fix #933. (There are still docs updates that are needed to reflect all the new options, tracked in https://github.com/google/WebFundamentals/issues/5567).
This adds support for `importWorkboxFrom: 'local'` in the `GenerateSW` mode of the webpack plugin.
(As with the underlying `workbox-build` library, `'local'` mode isn't supported in the inject manifest use case.)

Webpack import workbox from local

---

package-lock.json
package.json
packages/workbox-webpack-plugin/package.json
packages/workbox-webpack-plugin/src/generate-sw.js
packages/workbox-webpack-plugin/src/inject-manifest.js
packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js
packages/workbox-webpack-plugin/src/lib/sanitize-config.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

CC: @anilanar
Fixes #935
As mentioned in the comments/the original issue, this takes advantage of a pattern native to webpack and used in other plugins (like UglifyJS) for filtering the precache manifest of webpack assets based on an object with `test`, `include`, and `exclude` properties.
It defaults to using RegExps for `exclude` that will match `.map` files and `manifest*.js(on)` files. While webpack gives developers flexibility to name their sourcemaps and asset manifest files whatever they'd like, those seem like the most common naming schemes (and they can be overridden).
The drawback of this PR is that it makes filtering more complicated: prior to this PR we implemented filtering based on chunk name white/blacklists, and now this introduces …

Add in asset filename filtering via {test, include, exclude}

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/lib/errors.js
packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-build/node/lib/runtime-caching-converter.js

Fixes #1096, which also contains an explanation of what's changing and why.

Revamp the runtime caching option conversion.

---

packages/workbox-background-sync/Queue.mjs
packages/workbox-core/models/messages/messages.mjs
test/workbox-background-sync/node/lib/test-Queue.mjs

R:  @philipwalton 
CC: @jeffposnick @addyosmani @gauntface
Fixes #1145
Currently, on any failures in queue replay it results in re-registering of sync queue tag.
This causes infinite loop in case of `offline` from devtools + IIRC will not re-play the failed requests as this will re-register the same tag and also resolve the promise inside `event.waitUntil` of `sync` event. Hence telling the browser that we've successfully done everything related to this tag.
Instead to indicate any failure it is require that the promise passed to `event.waitUntil` should be rejected. ref: https://github.com/WICG/BackgroundSync/blob/master/explainer.md#the-api
> The promise passed to waitUntil is a signal to the user agent that the sync event is ongoing and that it should keep the service worker alive if …

Throwing error instead of re registering sync on failure

---

infra/testing/test-server.js
package-lock.json
test/workbox-cache-expiration/integration/expiration-plugin.js
test/workbox-cache-expiration/static/expiration-plugin/example-1.txt
test/workbox-cache-expiration/static/expiration-plugin/example-2.txt
test/workbox-cache-expiration/static/expiration-plugin/index.html
test/workbox-cache-expiration/static/expiration-plugin/sw-max-age-seconds.js
test/workbox-cache-expiration/static/expiration-plugin/sw-max-entries.js

This adds integration tests to the cache expiration plugin - this should guarantee everything stays working.
Major downside is I couldn't thing of a sure fire way to test the timed expiration. The sinon fake timers would need to be setup in the service worker env, which *could* get terminated and brought back up between commands, so for now I just wait a second before testing the expiration flow.

Expiration integration

---

packages/workbox-webpack-plugin/src/lib/get-workbox-sw-imports.js
test/workbox-webpack-plugin/node/generate-sw.js

Fixes #1172 
This was due to a missing `()` around an `||` operator.

Properly deal with webpack's publicPath + importWorkboxFrom: 'local'

---

packages/workbox-build/src/lib/copy-workbox-libraries.js
test/workbox-build/node/lib/copy-workbox-libraries.js

Don't copy the same workbox-sw.js(.map) files twice

---

gulp-tasks/utils/publish-helpers.js

This *might* deal with #1165, though we should probably leave that bug open until we can confirm during the next release.
Regardless of whether it fixes it or not, it seems like a cleaner approach to creating our own Promise wrapper.

Use the native archiver.finalize() promise

---

packages/workbox-google-analytics/_default.mjs

Fixes #1186 
These should be functionally equivalent, but by explicitly marking `getTextFromBlob()` as being an `async` function, the `asyncToGenerator` transpilation => UglifyJS minification pipeline now results in valid final JS code.

Tweak async/await usage to avoid a bug in the final prod bundle.

---

gulp-tasks/test-node.js
packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs
test/workbox-cache-expiration/node/test-CacheExpiration.mjs
test/workbox-cache-expiration/node/test-CacheTimestampsModel.mjs

Previously I was using a single database name with multiple store names for the cache expiration timestamps,. This doesn't work / make sense given that you need to know the store names up front which for multiple instances of the class - will not be the case.
This change moves to using a name for the database and store name to ensure uniqueness.
Fixes #1175

Switching to a db name instead of just a store name

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js

CC: @mischnic
Fixes #1215
The missing `new` was an oversight during the migration to using the `plugins: []` property for configuring all strategy classes.

Call new on the corresponding Plugin class.

---

infra/testing/test-server.js
packages/workbox-broadcast-cache-update/Plugin.mjs
packages/workbox-broadcast-cache-update/broadcastUpdate.mjs
test/workbox-broadcast-cache-update/integration/broadcast-cache-update-plugin.js
test/workbox-broadcast-cache-update/node/test-Plugin.mjs
test/workbox-broadcast-cache-update/static/index.html
test/workbox-broadcast-cache-update/static/sw.js

Fixes #1191 
In the course of writing this test I found two problems with the implementation, which this PR also fixes:
- The v3 `cacheDidUpdate` lifecycle callback no longer sets the `url` property on the parameter. It still sets the `request` property, and you can get the `url` from that, so I just switched over to getting it from there.
- The move from named properties for parameters to positional parameters led to an issue where `notifyIfUpdated()` was being called with the `url` and `cacheName` parameters transposed.
(I guess that's why we write integration tests!)

BroadcastCacheUpdate.Plugin integration test

---

test/workbox-routing/integration/routing-basic.js
test/workbox-routing/static/routing-basic/index.html
test/workbox-routing/static/routing-basic/sw.js

Fixes #1195
I think this should cover what was missing: registering a `Route` object directly, and using strings to implicitly create and register `Route`s.

Basic Route integration tests.

---

packages/workbox-cli/src/app.js
packages/workbox-cli/src/bin.js
packages/workbox-cli/src/lib/errors.js
test/workbox-broadcast-cache-update/integration/broadcast-cache-update-plugin.js
test/workbox-cli/node/app.js

Fixes #1238
The parameters got messed up when I started passed in `params.flags` from `bin.js` to `app.js`, so I took a step back and refactored how those are passed through.
I'm happier with this approach as it keeps the CLI position parameters separate from the CLI flags.

Refactor the way CLI parameters are processed by app.js.

---

infra/testing/test-server.js
test/workbox-strategies/integration/test-networkFirst.js
test/workbox-strategies/integration/test-networkOnly.js
test/workbox-strategies/integration/test-staleWhileRevalidate.js
test/workbox-strategies/static/network-first/index.html
test/workbox-strategies/static/network-first/sw.js
test/workbox-strategies/static/network-only/index.html
test/workbox-strategies/static/network-only/sw.js
test/workbox-strategies/static/stale-while-revalidate/index.html
test/workbox-strategies/static/stale-while-revalidate/sw.js

Fixes #1196
Integration tests for networkonly networkfirst and stalewhilerevalidate.

Adding integration tests for remaining strategies

---

packages/workbox-cli/src/lib/constants.js
packages/workbox-cli/src/lib/questions/ask-extensions-to-cache.js
test/workbox-cli/node/lib/questions/ask-extensions-to-cache.js

Ignore '.map' when suggesting extensions to precache.

---

packages/workbox-webpack-plugin/src/lib/get-workbox-sw-imports.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes https://github.com/GoogleChrome/workbox/issues/1261
This fix is intended for the following two configurations:
- Webpack plugin InjectManifest is used
- Webpack compiler is configured with `output.publicPath`
- `importWorkboxFrom` plugin option is set to a string, which points to a valid Webpack chunk name.
The fix is to ensure the generated `importScripts` statement will prefix the Webpack workbox chunk with `output.publicPath`

Make workbox sw chunk prefix with public path

---

packages/workbox-build/src/entry-points/options/base-schema.js
packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/entry-points/options/reg-exp-object.js

Fixes #1262 
This leads to error messages like:
```
child "dontCacheBustUrlsMatching" fails because [the value must be a RegExp]
```

Improve the RegExp object validation failure message

---

test/workbox-broadcast-cache-update/integration/broadcast-cache-update-plugin.js
test/workbox-broadcast-cache-update/static/sw.js

R: @gauntface
Fixes #1272 
There were a couple of tests in v2 that relied on the old `RequestWrapper'`s `waitOnCache` config option to ensure that the async cache writes were done before moving on to the next step of the test. Since that's no longer a thing in v3, doing two sequential `fetch()`es might be a bit flakey.

Remove some BCU integration flakiness by pre-populating the cache in the SW

---

packages/workbox-webpack-plugin/src/generate-sw.js
packages/workbox-webpack-plugin/src/inject-manifest.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes https://github.com/GoogleChrome/workbox/issues/1267
When in Webpack development mode where, regardless of using Webpack dev server, if Webpack watches the source change and re-compiles accordingly, the bug manifests itself as:
- precache-mainfest.js & workbox-sw path will be included multiple times, within `importScripts` from the generated service worker script.
- It appears in both `InjectManifest` and `GenerateSW`
By `git checkout` the fixes on the latest `v3`, and run it against the tests.

Prevent multiple precache manifest in webpack development

---

packages/workbox-background-sync/Queue.mjs
test/workbox-background-sync/node/test-Queue.mjs

Adds a check for tag name before replaying the requests in background sync queue.

adding bg-sync tag name check

---

packages/workbox-background-sync/src/lib/background-sync-queue.js
packages/workbox-background-sync/src/lib/broadcast-manager.js
packages/workbox-background-sync/test/browser/broadcast-manager.js
packages/workbox-broadcast-cache-update/src/lib/broadcast-cache-update.js
packages/workbox-broadcast-cache-update/src/lib/broadcast-update.js
packages/workbox-broadcast-cache-update/test/sw/broadcast-cache-update.js
packages/workbox-broadcast-cache-update/test/sw/broadcast-update.js

R: @gauntface @addyosmani 
Needed for Safari compatibility.
Checking for `'BroadcastChannel' in self` and effectively no-op'ing if it wasn't defined seems preferable to doing something more forceful, like throwing an error.
I'm wrapping the tests that assume `BroadcastChannel` in a similar conditional, but if there's a preferred way of conditionally skipping them, let me know.

Gracefully no-op when BroadcastChannel doesn't exist

---

packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/lib/runtime-caching-converter.js

CC: @mischnic
Fixes #1289
This is just normalizing the `runtimeCaching` option key to match the namespace that's exposed by `workbox-sw`.
~~I'll make a corresponding change to the docs.~~ The docs have the correct value already.

Consistently use broadcastUpdate instead of broadcastCacheUpdate

---

infra/testing/sw-env-mocks/Request.js
packages/workbox-precaching/models/PrecacheEntry.mjs
test/workbox-background-sync/node/test-Queue.mjs
test/workbox-precaching/node/controllers/test-PrecacheController.mjs

CC: @mnquintana
Fixes #1288
Rather than passing in `{credentials: 'same-origin'}` when calling `fetch()`, it seemed a bit more self-contained to explicitly set the `credentials` property on the underlying `Request` object that the precaching code uses.

Set credentials: 'same-origin' on the precaching requests.

---

infra/testing/sw-env.js
packages/workbox-core/_private/logger.mjs

Fixes #1296
On Safari, don't log the `Workbox` prefix in logs as it silences the rest of the arguments. I checked the code and we only ever use a single string in group titles, so it's only the prefix that is the issue.

Safari groups

---

packages/workbox-precaching/_default.mjs
test/workbox-precaching/node/controllers/test-default.mjs

This is the last 1/3 of #1188 
If the browser doesn't have a cache match for a URL that should have been precached, this will cause it to go to the network instead of returning an error.

Fallback to fetch() if the precached response is missing.

---

packages/workbox-background-sync/Queue.mjs
packages/workbox-background-sync/models/StorableRequest.mjs
packages/workbox-google-analytics/_default.mjs
test/workbox-background-sync/node/lib/test-StorableRequest.mjs
test/workbox-background-sync/node/test-Queue.mjs
test/workbox-google-analytics/node/test-index.mjs

Fixes #1309 
This PR fixes the error in #1309, which was resulting from `workbox-google-analytics` setting the replayed request headers as the string ` '[["Content-Type", "text/plain"]]'` instead of the object.
This likely means none of the replays were working, something that ideally should have been caught by an integration test. I'll put together another PR to make sure an integration test exists that ensures the entire process works. (Note, the node tests didn't catch this because we use header mock that didn't error here when they should have. Not sure if anything should be done about that though.)
In the process of manually testing it, I noticed a few other issues that I fixed as well.
- Failed `workbox-background-sync` requests that were …

Analytics fixes

---

packages/workbox-core/_default.mjs
packages/workbox-core/_private/assert.mjs
packages/workbox-core/_private/checkSWFileCacheHeaders.mjs

Fixes #620
Adds a basic test for cache-control header.

Log warning for bad cache control

---

packages/workbox-build/src/entry-points/generate-sw.js
packages/workbox-build/src/entry-points/options/generate-sw-string-schema.js
packages/workbox-build/src/lib/populate-sw-template.js
packages/workbox-build/src/lib/write-sw-using-default-template.js
packages/workbox-build/src/templates/sw-template.js
packages/workbox-webpack-plugin/src/generate-sw.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-build/node/lib/populate-sw-template.js
test/workbox-webpack-plugin/node/generate-sw.js

CC: @beatrizdemiguelperez 
Fixes #1324 
Should hopefully be a clean fix to the issue.

Add a new workboxSWImport option to the template.

---

packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/lib/runtime-caching-converter.js

Fixes #1334
With additional tests as well.

Fix for runtimeCaching plugin config conversion

---

packages/workbox-strategies/CacheFirst.mjs
packages/workbox-strategies/NetworkFirst.mjs
packages/workbox-strategies/NetworkOnly.mjs
packages/workbox-strategies/StaleWhileRevalidate.mjs
test/workbox-strategies/node/test-CacheFirst.mjs
test/workbox-strategies/node/test-NetworkFirst.mjs
test/workbox-strategies/node/test-NetworkOnly.mjs
test/workbox-strategies/node/test-StaleWhileRevalidate.mjs

This is related to #1131.
I don't know if we want to mark it as fixed once this is merged—that issue tracks docs, and while this PR adds the code that's required, along with JSDocs, I guess we could still put together a standalone guide on d.g.c.

Adds support for changing the options used when calling fetch()

---

infra/testing/activate-and-control.js
infra/testing/activate-sw.js
packages/workbox-precaching/_default.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-precaching/models/PrecachedDetailsModel.mjs
test/workbox-background-sync/integration/test-bg-sync.js
test/workbox-broadcast-cache-update/integration/broadcast-cache-update-plugin.js
test/workbox-cache-expiration/integration/expiration-plugin.js
test/workbox-cacheable-response/integration/test-cacheable-response-plugin.js
test/workbox-core/integration/test-core.js
test/workbox-google-analytics/integration/basic-example.js
test/workbox-precaching/integration/precache-and-update.js
test/workbox-precaching/node/controllers/test-PrecacheController.mjs
test/workbox-precaching/node/controllers/test-default.mjs
test/workbox-precaching/node/models/test-PrecachedDetailsModel.mjs
test/workbox-precaching/static/precache.html
test/workbox-range-requests/integration/range-requests-plugin.js
test/workbox-routing/integration/navigation-route.js
test/workbox-routing/integration/routing-basic.js
test/workbox-routing/integration/routing-regex.js
test/workbox-strategies/integration/test-cacheFirst.js
test/workbox-strategies/integration/test-cacheOnly.js
test/workbox-strategies/integration/test-networkFirst.js
test/workbox-strategies/integration/test-networkOnly.js
test/workbox-strategies/integration/test-staleWhileRevalidate.js

Fixes #1316
Precaching first occurs into a cache with `-temp` appended to the end and during the activate step I copy the requests over to the originally intended cache.
For the most part this seems like a minor and safe change. I extended the test that installs and activates two sets of assets to ensure new expectations are being met, there was a bug in the cache API where keys weren't updated and the integration test had a weird issue with Firefox where multiple `activate` events seem to enter into a race condition and we can't rely on the cache cleanup being done by the time the client is claimed.
Let me know what you thinkg

Precaching temp

---

packages/workbox-precaching/models/PrecachedDetailsModel.mjs
test/workbox-precaching/integration/precache-and-update.js
test/workbox-precaching/node/models/test-PrecachedDetailsModel.mjs
test/workbox-precaching/utils/getPrecachedIDBData.js

Using cache name as idb name for precaching

---

packages/workbox-build/src/_types.js
packages/workbox-build/src/lib/filter-files.js

Docs were broken on Web Fundamentals due to a clash of syntax (WF expects `{{}}` to be an include but our docs was using it for an object.)

Doc repair for wf

---

packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-core/models/messages/messages.mjs

Somewhat addresses: #1368
This will throw with a meaningful error if we try to cache a non-existant response, BUT I think the error in #1368 is actually an issue with precaching going from temp -> final cache but I'm not 100%.

Cache put error

---

packages/workbox-precaching/controllers/PrecacheController.mjs
test/workbox-precaching/integration/precache-and-update.js
test/workbox-precaching/node/controllers/test-PrecacheController.mjs

Fixes #1368
Instead of deleting the temporary cache - empty it during install. This avoids any possible condition where the temp cache is deleted even though we want it to be used *after* deletion.

Fixing temporary cache deletion issue

---

packages/workbox-webpack-plugin/src/generate-sw.js
packages/workbox-webpack-plugin/src/inject-manifest.js
packages/workbox-webpack-plugin/src/lib/relative-to-output-path.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

CC: @freezy
At least one of the two issues reported in https://github.com/GoogleChrome/workbox/issues/1367 are due to webpack hanging when an absolute Windows path is used as a new asset filename. This PR should address that scenario by translating absolute paths into paths that are relative to the output directory.

Explicitly support absolute swDest paths

---

packages/workbox-webpack-plugin/src/generate-sw.js
packages/workbox-webpack-plugin/src/inject-manifest.js
packages/workbox-webpack-plugin/src/lib/warn-about-config.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes #1380
Happy to iterate on the warning language.
This PR also includes updates to the existing test suite to ensure that warnings were not previously being set when they were not expected.

Set webpack's compilation.warnings when glob-related options are used

---

package-lock.json
packages/workbox-precaching/_default.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
test/workbox-precaching/node/controllers/test-PrecacheController.mjs
test/workbox-precaching/node/controllers/test-default.mjs

Fixes #1376
This uses plugins for install and activate events. This may cause some confusion between temp vs actual cache, but checking the cache name should allow for figuring out where the cache put is.

Precaching plugins for active and install events

---

packages/workbox-strategies/NetworkFirst.mjs
test/workbox-strategies/node/test-NetworkFirst.mjs

R: @jeffposnick @beatrizdemiguelperez 
Fixes #1386 
I noodled on a few approaches to fix this and I'm not 100% sure this is the best, but at least we can still cache regardless of timeout triggering or not and regardless of whether we can waitUntil or not.

Use waitUntil only when it's available.

---

packages/workbox-build/src/index.js

All workbox-build docs currently hang off of workbox-build module in jsdocs, but that module was never defined which meant the docs have just been lost.
This adds the module to jsdocs but the actual document seems pretty wrong.

Make workbox-build exist in jsdoc

---

packages/workbox-strategies/CacheFirst.mjs
packages/workbox-strategies/CacheOnly.mjs
packages/workbox-strategies/NetworkFirst.mjs
packages/workbox-strategies/NetworkOnly.mjs
packages/workbox-strategies/StaleWhileRevalidate.mjs
packages/workbox-strategies/utils/messages.mjs
test/workbox-strategies/node/test-CacheFirst.mjs
test/workbox-strategies/node/test-CacheOnly.mjs
test/workbox-strategies/node/test-NetworkFirst.mjs
test/workbox-strategies/node/test-NetworkOnly.mjs
test/workbox-strategies/node/test-StaleWhileRevalidate.mjs

R: @gauntface @philipwalton 
Fixes #1395 
This allows any of the `workbox.strategies.*` classes to be called manually, outside of a `Route` context.
The JSDocs in this PR refer to https://developers.google.com/web/tools/workbox/guides/advanced-recipes#make-requests, which I'll write following this PR.

Adds makeRequest() method to workbox.strategies

---

infra/testing/sw-env-mocks/Headers.js
packages/workbox-cache-expiration/Plugin.mjs
test/workbox-cache-expiration/node/test-Plugin.mjs

Fixes bug where all responses were seen as expired if expiry was set: adds a proper check to see if response `date` header is set.
Fixes #1416 , #1414, #1329 
If the response header did not have `date`, then `cachedResponse.headers.get('date')` would return `null`, as described here: https://developer.mozilla.org/en-US/docs/Web/API/Headers/get. Since `new Date(null).getTime()` returns 0, not `NaN`, all requests were seen as expired if an expiry was specified.
I can open an issue as per the guidelines, but will be duplicates of #1416, and #1414

Bugfix - Correctly identify when response does not have `date` header set

---

packages/workbox-webpack-plugin/src/inject-manifest.js

Fixes #1428 
Currently, webpack won't rebuild when in watch mode if a custom service worker `swSrc` is modified. This PR adds the custom service worker to the list of watched files according to [this part of the webpack docs](https://webpack.js.org/contribute/plugin-patterns/#monitoring-the-watch-graph).
I looked through the tests for `inject-manifest`, but I'm not entirely sure how to write a proper test that validates the functionality. I'm happy to add a test if someone can point me in the right direction!

Add swSrc to list of file dependencies for InjectManifest

---

packages/workbox-core/_default.mjs

@developit was asking me about when we load `.dev.` vs. `.prod.` bundles, and I realized that we could provide some extra context in our Welcome message to help explain what's going on.
Happy to tweak the actual language if it's too wordy.

More context in the welcome log message

---

demos/functions/views/demo/workbox-background-sync.hbs

Cache should be disabled for GET requests so that the demo worked as intended.

Add one very important detail

---

packages/workbox-strategies/CacheFirst.mjs
packages/workbox-strategies/StaleWhileRevalidate.mjs

Fixes #1435 
This is analogous to the change in #1392. I've gone through all the other strategies that might call `event.waitUntil()` asynchronously, and added the same change there.

Additional try/catch blocks around async waitUntil calls

---

packages/workbox-build/src/entry-points/options/common-generate-schema.js
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js

Fixes #1443
As described in the issue, this prevents a developer from generating a service worker using a configuring that would lead to a runtime error.

Require options.cacheName when options.expiration is set.

---

packages/workbox-webpack-plugin/src/inject-manifest.js
packages/workbox-webpack-plugin/src/lib/read-file-wrapper.js

Fixes https://github.com/GoogleChrome/workbox/issues/1393.
The issue linked above provides a more detailed explanation about the source of this problem.
Short version: The `InjectManifest` version of `workbox-webpack-plugin` currently relies on an internal function `_readFile` of the filesystem API. This only works under specific circumstances, and is unreliable in a more general case (e.g. in case of a decorated filesystem version).
Changes included in this PR:
- Use the public `readFile` function of `webpack`'s filesystem API. Requires an explicit binding for `this`.
- Omit the encoding in `readFileFn` of `readFileWrapper` - it cannot be provided explicitly in this case.

#1393: Only use public API of 'compiler.inputFileSystem'

---

packages/workbox-streams/utils/createHeaders.mjs
test/workbox-streams/node/utils/test-createHeaders.mjs

Fixes #1461
Small change needed to accommodate a quirk with the `Headers` constructor in Samsung Internet 6.4 (Chrome 56).

Use an empty object rather than undefined when calling new Headers()

---

README.md

We hadn't updated the README since moving to developers.google.com, and some of the links were out of date.
I also dropped a few tidbits in favor of driving traffic to the docs, where we can provide more context than this README could provide.

Pruning/updating the README

---

packages/workbox-webpack-plugin/src/inject-manifest.js

CC: @green-arrow 
There were a couple of gotchas that I noticed with #1432 when I was doing some manual testing with `webpack`'s dev server environment:
- The change only worked with `webpack` v3. In v4, `compilation.fileDependencies` is a `Set`, not an `Array`, so a conditional check is required for cross-compatibility.
- The file paths that are passed in to `compilation.fileDependencies` need to be absolute paths, or else they won't accomplish anything. (This requirement might be looser in `webpack` v3, but it's definitely the case in v4.)
This does point to a continued hole in our test coverage, in that we're still tied to `webpack` v3 (see #1281) and we don't test against the `webpack` dev environment (see #1456, though that's just one part of the dev environment). …

webpack v4 fixes for compilation.fileDependencies

---

demos/functions/cdn-details.json
packages/workbox-background-sync/_version.mjs
packages/workbox-broadcast-cache-update/_version.mjs
packages/workbox-build/src/cdn-details.json
packages/workbox-cache-expiration/_version.mjs
packages/workbox-cacheable-response/_version.mjs
packages/workbox-core/_version.mjs
packages/workbox-google-analytics/_version.mjs
packages/workbox-precaching/_version.mjs
packages/workbox-range-requests/_version.mjs
packages/workbox-routing/_version.mjs
packages/workbox-strategies/_version.mjs
packages/workbox-streams/_version.mjs
packages/workbox-sw/_version.mjs

`gulp publish` will end up bumping these version strings, but the changes aren't automatically committed to `master`. So there's a follow-up PR after each release to get them checked in.

3.2.0 version strings

---

packages/workbox-streams/isSupported.mjs
test/workbox-streams/node/test-isSupported.mjs

Fixes #1473
Not urgent, but something to get in for our next patch release.
I've got a locally copy of Workbox with this patch deployed for my streams demo, and can confirm that it properly returned `false` for the current buggy Edge 17 build.

Runtime check for a functional ReadableStream

---

packages/workbox-build/src/lib/use-build-type.js
test/workbox-build/node/lib/use-build-type.js

Fixes #1478 
This code path is still a bit hacky, and there's a lot of hardcoded assumptions, but at least it should now work as expected when the `source` path contains multiple instances of `DEFAULT_BUILD_TYPE`.

Improve the code that swaps 'prod' for 'dev' in copyWorkboxLibraries

---

infra/testing/create-webpack-asset-plugin.js
package-lock.json
package.json
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes #1281 
Given that there doesn't seem to be a clean way to run our tests under both webpack v3 & v4, and given that webpack v4 has all the momentum behind it, it seems like just switching over to run our test suite against v4 makes the most sense.
This PR does not change our compatibility story with webpack v3—it's just changes to our tests.

Run the webpack test suite against webpack v4

---

packages/workbox-background-sync/README.md
packages/workbox-broadcast-cache-update/README.md
packages/workbox-build/README.md
packages/workbox-cache-expiration/README.md
packages/workbox-cacheable-response/README.md
packages/workbox-cli/README.md
packages/workbox-core/README.md
packages/workbox-google-analytics/README.md
packages/workbox-precaching/README.md
packages/workbox-range-requests/README.md
packages/workbox-routing/README.md
packages/workbox-strategies/README.md
packages/workbox-streams/README.md
packages/workbox-sw/README.md
packages/workbox-webpack-plugin/README.md

I forget why we got rid of these back in the day... but I can't think of any reason why we wouldn't want to link to something useful, instead of:

Adds package-level README.md files.

---

gulp-tasks/test-integration.js
packages/workbox-cache-expiration/CacheExpiration.mjs
packages/workbox-cache-expiration/Plugin.mjs
packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs
packages/workbox-core/_private/DBWrapper.mjs
test/workbox-cache-expiration/integration/expiration-plugin.js
test/workbox-cache-expiration/static/expiration-plugin/index.html
test/workbox-cache-expiration/static/expiration-plugin/sw-deletion.js

CC: @josephliccini 
Fixes #1365
It took a while to get a hang of what needed to be explicitly `close()`d in order to avoid `blocked` errors, but I think this implementation works.
I envision making use of this as part of a future PR that will start introducing some opt-in automatic cleanup logic to handle, e.g., `QUOTA_EXCEEDED` errors. For the time being, though, this is just a standalone method that won't be called anywhere automatically.

New workbox.Plugin.deleteCacheAndMetadata() method

---

infra/pr-bot/aggregate-size-plugin.js
pr-bot.config.js

We were previously using 15kb uncompressed as the target size, when we had agreed on 15kb for the compressed size as the target.
We also had the configuration hardcoded to go against the `v3` branch, which was leading to what I think was inaccurate comparisons.
And I also tweaked some of the path settings to help make sure `npm run bot` works locally (it was failing when I tried things out due to a bad `require()` path).

Cleanup for PR Bot config

---

gulp-tasks/utils/cdn-helper.js

Fixes #1412
It took a little bit of experimentation with a test project, but based on [those results](https://storage.googleapis.com/foreign-fetch-demo/0.7232482770712967/subdir/2.js), this code is sufficient to enable both `gzip` compression and the `Cache-Control` header.
(Let's obviously pay close attention to the CDN uploads right after our next release.)

Enable gzip + cache-control on CDN

---

packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/entry-points/options/defaults.js
packages/workbox-cache-expiration/CacheExpiration.mjs
packages/workbox-cache-expiration/Plugin.mjs
packages/workbox-core/_private.mjs
packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-core/_private/quota.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-cache-expiration/node/test-Plugin.mjs
test/workbox-core/node/_private/test-cacheWrapper.mjs
test/workbox-core/node/_private/test-checkSWFileCacheHeaders.mjs
test/workbox-core/node/_private/test-quota.mjs

CC: @raejin @Enalmada @josephliccini
Fixes #1308
There are two changes in this PR:
- There's a check in `workbox-core`'s `cacheWrapper.put()` (which is used "under the hood" throughout Workbox) method to detect when the underlying `cache.put()` fails due to a `QuotaExceededError`. When that happens, one or more previously registered callback functions will automatically be called, and given a chance to free up storage. There is (currently) no attempt made to retry the failed `cache.put()` automatically after the cleanup completes, and the `QuotaExceededError` will be re-thrown and bubble-up to the method that called `cacheWrapper.put()` originally.
- There's a new `purgeOnQuotaError` option added to the `workbox.expiration.Plugin` constructor. It defaults to `false`. When …

Opt-in method for purging (some) caches upon a QuotaExceededError

---

gulp-tasks/utils/cdn-helper.js

As per https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1087#issuecomment-175105508, perhaps this will work?

Properly set Cache-Control on CDN hosting

---

packages/workbox-cache-expiration/Plugin.mjs
packages/workbox-core/_private.mjs
packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-core/_private/quota.mjs
packages/workbox-core/package.json
test/workbox-cache-expiration/node/test-Plugin.mjs
test/workbox-core/node/_private/test-cacheWrapper.mjs
test/workbox-core/node/_private/test-quota.mjs

We previously had two exports in `quota.mjs` named `registerCallback` and `executeCallbacks`, and `registerCallback` was exposed publicly in `worbox.core` as `worbox.core.registerQuotaExceededCallback`.
As pointed out in https://github.com/GoogleChromeLabs/so-pwa/issues/2, the Rollup-generated bundles don't work nicely due to this aliasing. There's a spot in the codebase that imported `registerCallback` from `workbox-core`, and even though that symbol exists before bundling, it doesn't exist post-bundling, leading to runtime errors.
To avoid this, I'm just explicitly renaming all the symbols to be as verbose as we need, rather than aliasing them after the fact.
(I'm not sure whether this constitutes a bug in Rollup, but I'd like to work around it in our codebase first.)

Don't alias the exported workbox.core.registerQuotaExceededCallback symbol

---

README.md

Fixes #1410
Adds a badge linking to the TypeScript definitions (and drops the `dependencies` freshness badge, since the main package in the monorepo doesn't have any dependencies).

README badge update

---

package-lock.json
package.json
packages/workbox-strategies/CacheFirst.mjs
packages/workbox-strategies/CacheOnly.mjs
packages/workbox-strategies/NetworkFirst.mjs
packages/workbox-strategies/StaleWhileRevalidate.mjs
test/workbox-strategies/node/test-CacheFirst.mjs
test/workbox-strategies/node/test-CacheOnly.mjs
test/workbox-strategies/node/test-NetworkFirst.mjs
test/workbox-strategies/node/test-StaleWhileRevalidate.mjs

Fixes #1550
Add support for CacheQueryOptions when performing cache.match. Previously workbox.strategies always passed null as match options to cacheWrapper.match. This PR add the ability to configure CacheQueryOptions through the matchOptions property.

Use CacheQueryOptions in workbox.strategies

---

packages/workbox-core/_private/DBWrapper.mjs

Fixes #1509
Edge Browser does not support `undefined` arguments being passed into `openCursor(...)`
I handle each case for the arguments to `openCursor(...)`
See https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openCursor for more information on the API itself.
This will fix the CacheExpiration logic in Edge Browsers that depend on `openCursor(...)` in the expiration entry lookup process.

Fix CacheExpiration / IndexedDB OpenCursor for Edge

---

packages/workbox-strategies/_default.mjs

CC: @surma 
Fixes #1587 
We were referencing a `workbox.strategies.StrategyOptions` definition that no longer exists. This change points folks to the corresponding documentation for the equivalent class constructor.

Link to the class constructors' docs instead of StrategyOptions

---

packages/workbox-build/package-lock.json
packages/workbox-build/package.json
packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/lib/runtime-caching-converter.js

Fixes #1597
As discussed on the issue, I've used [this library](https://github.com/yeoman/stringify-object) by Yeoman instead of JSON.stringify because it doesn't handle functions, resulting in an empty object when adding custom plugins with workbox-webpack-plugin. Also, I've made some changes and now I'm using a regex based on [this one](http://blog.moagrius.com/javascript/javascript-regexp-to-remove-comments/) to remove comments once the object is parsed as a string.
Also added some test cases.

Fix empty object when adding runtimeCaching custom plugins with workbox-webpack-plugin

---

packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/lib/runtime-caching-converter.js

Fixes #1607
Caching strategies support taking objects for `fetchOptions` and `matchOptions`, but `runtimeCachingConverter` has no support for taking them as input.
I've left both as `joi.object()` in the schema, as I'm not sure how to specify a DOM interface as the type/if it's possible, and I don't think it makes sense to duplicate browser specs in the schema.

Add support for fetchOptions/matchOptions in runtimeCachingConverter

---

packages/workbox-core/_private.mjs
packages/workbox-core/browser.mjs
packages/workbox-core/index.mjs
test/workbox-core/node/test-exports.mjs

Fixes #1616
This renames `workbox.core._private.reigsterQuotaErrorCallback` to `workbox.core.reigsterQuotaErrorCallback`, matching the docs and the intended interface.
It's a change to our interface, but since it amounts to removing something that was under `_private` (and is likely not to be widely used directly as-is), I'm inclined to say that we can get this in outside of a major semver release, as long as we document the change in the release notes.

Expose workbox.core.registerQuotaErrorCallback

---

packages/workbox-streams/_public.mjs
packages/workbox-streams/browser.mjs
packages/workbox-streams/index.mjs
packages/workbox-streams/strategy.mjs

This PR:
- Moves the `strategy()` function form `_default.mjs` into it's own file, so it can be imported on it's own (e.g. `import {strategy} from 'workbox-streams/strategy.mjs'`).
- Removes the `_default.mjs` file as there's no "special" default export outside of what's already in `_public.mjs`.

Move the stategy function into its own file

---

packages/workbox-build/src/entry-points/options/common-generate-schema.js

Add method option to GenerateSW validation

---

test/workbox-cache-expiration/static/expiration-plugin/sw-deletion.js

This would catch https://github.com/GoogleChrome/workbox/issues/1642 the next time around by making sure we use that export in the final bundle in an integration test.
(The actual behavior for `purgeOnQuotaError` is tested in the unit tests.)

Use purgeOnQuotaError in integration test

---

packages/workbox-broadcast-cache-update/Plugin.mjs
packages/workbox-cache-expiration/Plugin.mjs
packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-core/_private/fetchWrapper.mjs
packages/workbox-precaching/_default.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
packages/workbox-routing/NavigationRoute.mjs
packages/workbox-strategies/CacheFirst.mjs
packages/workbox-strategies/CacheOnly.mjs
packages/workbox-strategies/NetworkFirst.mjs
packages/workbox-strategies/NetworkOnly.mjs
packages/workbox-strategies/StaleWhileRevalidate.mjs
packages/workbox-strategies/plugins/cacheOkAndOpaquePlugin.mjs
test/workbox-core/node/_private/test-cacheWrapper.mjs
test/workbox-core/node/_private/test-fetchWrapper.mjs
test/workbox-precaching/node/controllers/test-PrecacheController.mjs

Fixes #1639. 
This PR implements the proposal in #1639 by updating the fetch and catch wrappers as well as the strategies (and other code) that calls them. It also removes the `preloadResponse` option passed to the fetch wrapper, since that can now be found on the fetch event (@jeffposnick can you confirm that's okay?).
In addition, I noticed we're being inconsistent in how we refer to restructured parameters in our JSDoc comments (`options` vs `input`), so, since I was already updating some, I decided to change all instances of `input` to `options`.

Expose the event object to plugin methods

---

.travis.yml
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

This needs to be done when we change the `webpack` dependency versions, as different webpack versions tend to spit out different hashes for the same source content.

Fix for the workbox-webpack-plugin tests

---

infra/testing/sw-env-mocks/Headers.js
packages/workbox-precaching/utils/cleanRedirect.mjs
test/workbox-precaching/node/utils/test-cleanRedirect.mjs

While investigating https://github.com/GoogleChrome/workbox/issues/1677 I realized that there's a bug in the `Request` constructor usage inside the code that "cleans up" redirected responses.
The code in this PR just takes the [corresponding code](https://github.com/GoogleChromeLabs/sw-precache/blob/e5892c9a3cce1a8d4f6de2aa768287cb709ba1e7/lib/functions.js#L101-L105) from `sw-precache`'s implementation, which should work.
I'm filing this PR against `next` because I don't think it's an *urgent* bug to fix, and I'd rather we don't cut any additional v3 releases if we can help it.

Fix cleanRedirect logic

---

packages/workbox-webpack-plugin/src/lib/get-default-config.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes #1665 
We no longer will match `manifest.json` in `workbox-webpack-plugin`'s default list of patterns to filter out.

Precache manifest.json by default when using the webpack plugin

---

.gitignore
demos/functions/cdn-details.json
gulp-tasks/publish-cdn.js
gulp-tasks/utils/cdn-helper.js
gulp-tasks/utils/publish-helpers.js

Fixes some issues with the `gulp publish-assets` command in the `next` branch.

Cleanup publishing for next branch

---

package-lock.json
package.json
packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs
packages/workbox-core/_private.mjs
packages/workbox-core/_private/DBWrapper.mjs
packages/workbox-core/_private/deleteDatabase.mjs
test/workbox-core/node/_private/test-DBWrapper.mjs

As noted in https://github.com/GoogleChrome/workbox/pull/1510#issuecomment-396643575, the version of `DBWrapper` was slightly behind the version I was working to release separately (which ended up not happening after a decision to merge it with `idb` once the promise issue was resolved).
The up-to-date version has been tested against all browsers (including IE10 and Safari 10.1), and [already included](https://github.com/GoogleChrome/workbox/compare/next...db-wrapper-updates?expand=1#diff-5c1f717d7f769e925ffa201e42c73ce5R151) the fix from #1509.
Making this update required me to also [update to my fork](https://github.com/philipwalton/shelving-mock-indexeddb/commit/4cf22cfcd464cbae648ebbe73268c2a72e110ad6) of our IDB mocking library due to the following issues with the …

DBWrapper updates

---

packages/workbox-core/models/messages/messages.mjs
packages/workbox-precaching/_default.mjs
packages/workbox-precaching/controllers/PrecacheController.mjs
test/workbox-precaching/node/controllers/test-PrecacheController.mjs

CC: @josephliccini 
Fixes #1711, to be released as part of v4.
Previously, if you precached a URL that resulted in a 4xx or 5xx response, that would not result in a failure to install the service worker, and you could end up with an active service worker that continuously responded to requests with that (potentially transient) original error.
I think the intention had always been to cause this to be a fatal situation that would then trigger another re-installation attempt, and this was an oversight. (Potentially a v3 regression? Not 100% sure.)

Fail SW installation when a precaching request results in an error response

---

packages/workbox-range-requests/createPartialResponse.mjs
test/workbox-range-requests/node/createPartialResponse.mjs

CC: @jakearchibald
Fixes #1720
This doesn't change much right now, but if and when the Cache Storage API starts generating `HTTP 206 Partial Content` responses, it ensures that `workbox-range-requests` usage wouldn't double-slice.

workbox-range-requests will return a 206 response as-is

---

infra/testing/sw-env-mocks/Headers.js
packages/workbox-precaching/utils/cleanRedirect.mjs
test/workbox-precaching/node/utils/test-cleanRedirect.mjs

Fixes #1677
This takes the v4 change from #1678 and backports it to the v3 branch.
After doing some `git` digging, the change that introduced the issue turned out to be https://github.com/GoogleChrome/workbox/pull/828/files#diff-37d7dc9fcc2f99bebe79d4b453e132fe, i.e. it looks inadvertant, so I can't think of a reason why we wouldn't want this code to be in v3.x.

Backporting the 301 redirect fix to v3 branch

---

package-lock.json
package.json
packages/workbox-background-sync/Plugin.mjs
packages/workbox-background-sync/Queue.mjs
packages/workbox-background-sync/models/QueueStore.mjs
packages/workbox-background-sync/models/StorableRequest.mjs
packages/workbox-background-sync/utils/constants.mjs
packages/workbox-core/_private.mjs
packages/workbox-core/_private/migrateDb.mjs
packages/workbox-core/models/messages/messages.mjs
packages/workbox-google-analytics/initialize.mjs
test/workbox-background-sync/node/lib/test-QueueStore.mjs
test/workbox-background-sync/node/lib/test-StorableRequest.mjs
test/workbox-background-sync/node/test-Plugin.mjs
test/workbox-background-sync/node/test-Queue.mjs
test/workbox-background-sync/static/basic-example/sw.js
test/workbox-core/node/_private/test-DBWrapper.mjs
test/workbox-google-analytics/integration/basic-example.js
test/workbox-google-analytics/node/test-index.mjs

Addresses #1424, #1502, #1503, #1637, and #1695.
Based on lots of feedback in the above issues/PRs, its clear that the callbacks provided in `workbox.backgroundSync.Queue` are not sufficient to handle many real-world background sync needs.
This PR attempts to solve this issue by exposing more low-level features of the queue, which should give developers all the flexibility they need; the downside is it may make very simple replay modifications a bit more complicated. Hopefully (due to the complex nature of background sync in general), this downside will affect very few people.
In Workbox v3, the `workbox.backgroundSync.Queue` class had the following public methods:
- `addRequest()`
- `replayRequests()`
And the following replay callbacks that allowed you modify requests as …

v4 Background Sync API updates

---

packages/workbox-routing/Router.mjs
test/workbox-routing/node/test-Router.mjs
test/workbox-routing/node/test-interface.mjs

CC: @westonruter
This takes a private property and exposes it publicly, as part of v4. There's going to be a (small) hit in bundle size, since that property name can't be mangled anymore.

Make Router.routes public

---

packages/workbox-build/src/lib/runtime-caching-converter.js
packages/workbox-build/src/lib/stringify-without-comments.js

Fixes #1761
- use `stringify-object` instead of `JSON.stringify`

use stringify-object instead of JSON.stringify

---

packages/workbox-webpack-plugin/src/lib/stringify-manifest.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

CC: @AidanDai to confirm this addresses their issue.
Fixes #1762
Instead of assigning to `self.__precacheManifest`, the webpack plugin will concatenate to the end (or just to the end of `[]`).

concat, rather than overwrite, self.__precacheManifest

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/entry-points/generate-sw.js

Fixes #1764
Pretty straightforward change to allow for functions to be passed in as the `urlPattern` value when using `runtimeCaching`.
The main difficulty was getting this tested, since `chai` isn't happy when using `deep.equal` to compare functions.

Support using a function as urlPattern in runtimeCaching

---

packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-core/_private/fetchWrapper.mjs
packages/workbox-core/models/pluginEvents.mjs
test/workbox-core/node/_private/test-fetchWrapper.mjs

Fixes #788, fixes #1391, fixes #1481
Adds a new `fetchDidSucceed` callback, which allows a plugin to modify a request that's been retrieved from the network.
This was requested by @weeblr back in the day.
We'll need to update https://developers.google.com/web/tools/workbox/guides/using-plugins once v4 goes live to reflect this new callback.

Adds a fetchDidSucceed callback

---

test/workbox-precaching/integration/precache-and-update.js

Fixes #1804
This, as all magic sleep values, is gross... but we already were sleeping for `100ms`, and it looks like that isn't enough in the current Chrome Beta. Bumping it up to `1000ms` made the tests pass locally...

Bumps a sleep value in workbox-precaching's integration test

---

packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-strategies/plugins/cacheOkAndOpaquePlugin.mjs
test/workbox-core/node/_private/test-cacheWrapper.mjs
test/workbox-strategies/node/test-cacheOkAndOpaquePlugin.mjs

Fixes #1804
Currently, we'll default to attempting to cache when `response.status === 206`, which is explicitly disallowed by the Cache Storage API.
This can still be overridden by `workbox-cacheable-response` for folks who need to customize the defaults.

Default to response.status === 200 instead of response.ok

---

packages/workbox-routing/Router.mjs
test/workbox-routing/node/test-Router.mjs

Fixes #1826
I choose to initially go with a solution that just lets developers choose what init options they want. I figure we can hold off on implementing any automagic behavior until we see what/if our `workbox-window` method for doing this automatically looks like.

Support requestInit in CACHE_URLS message URLs

---

packages/workbox-core/_private/fetchWrapper.mjs
test/workbox-core/node/_private/test-fetchWrapper.mjs

This is related to https://github.com/GoogleChrome/workbox/issues/1796, but it doesn't fix it. The workaround that I added to fix it led to issues in Edge, and rather than continue to iterate and try to find a fix for the v4.0.0 release, I'm going to work around the issue by making sure we don't set `fetchOptions` when `request.mode === 'navigate'`.
This is strictly better than the behavior in v3, where you could end up with failed navigations in this scenario.
The ultimate fix is to find the cleanest, cross-browser-compatible way to create a new `Request` with `mode` set to `'same-origin'` and all of the other `Request` properties carried over. I'd like to punt on that until after the final v4.0.0 release, though.

Don't set fetchOptions when request.mode is 'navigate'

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/entry-points/options/defaults.js
packages/workbox-build/src/lib/populate-sw-template.js
packages/workbox-build/src/lib/write-sw-using-default-template.js
packages/workbox-build/src/templates/sw-template.js
test/workbox-build/node/lib/populate-sw-template.js
test/workbox-webpack-plugin/node/generate-sw.js

This adds a new option available to the various `GenerateSW` build integrations to automatically call `workbox.precaching.cleanupOutdatedCaches()` for you, when `cleanupOutdatedCaches: true` is set. (The default is not to call it.)
Calling that method will attempt to find and remove any of the older precaches that might have been used by previous versions of Workbox, as Workbox v4 moved to a new, incompatible precaching format.

GenerateSW config support for cleanupOutdatedCaches

---

packages/workbox-google-analytics/initialize.mjs
packages/workbox-google-analytics/utils/constants.mjs
test/workbox-google-analytics/integration/basic-example.js
test/workbox-google-analytics/node/test-index.mjs
test/workbox-google-analytics/static/basic-example/sw.js

A continuation of https://github.com/GoogleChrome/workbox/pull/1837. This also fixes #1751 for real.

Cache gtm.js runtime caching

---

demos/functions/cdn-details.json
infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/templates/sw-template.js
packages/workbox-routing/registerNavigationRoute.mjs
test/workbox-build/node/entry-points/generate-sw-string.js
test/workbox-build/node/entry-points/generate-sw.js

Fixes #1873
This updates the templated used in `GenerateSW` mode to account for the fact that `workbox.precaching.getCacheKeyForUrl()` need to be called to translate the `navigateFallback` URL into a cache key URL.
It also updates the JSDoc to reflect that requirement. This should also be called out as part of our migration docs, for folks like @prateekbh who ran into this when using `InjectManifest` mode and need to make manual updates.

Add getCacheKeyForUrl() in GenerateSW mode

---

gulp-tasks/test-integration.js
package-lock.json
package.json

This PR updates `selenium-assistant` to version `5.4.0`, which includes [this fix](https://github.com/GoogleChromeLabs/selenium-assistant/pull/113) for Safari 12. With this fix we can now resume running our local integration tests against Safari before deployments.

Re-enable Safari integration tests

---

infra/testing/comlink/sw-interface.js
package-lock.json
package.json
packages/workbox-expiration/CacheExpiration.mjs
packages/workbox-expiration/Plugin.mjs
packages/workbox-expiration/models/CacheTimestampsModel.mjs
test/workbox-expiration/integration/expiration-plugin.js
test/workbox-expiration/node/test-CacheExpiration.mjs
test/workbox-expiration/node/test-CacheTimestampsModel.mjs
test/workbox-expiration/node/test-Plugin.mjs
test/workbox-expiration/static/expiration-plugin/sw-deletion.js
test/workbox-expiration/static/expiration-plugin/sw-max-age-seconds.js
test/workbox-expiration/static/expiration-plugin/sw-max-entries.js

Fixes #1398, Fixes #1400. 
This PR updates the IDB data model used by `workbox-expiration`, switching it to from multiple databases (named the same as the cache name), to  a single database (named `workbox-expiration`) where the entries in the database have a `cacheName` property.
I've also updated how expiration happens to make it more efficient. Previously the entire contents of the object store would be read out, the purgeable entires were determined, and then in a second transaction those entries would be removed. In this PR I've moved the logic that determines what needs to be expired into `CacheTimestampsModel`, so it can all happen inside a single transaction.
Lastly, I had to update our IDB mocks yet again due to bugs I found when running tests. I've manually …

Update the workbox-expiration IDB data model

---

packages/workbox-build/src/entry-points/generate-sw.js
packages/workbox-build/src/lib/copy-workbox-libraries.js

Fixes #1901 by ensuring that we pick up the paths to copy via `require.resolve()`.

Fix for copyLibraries

---

.eslintrc.js
packages/workbox-window/Workbox.mjs
test/workbox-window/integration/test.js
test/workbox-window/unit/test-Workbox.mjs

This PR add the `isUpdate` and `wasWaitingBeforeRegistration` flags on the relevant `workbox-window` lifecycle events, and it adds jsdoc comments for the events and their callback parameters.
/cc @webmaxru

Add isUpdate and wasWaitingBeforeRegistration to workbox-window lifecycle events

---

packages/workbox-routing/Router.mjs
test/workbox-routing/node/test-Router.mjs

When writing the `workbow-window` documentation, I realized that the logic in `Router#addCacheListener` includes a check for `meta === 'workbox-window'`, but we shouldn't require developers to be use `workbox-window` to cache URLs (or ask them to set that meta value themselves, which wouldn't make sense).
This PR removes that check. It also adds a response to the message event if it contains a message channel (which `workbox-window` message do by default). This allows users to await successful caching of all URLs, similar to what you get with precaching.
Note: I did not add a message response in the event of an error, but I potentially could? WDYT?

Add a cache listener message response

---

packages/workbox-window/Workbox.mjs

While implementing `workbox-window` myself, I noticed that when upgrading a service worker, the message that was logged for the old service worker becoming redundant was a bit misleading. This change better handles both a registered and an originally-controlling service worker becoming redundant.

Update log messages on redundant SW

---

packages/workbox-routing/Router.mjs
packages/workbox-strategies/CacheFirst.mjs
packages/workbox-strategies/NetworkFirst.mjs
packages/workbox-strategies/StaleWhileRevalidate.mjs
test/workbox-routing/node/test-Router.mjs

This PR fixes an issue with the cache listener logic (it was awaiting an array instead of a `Promise`), and it changes the code to call `event.waitUntil()` explicitly in the listener rather than passing the event to various handler functions.
This seems to be a safer approach since handler functions may incorrectly assume the event if a `FetchEvent` (as some of them already do, see the strategy changes).

Update cache message wait until logic

---

infra/testing/sw-env-mocks/ExtendableMessageEvent.js
packages/workbox-routing/Router.mjs
test/workbox-routing/node/test-Router.mjs

While testing out the latest Workbox RC I noticed that if you run `Router#addCacheListener()` and then `postMessage()` to the SW anything that's not an object, it'll fail.
This PR adds an extra check and test that should ensure non-`CACHE_URLS` messages don't cause errors.

Add a null check for cache listener message data

---

packages/workbox-core/_private/cacheWrapper.mjs
packages/workbox-precaching/PrecacheController.mjs
test/workbox-core/node/_private/test-cacheWrapper.mjs
test/workbox-precaching/node/test-PrecacheController.mjs

This will pass `ignoreSearch: true` through to the underlying call to `cache.match()` that attempts to find the previously precached entry with the same URL, in order to detect whether there's been an update. This is in turn used by the `broadcast-update` plugin.
This is necessary in v4 because the previously cached URL may have a `__WB_REVISION__` URL query parameter.
This should only affect cache wrapper usage from within the `PrecacheController`, as in all other uses, the `matchOptions` will remain `undefined`.
CC: @webmaxru

Use ignoreSearch to fix precaching broadcast updates.

---

packages/workbox-precaching/PrecacheController.mjs
test/workbox-precaching/node/test-PrecacheController.mjs
test/workbox-precaching/static/precache-and-update/sw-1.js

Fixes #1927 by properly `bind()`ing to the `Plugin` instance.
This also adds to the integration test for `workbox-precaching` to ensure that the `addPlugins()` flow has better test coverage.

Call bind() to get the right this in precaching's plugins

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/templates/sw-template.js
test/workbox-build/node/entry-points/generate-sw.js

Fixes #1753 
If `generateSW` is called from our build tools, and `skipWaiting` is `false` (the default), the resulting service worker will include a `message` event listener which checks for `event.data.type === 'SKIP_WAITING'`. If the service worker receives that message, it will call `self.skipWaiting()`.
We should update our recipes to include an example of this once it gets deployed.

Add a message listener when generateSW is called with skipWaiting: false

---

packages/workbox-broadcast-update/BroadcastCacheUpdate.mjs

Fixes #1931
Right now the plugin assumes that if `event` is set, then `event.request` will also be set. That isn't the case if `event` is an `InstallEvent`, which is what happens when the plugin is used along with `workbox-precaching`.

Explicitly check event.request in BroadcastUpdatePlugin

---

packages/workbox-window/Workbox.mjs
test/workbox-window/unit/test-Workbox.mjs

Fixes #1939
The previous workbox-window logic would created a deferred for the instances "own" service worker and, once resolved, always return that service worker in the `getSW()` (and consequently the `messageSW()` method). But in the case of a SW already controlling the page and then an update being found for the same URL, this wouldn't be the desired behavior.
This PR updates the logic to handle this case.
/cc @Avocher

Resolve getSW correctly after an update is found

---

packages/workbox-background-sync/Queue.mjs
packages/workbox-google-analytics/initialize.mjs
test/workbox-background-sync/node/test-Queue.mjs
test/workbox-google-analytics/integration/basic-example.js
test/workbox-google-analytics/static/basic-example/sw.js

Fixes #1937 
This PR updates the background sync replay logic in the following ways to help prevent infinite loops when adding new requests to the queue during a sync event replay:
- Adding a request to the queue only registers a sync tag if a `sync` event is not currently in progress.
- At the end of a successful sync event replay (i.e. the `waitUntil` promise did not reject) a sync tag is registered if new requests have been added to the queue.
- At the end of a failed sync event replay (i.e. the waitUntil promise rejected) no sync event is registered because the browser will automatically retry later (unless the `event.lastChance` property is true, in which case a new sync tag is registered
The PR also updates some of the `workbox-google-analytics` behavior to handle …

Prevent onSync infinite loops

---

packages/workbox-window/Workbox.mjs
test/workbox-window/unit/test-Workbox.mjs

Fixes #1957
This PR updates the logic for how an "own" service worker is resolved in `workbow-window` as follows:
If a service worker with a matching `scriptURL` was already waiting to activate at registration time, it is considered to be the "own" service worker and thus will be the service worker `getSW()` resolves to.
In cases where there's an active *and* waiting service worker at registration time with a matching `scriptURL`, `getSW()` will resolve to the waiting service worker because it's the one that was registered most recently.

Resolve getSW() to a matching waiting SW

---

packages/workbox-window/utils/EventTargetShim.mjs
test/workbox-window/unit/test-Workbox.mjs

Fixes #1962 
`Set` does not have a `remove` method. It should be `delete`.

Allow wb.removeEventListener to work without an exception

---

packages/workbox-webpack-plugin/src/generate-sw.js
packages/workbox-webpack-plugin/src/lib/stringify-manifest.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes #1972
Added sorting before generating a hash

Make the sw imports sorted

---

packages/workbox-background-sync/lib/QueueStore.mjs
test/workbox-background-sync/sw/lib/test-QueueStore.mjs
test/workbox-background-sync/sw/test-Queue.mjs

This PR incorporates some of the helpers added in the `workbox-google-analytics` tests migrations, and it updates the use of IndexedDB to avoid flakiness in Firefox and Safari being blocked when deleting databases in a service worker.

Fix flakiness in background sync tests

---

packages/workbox-core/_private/cacheNames.mjs
packages/workbox-core/cacheNames.mjs
test/workbox-core/static/core-in-browser/sw.js
test/workbox-core/sw/test-cacheNames.mjs

CC: @westonruter
Fixes #1998
The original request was just for the prefix, but I've added the suffix getter as well, since it presumably might be useful for the same reasons.

Adds cacheNames.prefix/suffix

---

test/workbox-cli/node/app.js

It's no longer needed now that we're not using `esm`.

Remove extra escaping in Windows CLI test

---

packages/workbox-build/src/templates/sw-template.js

Fixes #1915 / #1981 
Sorry to follow up with a PR immediately after the publish, but it turns out order in the template does matter, as otherwise `workbox` might not be defined yet (total facepalm on my part)! I feel like I probably missed implementing a test somewhere in the initial pass but I'm not sure where that should've gone, so I at least added a warning comment for now. Let me know if there's something better I could add.

Ensure workbox is available before referencing it

---

packages/workbox-background-sync/Queue.mjs
test/workbox-background-sync/sw/test-Queue.mjs

Fixes #1984
The issue in #1984 was the request wasn't being cloned in the re-`fetch()` attempt, which in some cases (depending on the request method and body) was causes issues when attempting to clone it later when re-adding it to the queue. 
This PR fixes the issue and updates the tests to manually read the request when re-fetching to ensure this kind of thing would be caught in the future.

Fix a background sync reply bug

---

packages/workbox-background-sync/lib/StorableRequest.mjs
test/workbox-background-sync/sw/lib/test-StorableRequest.mjs

Fixes #1955
PR updates the `StorableRequest` object to ensure any instances created from navigation requests will get serialized as `same-origin` requests since navigation requests cannot be script-constructed.

Ensure navigation requests queue as some-origin

---

packages/workbox-build/src/lib/runtime-caching-converter.js
test/workbox-build/node/lib/runtime-caching-converter.js

Fixes #2016, by accounting for the fact that the broadcast update plugin is now passed the channel name as a named parameter in the options object.

Fixes opts passed to the BCU Plugin.

---

packages/workbox-background-sync/Queue.mjs
packages/workbox-background-sync/lib/QueueStore.mjs
packages/workbox-expiration/Plugin.mjs
test/workbox-background-sync/sw/lib/test-QueueStore.mjs
test/workbox-background-sync/sw/test-Queue.mjs

Fixes #2011
This PR adds a method to count the number of entries in the queue store for the given queue name.
***
**UPDATE:** Given https://github.com/GoogleChrome/workbox/issues/2011#issuecomment-480731157 and the fact that the initial changes in the PR didn't consider that a simple IndexedDB count operation wouldn't account for entries that have expired, I decided to just add a single `getAll()` method that returns an array of unexpired entries. Users who need a count can access that array's length.

Add a size method to the Queue class

---

packages/workbox-build/package-lock.json
packages/workbox-build/package.json
packages/workbox-build/src/entry-points/options/base-schema.js
packages/workbox-build/src/entry-points/options/common-generate-schema.js
packages/workbox-build/src/entry-points/options/generate-sw-schema.js
packages/workbox-build/src/entry-points/options/generate-sw-string-schema.js
packages/workbox-build/src/entry-points/options/get-manifest-schema.js
packages/workbox-build/src/entry-points/options/inject-manifest-schema.js
packages/workbox-build/src/entry-points/options/reg-exp-object.js

Fixes #2043 
As far as I can tell, there are  no incompatible changes between `joi` v14 and `@hapi/joi` v15.

Switch to @hapi/joi

---

packages/workbox-routing/NavigationRoute.mjs

Given that I struggled to find these console logs because I was using console filtering (which is a quite common practice), I think it would be nice to add the `${pathnameAndSearch}` within the `_match()` logging, in order to discover issues like this more quickly: https://github.com/facebook/create-react-app/pull/7176
Cc @jeffposnick
Thanks!

Add ${pathnameAndSearch} info within _match() logging

---

packages/workbox-build/src/lib/module-registry.js
test/workbox-build/node/lib/module-registry.js

Fixes #2106 
Changed module resolution to use require.resolve for import paths.

Fix import resolution in workbox-build

---

packages/workbox-window/src/Workbox.ts
test/workbox-window/window/test-Workbox.mjs

Fixes #2101
Adds the missing `isUpdate` property to the `controlling` event in `workbox-window`.

Add missing isUpdate to the controlling evnet

---

packages/workbox-build/src/lib/bundle.js
test/workbox-build/node/lib/bundle.js

Fixes #2111
Thanks for pointing this out, @kaykayehnn! This PR seems to address the issue in the test case you provided.

Bypass local Babel config files in workbox-build's bundling step

---

packages/workbox-precaching/src/addRoute.ts
packages/workbox-precaching/src/precacheAndRoute.ts
packages/workbox-precaching/src/utils/addFetchListener.ts

The `FetchListenerOptions` parameter to `precacheAndRoute()` should be marked as optional. If it's not set, it will end up being set to some defaults by https://github.com/GoogleChrome/workbox/blob/b32a0823c942d49567d3f2bd49c0a92815476910/packages/workbox-precaching/src/utils/addFetchListener.ts#L51-L56

Make FetchListenerOptions optional

---

packages/workbox-build/src/entry-points/options/webpack-inject-manifest-schema.js
test/workbox-webpack-plugin/node/inject-manifest.js
test/workbox-webpack-plugin/static/sw.ts

Our webpack plugin will generate a default output service worker filename (`swDest`) using the basename of the required `swSrc` parameter when `swDest` isn't explicitly provided.
If the `swSrc` file is TypeScript, then chances are it has a `.ts` extension, and we don't want that to be used as the extension in `swDest`. (Ideally, the developer will have set up `ts-loader` to automatically compile the TypeScript file in their build process, so the output will be JavaScript.)
This change forces the `.js` file extension whenever we're calculating a default `swDest` value.

Use a .js extension when generating a default swDest

---

packages/workbox-background-sync/src/Queue.ts
packages/workbox-background-sync/src/lib/QueueStore.ts
packages/workbox-broadcast-update/src/BroadcastCacheUpdate.ts
packages/workbox-expiration/src/Plugin.ts
packages/workbox-expiration/src/models/CacheTimestampsModel.ts
packages/workbox-routing/src/NavigationRoute.ts
packages/workbox-strategies/src/NetworkFirst.ts
packages/workbox-window/src/Workbox.ts

When testing out the TypeScript functionality, I noticed that there were a bunch of methods on `workbox-window` that started with `_` and were `@private` in JSDoc, but weren't marked `private` in TypeScript.
I wonder if this is something we could catch via linting or some sort of post-TypeScript-compilation test?

Adds the private TS annotation to _methods()

---

packages/workbox-precaching/src/precache.ts
packages/workbox-precaching/src/precacheAndRoute.ts

I'm not 100% sure that this is the right way to do things, so please review this with skepticism, but this definition is the cleanest way I could come up with to support using `self.__WB_MANIFEST` inside of a TypeScript `swSrc` file.
The usage ends up looking like:
```typescript
import {precacheAndRoute, WorkboxGlobalScope} from 'workbox-precaching/precacheAndRoute';
declare const self: WorkboxGlobalScope;
precacheAndRoute(self.__WB_MANIFEST);
```
Maybe we should have a separate `WorkboxGlobalScope` declaration inside of `workbox-core` instead, which would presumably make it cleaner if we ever added in custom global properties that weren't related to `workbox-precaching`?

Define WorkboxGlobalScope in workbox-precaching

---

.gitignore
packages/workbox-build/src/entry-points/options/base-schema.js
packages/workbox-build/src/entry-points/options/manifest-entry-object.js
packages/workbox-build/src/lib/additional-manifest-entries-transform.js
packages/workbox-build/src/lib/errors.js
packages/workbox-build/src/lib/get-file-manifest-entries.js
packages/workbox-build/src/lib/transform-manifest.js
packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-build/node/entry-points/inject-manifest.js
test/workbox-build/node/lib/additional-manifest-entries-transform.js
test/workbox-webpack-plugin/node/generate-sw.js

Fixes #1571 by adding in a new `additionalManifestEntries` option that can be passed in to any of the build tools.

Adds support for additionalManifestEntries build option

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/entry-points/options/webpack-generate-sw-schema.js
packages/workbox-webpack-plugin/src/generate-sw.js
packages/workbox-webpack-plugin/src/lib/get-script-files-for-chunks.js
test/workbox-build/node/entry-points/generate-sw.js
test/workbox-webpack-plugin/node/generate-sw.js

Fixes #1752
This new option in `workbox-webpack-plugin`'s `GenerateSW` mode allows you to use the name of chunks from your `webpack` compilation as the source for `importScripts()`. It also takes steps to exclude whatever's imported via `importScripts()` from the precache manifest, since the service worker maintains its own cache of imported scripts.
It's important that developers use this with versioned filenames (i.e. including a hash), since the current service worker implementations in browsers won't check for updates to imported scripts unless their URL changes.
In the course of writing tests for this, I also fixed some of the validation logic around calls to `importScripts`, making it so that we can check to make sure that the Workbox runtime is imported without …

Adds importScriptsViaChunks option to webpack plugin

---

packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js
test/workbox-precaching/sw/test-PrecacheController.mjs

I realized in https://github.com/GoogleChrome/workbox/pull/2131 that we can limit the fields returned by the `compilation.getStats().toJson()` call so that it only includes what we need.
This PR changes an existing usage to just return fields we need for a different use case.

Limit the webpack stats to what we need

---

packages/workbox-routing/src/Router.ts
test/workbox-routing/sw/test-Router.mjs

Fixes #2079
This change results in more return values from the `matchCallback` being passed through to the `handlerCallback` as the `params` option.
(There is still some special-case logic for `{}` and `[]` being treated as `{params: undefined}`, matching the existing v4 behavior. It's implemented this way to make it easier to deal with a `matchCallback` that uses a `RegExp` with capture groups.)

Pass more matchCallback return values through to handlerCallback

---

packages/workbox-window/src/Workbox.ts
packages/workbox-window/src/utils/WorkboxEvent.ts
packages/workbox-window/src/utils/WorkboxEventTarget.ts

This PR adds some additional type information to address #2144. Primarily, it adds additional event callback types as well as a `WorkboxEventMap` interface so callbacks can declare their event callback argument types based on the event type passed to `addEventListener()`.
This means developer code doesn't have to import the `WorkboxEvent` type and annotate their own callbacks -- the types are inferred from the event type listened to. (Note: I took this pattern from the built-in [`addEventListener()`](https://github.com/microsoft/TypeScript/blob/3f75d2c8790b9e2d5d99b9d2b830a4e6a624151a/src/lib/dom.generated.d.ts#L18602) declaration, so I assume it's how these types of APIs are supposed to be typed.)
/cc @azizhk

Workbox event types

---

packages/workbox-window/src/Workbox.ts
test/workbox-window/window/test-Workbox.mjs

Fixes #2130
This PR introduces an `update` method on the `Workbox` instance in order to check for updates after the page has loaded. This is useful for long running applications that are seldom closed (e.g. mail applications) and where you need to check for updates on regular time interval.

feat: workbox-window method to trigger SW update check 

---

packages/workbox-webpack-plugin/src/lib/get-script-files-for-chunks.js
test/workbox-webpack-plugin/node/generate-sw.js

Fixes #2161
I think this is a reasonable restriction, and allowing developers to customize things to allow for non-`.js` extensions seems like overkill.
(`importScripts()` will never play nicely with ES modules, so `.mjs` is a non-issue.)

importScriptsViaChunks checks for .js extension

---

packages/workbox-webpack-plugin/src/generate-sw.js
test/workbox-webpack-plugin/node/generate-sw.js

Fixes #2158
The nuance about `emit` getting called multiple times on the same plugin instance was lost in the v5 rewrite. This makes sure that we don't modify the `this.config` member variable in our `emit` callback, allowing the callback to work when called multiple times via, e.g., `webpack-dev-server`.

Fix for multiple compilations/webpack-dev-server

---

test/workbox-google-analytics/integration/test-all.js

Fixes #2168
I'm not super-familiar with this test, but I could plausibly see how sending both of the GA events back-to-back could cause the replay order to get out of whack. So I'm taking the coward's way out and adding a short timeout in between each.

Reduce GA integration test flakiness

---

packages/workbox-precaching/src/PrecacheController.ts
test/workbox-precaching/integration/test-precache-and-update.js
test/workbox-precaching/sw/test-PrecacheController.mjs

Fixes #2146
This PR sets `cache: 'reload'` as an alternative to using the `__WB_REVISION=...` URL query parameter on the outgoing network requests used to populate the precache.
I also renamed some variables to clarify the distinction between `cacheKey` & `url` within the `install()` method.
The underlying precache keys still use the `__WB_REVISION=...` query parameters, as we continue to use those parameters as versioning metadata.
There's a slight breaking change in the `updatedURLs` & `notUpdatedURLs` values that are returned by `install()`: the previously would include `__WB_REVISION` query parameters, and now they won't. Since those return values are only used for logging/display purposes, this change is probably an improvement.

Set cache: 'reload' on precaching requests

---

packages/workbox-core/src/types.ts
packages/workbox-routing/src/NavigationRoute.ts
packages/workbox-routing/src/RegExpRoute.ts
packages/workbox-routing/src/Route.ts
packages/workbox-routing/src/Router.ts
packages/workbox-routing/src/_types.ts
packages/workbox-routing/src/registerRoute.ts
packages/workbox-routing/src/setCatchHandler.ts
packages/workbox-routing/src/setDefaultHandler.ts
packages/workbox-routing/src/utils/normalizeHandler.ts
packages/workbox-strategies/src/CacheFirst.ts
packages/workbox-strategies/src/CacheOnly.ts
packages/workbox-strategies/src/NetworkFirst.ts
packages/workbox-strategies/src/NetworkOnly.ts
packages/workbox-strategies/src/StaleWhileRevalidate.ts

Fixes #2171, fixes #2180.
The were several places in the existing `workbox-routing` code where our type definitions claim to only accept `HandlerCallback`, but in reality we accept `Handler | HandlerCallback`.
Instead of adding both types everywhere, I opted to renamed the old `Handler` type to `HandlerObject`, and then re-add `Handler` as `HandlerObject | HandlerCallback` (since that's what's exposed to most public APIs).
The end result was about the same about of code/changes, but I think calling it `HandlerObject` (or `RouteHandlerObject` in the core) is a bit more explicit.

Add a RouteHandlerObject type

---

test/workbox-window/integration/test-all.js

Fixes #2150
Just a hunch that ignoring this error might work around what appears to be a timing problem in Travis CI. (I can't reproduce it locally.)

Ignore NoSuchWindowError in workbox-window test

---

packages/workbox-window/src/utils/WorkboxEvent.ts

Fixes #2199 
Should I add externalredundant as well? I don't think that exists right?

Add redundant to WorkboxLifecycleEventMap

---

test/workbox-window/window/test-Workbox.mjs

Fixes #2213
This PR fixes the incorrect test logic in #2213 and adds more comprehensive tests in general around the `update()` method (handling both own and external updates).

Fix incorrect Workbox#update() test logic

---

packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js

Fixes #2194
The code in question should be safe to skip if the condition is false.

Guard against undefined reference in webpack plugin

---

packages/workbox-strategies/src/StaleWhileRevalidate.ts

(This is not an actual issue fix, it's a typo fix. I think creating issue would be redundant.)
Fixes typo in StaleWhileRevalidate docs.

[workbox-strategies] Fix StaleWhileRevalidate docs

---

packages/workbox-build/src/lib/write-sw-using-default-template.js
test/workbox-build/node/lib/write-sw-using-default-template.js

I came across this issue when manually testing v5 using a config like:
```
module.exports = {
globDirectory: 'public',
swDest: 'public/service-worker.js',
};
```
Prior to this change, the code would attempt to write the generated service worker to `public/public/service-worker.js`, because the filenames returned from Rollup would already include the `public/` prefix.
(The original test unfortunately did not catch this because the wrong assumption was made when stubbing out Rollup's behavior.)

Don't double-prepend the output dir

---

packages/workbox-precaching/src/PrecacheController.ts
test/workbox-precaching/sw/test-PrecacheController.mjs

I was revisiting the changes in #2176, and realized that one unintended consequence was that if the HTTP cache contained a valid entry for a URL that could be safely read from the cache (i.e. there's no `revision` field for the precache manifest entry), the precaching  request would still go to the network.
While this is "safe", it's less efficient.
This change accounts for that, and will set `cache: 'default'` for those requests that could be safely satisfied by the HTTP cache,  with `cache: 'reload'` still being set for requests that should always ignore the cache and go against the network.

Use cache: default for precaching requests when it's safe to

---

packages/workbox-build/src/generate-sw.js
packages/workbox-build/src/inject-manifest.js
packages/workbox-build/src/lib/get-file-manifest-entries.js
packages/workbox-build/src/lib/rebase-path.js
test/workbox-build/node/generate-sw.js
test/workbox-build/node/inject-manifest.js

Fixes #2229
We previously had some code that ensured that `swDest` was omitted from the `glob` matches when generating the precache manifest.
This extends that to also ignore `swSrc` in `injectManifest` mode.
I also improved the that generates the `globIgnores` value so that instead of just matching anything that has the same basename as `swSrc`/`swDest`, it actually uses a full path to the file, relative to `globDirectory`. This should reduce the chance of a false positive.

Ignore both swSrc and swDest when globbing for the manifest

---

packages/workbox-build/src/inject-manifest.js
packages/workbox-build/src/lib/errors.js
test/workbox-build/node/inject-manifest.js

Fixes #2230
This allows for a use case that's likely to become more common when folks bundle their own SW and then use our build tools to run `injectManifest`.

Allow the same swSrc and swDest in injectManifest

---

packages/workbox-background-sync/src/_version.ts
packages/workbox-background-sync/src/lib/QueueStore.ts
packages/workbox-broadcast-update/src/_version.ts
packages/workbox-build/src/cdn-details.json
packages/workbox-cacheable-response/src/_version.ts
packages/workbox-core/src/_private/DBWrapper.ts
packages/workbox-core/src/_private/Deferred.ts
packages/workbox-core/src/_version.ts
packages/workbox-expiration/src/_version.ts
packages/workbox-expiration/src/models/CacheTimestampsModel.ts
packages/workbox-google-analytics/src/_version.ts
packages/workbox-navigation-preload/src/_version.ts
packages/workbox-precaching/src/_version.ts
packages/workbox-range-requests/src/_version.ts
packages/workbox-routing/src/Router.ts
packages/workbox-routing/src/_version.ts
packages/workbox-strategies/src/_version.ts
packages/workbox-streams/src/_version.ts
packages/workbox-streams/src/concatenate.ts
packages/workbox-sw/_version.mjs
packages/workbox-window/src/Workbox.ts
packages/workbox-window/src/_version.ts
packages/workbox-window/src/utils/WorkboxEvent.ts
tsconfig.json

This adds `strictPropertyInitialization` checks to our TypeScript setup, and fixes the associated problems by throwing in a lot of `?` next to the properties that aren't explicitly initialized in the constructor, and the `!` next to the instances where those properties are used.
I think that's safe, but please double-check.

strictPropertyInitialization + fixes

---

packages/workbox-broadcast-update/src/BroadcastCacheUpdate.ts
packages/workbox-core/src/_private/DBWrapper.ts
packages/workbox-core/src/_private/cacheWrapper.ts
packages/workbox-core/src/_private/fetchWrapper.ts
packages/workbox-core/src/types.ts
packages/workbox-precaching/src/cleanupOutdatedCaches.ts
packages/workbox-precaching/src/precache.ts
packages/workbox-precaching/src/utils/addFetchListener.ts
packages/workbox-routing/src/Router.ts
packages/workbox-window/src/utils/WorkboxEventTarget.ts
tsconfig.json

Fixes #2242 
This cleans up a number of problems that were found by switching to using `strict: true` in the TypeScript compiler options.
There are some... questionable?... casts going on, so I'll address them via comments on the specific lines to see whether there are better approaches.

Strict TypeScript cleanup

---

packages/workbox-webpack-plugin/src/inject-manifest.js
packages/workbox-webpack-plugin/src/lib/get-sourcemap-asset-name.js
test/workbox-webpack-plugin/node/inject-manifest.js
test/workbox-webpack-plugin/static/sw-src-missing-sourcemap.js

Fixes #2250
Treating a failure to find the sourcemap in the webpack compilation as a fatal error is problematic (since it's possible for invalid sourcemap URLs to make it into the `swSrc` asset), so this relaxes that requirement.

Don't treat lack of sourcemap asset as a fatal error

---

packages/workbox-core/src/index.ts

Fixes #2252 
This PR exports all public TypeScript types directly from `workbox-core`, so developers can import them without needing sub-package references.
It also keeps all the types defined in a single `types.ts` file at the root level, so developers wanting to make it clear in their source code what is a type and what is a part of the API can do something like this:
```js
import {somePublicMethod} from 'workbox-core';
import {SomeTypeDefinition} from 'workbox-core/types';
```

Export all public types directly from workbox-core

---

infra/testing/validator/service-worker-runtime.js
packages/workbox-build/src/templates/sw-template.js
packages/workbox-core/src/models/messages/messages.ts
packages/workbox-precaching/src/PrecacheController.ts
packages/workbox-precaching/src/createHandler.ts
packages/workbox-precaching/src/createHandlerBoundToURL.ts
packages/workbox-precaching/src/index.ts
packages/workbox-precaching/src/matchPrecache.ts
test/workbox-build/node/generate-sw.js
test/workbox-precaching/sw/test-createHandler.mjs
test/workbox-precaching/sw/test-createHandlerBoundToURL.mjs
test/workbox-precaching/sw/test-matchPrecache.mjs

Fixes #2249
Exposes three new functions:
- `async function matchPrecache(request: string|Request): Promise<Response|null>`
- `function createHandler(fallbackToNetwork = true): RouteHandlerCallback`
- `function createHandlerBoundToURL(url: string, fallbackToNetwork = true): RouteHandlerCallback`
`createHandlerBoundToURL` replaces `createHandlerForURL`, and serves the same purpose.

New precache helper functions + removal of createHandlerForURL

---

packages/workbox-core/src/_private/cacheNames.ts

Don't assume that whenever `workbox-core` is imported, `registration` will be set.

registration existence check in workbox-core

---

packages/workbox-build/src/lib/additional-manifest-entries-transform.js
packages/workbox-build/src/lib/errors.js
packages/workbox-precaching/src/PrecacheController.ts
test/all/node/test-prod-builds.mjs
test/workbox-build/node/lib/additional-manifest-entries-transform.js
test/workbox-precaching/sw/test-PrecacheController.mjs

Fixes #2259
Let me know if it's too verbose.
The https://bit.ly/wb-precache link goes to https://developers.google.com/web/tools/workbox/modules/workbox-precaching#explanation_of_the_precache_list right now, which needs to be rewritten a to provide full context about what the problem is and what we want developers to do.
But I think that's the most reasonable place to link to that exists in our docs,  unless we wanted to create a dedicated landing page that elaborated on the topic.

Unrevisioned precaching warning

---

packages/workbox-webpack-plugin/src/inject-manifest.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes #2263
I could go down a rabbit hole a bit with either pre-escaping `'` characters in the manifest, or throwing an error when there are `'` characters there for some reason, but I think it would be sufficiently difficult to end up with a `'` organically in your manifest URLs that I'm not sure it's worth it.

Replace " with ' when stringifying the manifest

---

packages/workbox-routing/src/Router.ts

Fixes #1732 
The log message didn't add a ton of value anyway, and this should work around [the bug in Safari](https://bugs.webkit.org/show_bug.cgi?id=203617).

Don't log the request object in the router

---

packages/workbox-core/src/_private/cacheWrapper.ts
packages/workbox-core/src/clientsClaim.ts
packages/workbox-core/src/skipWaiting.ts
packages/workbox-expiration/src/CacheExpiration.ts
packages/workbox-expiration/src/ExpirationPlugin.ts
packages/workbox-precaching/src/PrecacheController.ts
packages/workbox-precaching/src/cleanupOutdatedCaches.ts
packages/workbox-precaching/src/precache.ts
packages/workbox-precaching/src/utils/addFetchListener.ts
packages/workbox-precaching/src/utils/deleteOutdatedCaches.ts
packages/workbox-window/src/Workbox.ts

There are a few instances where using the implicit global (`window` or `self`) was making JS Compiler with a specific set of `externs` unhappy.

Adds in explicit self/window in a few places

---

packages/workbox-build/package-lock.json
packages/workbox-build/package.json

Upgrade strip-comments to 2.0.1 from 1.0.2
This upgrade will remove dependency to core-js annoying ads.

Upgrade strip-comments to 2.0.1 from 1.0.2

---

packages/workbox-precaching/src/PrecacheController.ts
test/workbox-precaching/sw/test-PrecacheController.mjs

Fixes #2285 
When we made all of the standard  plugins `async`, we forgot add in an `await` inside of the `PrecacheController.install()` method.

Await an async cacheWillUpdate in PrecacheController.install()

---

packages/workbox-core/src/_private/logger.ts

We need this extra declaration because `workbox-core`'s `logger` can be used in the `window` context as well.

window.__WB_DISABLE_DEV_LOGS  declaration

---

gulp-tasks/build-browser-packages.js
gulp-tasks/build-packages.js
gulp-tasks/build-window-packages.js
gulp-tasks/build.js
gulp-tasks/transpile-typescript.js
gulp-tasks/utils/version-module.js
package-lock.json
package.json

Fixes #2291, fixes #2290
This PR updates the ordering for the  `version-module` and `transpile-typescript` tasks, to ensure versioning always happens before transpiling.
It also adds a `version` script (`"version": "git add -A packages"`) to the root level `package.json`, which is run as part of the `lerna version` lifecycle and happens during publish.
I've tested this locally and with these changes the version strings correctly appear in the version update commit, so we won't have to make a separate commit to update versions.

Publish version

---

packages/workbox-core/src/_private/logger.ts

CC: @westonruter
See https://github.com/GoogleChrome/workbox/pull/2284#issuecomment-560470923
Unfortunately, I can't think of a great way to test this, given that by the time our test suite executes, the `logger` IIFE will have already executed.

Don't overwrite __WB_DISABLE_DEV_LOGS

---

packages/workbox-build/package-lock.json
packages/workbox-build/package.json

Fixes #2297, as we want to keep Node v8.0.0 compatibility for now.

Downgrade strip-comments

---

packages/workbox-core/src/types.ts
packages/workbox-precaching/src/PrecacheController.ts
packages/workbox-strategies/src/CacheFirst.ts
packages/workbox-strategies/src/CacheOnly.ts
packages/workbox-strategies/src/NetworkFirst.ts
packages/workbox-strategies/src/NetworkOnly.ts
packages/workbox-strategies/src/StaleWhileRevalidate.ts
test/workbox-strategies/sw/test-CacheFirst.mjs
test/workbox-strategies/sw/test-CacheOnly.mjs
test/workbox-strategies/sw/test-NetworkFirst.mjs
test/workbox-strategies/sw/test-NetworkOnly.mjs
test/workbox-strategies/sw/test-StaleWhileRevalidate.mjs

As mentioned when we were going through the v5 changes, it makes sense to support passing in a string request to `handle()` in the various strategies, to match the interface supported by `makeRequest()`.

String support in handle()

---

packages/workbox-build/src/inject-manifest.js
test/workbox-build/node/inject-manifest.js

Just a small thing that bugged me when I looked at the logged output from `injectManifest`.

Absolute paths in injectManifest's filePaths return value

---

packages/workbox-build/src/lib/no-revision-for-urls-matching-transform.js
packages/workbox-build/src/lib/transform-manifest.js
test/workbox-build/node/lib/no-revision-for-urls-matching-transform.js
test/workbox-build/node/lib/transform-manifest.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

This is needed to avoid a warning message due to a missing `revision` field, introduced in one of the earlier RCs.
See https://github.com/GoogleChrome/workbox/issues/2259#issuecomment-573281342

Set revision: null instead of deleting revision

---

gulp-tasks/publish-lerna.js

This PR adds the `--force-publish` to our lerna publish task, which is needed to make sure all packages are bumped, regardless of whether they had changes or not. This was not necessary before because we were manually adding commits to all packages with new version details (thus there were always changes), but we're not doing that anymore.
The PR also removes the `--dist-tag=next` line, since we no longer plan on publishing v5 prereleases.

Update publish-lerna to include all packages

---

gulp-tasks/build.js

This PR updates the `gulp build:update-cdn-details` task to use the version from `workbox-build` rather than from `lerna.json` in the root directory. This issue appears to be that the `lerna version` lifecycle will update each package's version and run it's `version` npm script, and then it will update `lerna.json` last.
Since we need the version it's updating to in this task, it's better to get the version from `workbox-build`'s `package.json` file.

Fix the update-cdn-details task

---

infra/testing/validator/service-worker-runtime.js
package-lock.json
package.json
test/workbox-build/node/generate-sw.js
test/workbox-build/node/inject-manifest.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

Fixes #2362 
This moves from hardcoded hashes in our validation to special string constants, like `20_CHARACTER_HASH`.
It allows use to move from a pinned version of `webpack` that our tests needed to be run against to using whatever the latest version is. It should also help with re-enabling our Windows tests, which tended to generate different hashes.

Loosen the hash validation in our integration tests

---

packages/workbox-core/src/_private/getFriendlyURL.ts
test/workbox-core/sw/_private/test-getFriendlyURL.mjs

Fixes #2323 by including the `hash` portion of a URL in our log messages.

Include the hash in our "friendly" URL logging

---

packages/workbox-core/src/_private/Deferred.ts
packages/workbox-streams/src/concatenate.ts
packages/workbox-window/src/Workbox.ts

This PR updates the `Deferred` types and then any consumers of that class via `eslint --fix`.

Fix Deferred type and run lint fix

---

.github/workflows/pull-request.yml
infra/testing/validator/service-worker-runtime.js
package-lock.json
package.json
test/workbox-build/node/generate-sw.js
test/workbox-build/node/get-manifest.js
test/workbox-build/node/inject-manifest.js
test/workbox-webpack-plugin/node/generate-sw.js
test/workbox-webpack-plugin/node/inject-manifest.js

This re-enables Windows testing of the `node` modules on GitHub Actions (not the SW runtime), which has historically been a source of bugs due to path separator differences.
It also cleans up some of the logic in place around validating hashes, switching to regexes and the `chai-match-pattern` library.
Fixes #2288

Enable Windows tests on GH Actions

---

packages/workbox-webpack-plugin/src/inject-manifest.js
packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js

I had always felt guilty about using the package subpaths, and didn't realize that official exports existed for those bits of the `webpack` internals we need. I checked back to the `webpack` v4.0.0 release (what we specify in our `peerDependencies`) and they're both supported there.
This may fix #2385? I'm not entirely sure. But it's a good idea to switch over anyway.

Switch to official webpack exports

---

packages/workbox-build/src/options/defaults.js
packages/workbox-build/src/options/schema/webpack-inject-manifest.js
packages/workbox-webpack-plugin/src/inject-manifest.js
test/workbox-webpack-plugin/node/inject-manifest.js
test/workbox-webpack-plugin/static/injected-manifest.js
test/workbox-webpack-plugin/static/injected-manifest.json

CC: @bailnl
Fixes #2383
When `compileSrc` is set to `false`, the `swSrc` file won't be run through the `webpack` compilation process. That allows for the use case described in #2383, where the manifest ends up injected into an arbitrary file that might not be something that should be processed by `webpack`.
The default behavior has not changed.

Add compileSrc option to InjectManifet webpack plugin

---

packages/workbox-build/package-lock.json
packages/workbox-build/package.json
test/all/node/test-yarn-installation.js

Fixes #2412 
This adds a new test that tries to install our three `node` packages using `yarn`. `yarn` is stricter about `engines` versioning than `npm` is, so this will presumably catch some things that we wouldn't notice normally from just using `npm`.
This also reverts the version of `strip-comments` used by `workbox-build` to one that's compatible with `node` v8.
(The Windows CI test suite currently uses the latest version of `node`, but the OS X test suite uses `node` v8.)

Add test of yarn installation

---

packages/workbox-build/src/get-manifest.js

Fixes #2422
This was a copy/paste error in the JSDoc.

Correct the workbox-build's getManifest() JSDoc

---

packages/workbox-routing/src/_types.ts

Prompted by https://github.com/GoogleChrome/workbox/issues/2439, I found a discrepancy in our `handlerCallback` JSDocs and TypeScript definition: https://github.com/GoogleChrome/workbox/blob/3ac095656354157eb4b58c93d3b1e390a5ba34dd/packages/workbox-core/src/types.ts#L36-L56

handlerCallback JSDocs update

---

.github/workflows/pull-request.yml
package-lock.json
package.json

Swap node versions in our CI tests

---

gulp-tasks/transpile-typescript.js
infra/testing/helpers/extendable-event-utils.mjs
infra/testing/server/routes/sw-bundle.js
infra/testing/server/routes/test-sw.js
infra/testing/server/routes/test-window.js
infra/testing/server/templates/test-sw-runner.js.njk

This PR fixes a few long-standing annoyance of mine:
- There was no easy way to just run one (or a few) tests.
- If a TypeScript compile or Rollup error occurred, you would need to restart the test server in order to refresh and rerun the tests.
- Dev logging made it hard to see the test output.
Now, when running the SW or window tests in the browser, you can append `?filter=` and pass a test glob, where the default is `**/test-*`. For example, if you wanted to just test the `CacheFirst` and `CacheOnly` strategies you could visit: `http://localhost:3004/test/workbox-strategies/sw/?filter=test-Cache*`

Add test filters for selective test running

---

infra/testing/confirm-directory-contains.js
test/workbox-build/node/generate-sw.js

I noticed while looking at our CI output that there are some test cases in the Windows suite that should have been failed, but passed because of a missing `await`:
https://github.com/GoogleChrome/workbox/pull/2451/checks?check_run_id=583425178#step:6:60
This PR adds that `await` to ensure that an exception in the `async` sub-function properly fails our main test case. It also fixes the logic so that the Windows tests should pass.
(They were failing because a Windows path separator isn't meant to be used in a `globby` pattern.)

Fixes unhandled rejections in Windows tests

---

packages/workbox-core/src/_private/assert.ts
packages/workbox-core/src/models/messages/messages.ts
packages/workbox-precaching/src/index.ts
test/workbox-core/sw/_private/test-assert.mjs
test/workbox-precaching/static/addToCacheList.html
test/workbox-precaching/static/precache.html

As discussed, this assertion makes it difficult to test the `workbox-precaching` class outside of the SW environment.
We don't have a similar assertions in any other module, so having it just for `workbox-precaching` is hard to justify.

Remove the isSWEnv assertion

---

.github/workflows/pull-request.yml

This PR update the `Full_Suite_Mac` job in pull request GitHub action to use Node 12, as experimental Node 13 changes were causing breakage.

Update GitHub actions to use Node 12

---

packages/workbox-core/src/models/messages/messages.ts

I was getting this message on a workbox build. Notice the duplicate 'is'. 

Update message to remove duplicate `is`

---

packages/workbox-build/src/get-manifest.js
packages/workbox-build/src/inject-manifest.js
packages/workbox-build/src/options/partials/base.js
packages/workbox-build/src/options/partials/generate.js
packages/workbox-build/src/options/partials/webpack.js
test/workbox-build/node/get-manifest.js
test/workbox-build/node/inject-manifest.js

Fixes #2427
`mode` wasn't intended to be supported for either `workbox-build`'s `injectManifest` or `getManifest` methods, but it was included due to some copy-paste errors when putting together v5.
This removes it form the JSDocs and will cause validation to fail if it's included in your config.

Don't list mode as supported for injectManifest or getManifest

---

.github/workflows/pull-request.yml
gulp-tasks/utils/build-node-package.js
package.json
packages/workbox-build/package.json
packages/workbox-cli/package.json
packages/workbox-webpack-plugin/package.json

This switches to `node` v10 as the minimum required version in our packages' `engines` field, and changes the `preset-env` target to 10 as well.
Fixes #2445

Switch the minimum supported node version to 10

---

gulp-tasks/test-integration.js

This disables Chrome Canary tests (for the `v6` branch), as they're all failing right now due to a versioning issue with https://www.npmjs.com/package/chromedriver
We can re-enable when that's cleared up.

Disable Chrome Canary tests.
