.gitignore, .travis.yml
R: @gauntface @wibblymat @addyosmani 
Based on the Travis CI setup that's [being used for `sw-toolbox`](https://github.com/GoogleChrome/sw-toolbox/blob/master/.travis.yml).
Fixes #6
=> Initial Travis CI config

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
R: @addyosmani @wibblymat @gauntface 
Fixes #3
This adds (bare-bones) issue and PR templates, as per https://github.com/blog/2111-issue-and-pull-request-templates
=> Basic Issue and PR templates

projects/sw-offline-google-analytics/src/lib/enqueue-request.js
Just some small cruft that was left behind while I was experimenting.
=> Removes a debugging statement

projects/sw-offline-google-analytics/src/lib/replay-queued-requests.js
R: @jeffposnick @addyosmani @wibblymat @gauntface
The [`qt`](https://devsite.googleplex.com/analytics/devguides/collection/protocol/v1/parameters#qt) param for the Measurement Protocol accepts a time offset, not a timestamp. Unfortunately this means hits replayed by the current version of this library are most likely being discarded (sorry for not catching this in my initial review).
=> Fix the qt param to use offset time

projects/sw-appcache-behavior/src/appcache-behavior-import.js
Merging with self-review, since this is so minor.
=> Removes another stray console.log()

packages/sw-broadcast-cache-update/package.json, packages/sw-cache-expiration/package.json, packages/sw-precaching/package.json, packages/sw-routing/package.json, packages/sw-runtime-caching/package.json
=> Standardize the naming of the build output.

packages/sw-lib/build.js, packages/sw-lib/src/lib/error-factory.js, packages/sw-lib/src/lib/sw-lib.js, packages/sw-lib/test/automated-test-suite.js, packages/sw-lib/test/browser-unit/cache-revisioned-e2e.js, packages/sw-lib/test/browser-unit/data/sw/cache-revisioned-1.js, packages/sw-lib/test/browser-unit/data/sw/cache-revisioned-2.js, packages/sw-lib/test/browser-unit/data/test-data.js, packages/sw-lib/test/browser-unit/index.html, packages/sw-lib/test/browser-unit/library-namespace.js, packages/sw-lib/test/browser-unit/sw-unit/cache-revisioned-assets.js, templates/README.hbs, utils/test-server.js
Adds cacheRevisionedAssets to swlib.
=> sw-lib precache

packages/sw-cli/.eslintrc, packages/sw-cli/build.js, packages/sw-cli/package.json, packages/sw-cli/src/bin/index.js, packages/sw-cli/src/cli/cli-help.txt, packages/sw-cli/src/cli/index.js, packages/sw-cli/src/index.js, packages/sw-cli/src/lib/log-helper.js, packages/sw-cli/test/.eslintrc, packages/sw-cli/test/cli-flags.js, utils/server-instance.js
Super early and small PR for the CLI / Module piece. Has no logic other than showing help / version text. But comments on general structure and testing approach would be appreciated.
=> Adding the start of a CLI tool. No logic at the moment

packages/sw-precaching/src/lib/models/precache-entries/base-precache-entry.js, packages/sw-precaching/test/browser-unit/cache-testing.js, packages/sw-precaching/test/browser-unit/data/response-types/redirect-revisioned-sw.js, packages/sw-precaching/test/browser-unit/data/response-types/redirect-unrevisioned-sw.js, packages/sw-precaching/test/browser-unit/data/test-data.js, packages/sw-precaching/test/browser-unit/register-sw-tests.js, utils/server-instance.js
This adds redirects for testing the sw-precache.
=> Adding test for redirects in sw-precaching

packages/sw-cli/src/cli/index.js, packages/sw-cli/src/lib/errors.js, packages/sw-cli/test/cli-file-manifest-name.js, packages/sw-cli/test/cli-sw-name.js
Any chance of some eyes on this. (apologies for the PR spam, but trying to keep the PR's small)
=> Adding Manifest Name and SW Name Questions

packages/sw-lib/src/lib/sw-lib.js, packages/sw-lib/test/browser-unit/cache-unrevisioned-e2e.js, packages/sw-lib/test/browser-unit/data/sw/cache-revisioned-1.js, packages/sw-lib/test/browser-unit/data/sw/cache-unrevisioned-1.js, packages/sw-lib/test/browser-unit/data/sw/cache-unrevisioned-2.js, packages/sw-lib/test/browser-unit/data/test-data.js, packages/sw-lib/test/browser-unit/index.html
This properly hooks up the warmRuntimeCache method up to the unrevisioned cache asset method.
=> hooking up warm runtime to swlib

packages/sw-background-sync-queue/test/unit/index.html, packages/sw-lib/src/lib/sw-lib.js, packages/sw-lib/test/browser-unit/index.html, packages/sw-lib/test/browser-unit/library-namespace.js, packages/sw-lib/test/browser-unit/sw-unit/caching-strategies.js, packages/sw-offline-google-analytics/test/unit/index.html
Fixes #113
Adds strategies to sw-lib.
=> Sw lib strategies

package.json, packages/sw-cli/src/cli/index.js
Notify user of new CLI versions.
=> Address comment in #82 - update user of new versions

docs/contributing.md
=> Adding contribution guidelines

.travis.yml, packages/sw-precaching/package.json, packages/sw-precaching/src/lib/controllers/base-cache-manager.js, packages/sw-precaching/src/lib/precache-manager.js, packages/sw-precaching/test/automated-test-suite.js, packages/sw-precaching/test/browser-unit/sw-unit/basic.js, packages/sw-precaching/test/routing-demo/example.html, packages/sw-precaching/test/routing-demo/index.html, packages/sw-precaching/test/routing-demo/sw.js, packages/sw-precaching/test/routing-example.js, utils/server-instance.js
Fixes #136
This makes the cache name and cached assets available so Routes can be easily added for precaching.
=> Adding ability to define routes for precached assets

packages/sw-broadcast-cache-update/src/index.js, packages/sw-broadcast-cache-update/src/lib/behavior.js, packages/sw-broadcast-cache-update/src/lib/broadcast-update.js, packages/sw-broadcast-cache-update/src/lib/constants.js, packages/sw-broadcast-cache-update/src/lib/responses-are-same.js
R: @jeffposnick @addyosmani @jpmedley 
I just started to step through the docs to clean up npm-publish-script problems / errors in the jsdoc theme, but in the process fixed up a few quirks / lacking pieces in the docs.
=> Updating broadcast-cache-update docs

packages/sw-cache-expiration/src/index.js, packages/sw-cache-expiration/src/lib/behavior.js, packages/sw-cli/src/cli/index.js
Another batch of minor tweaks.
=> Cache expiration docs

gulp-tasks/test.js, packages/sw-cli/package.json, packages/sw-cli/src/cli/index.js, packages/sw-cli/test/extensions-glob-pattern.js
Fixes #166 
Handles the case where there is only one file extension to add to glob.
=> Glob pattern

.travis.yml, appveyor.yml, package.json, packages/sw-cli/package.json, packages/sw-cli/src/cli/index.js, packages/sw-cli/src/lib/errors.js, packages/sw-cli/src/lib/templates/sw.js.tmpl, packages/sw-cli/test/.eslintrc, packages/sw-cli/test/build-service-worker.js, packages/sw-cli/test/copy-sw-lib.js, packages/sw-cli/test/end-to-end.js, packages/sw-cli/test/example-projects/example-1/index.html
This is a super basic, bare bones implementation of service worker generation.
=> CLI - Generate sw

package.json, packages/sw-precaching/src/lib/constants.js, packages/sw-precaching/src/lib/controllers/base-cache-manager.js, packages/sw-precaching/src/lib/controllers/unrevisioned-cache-manager.js, packages/sw-precaching/test/browser-unit/cache-testing.js, packages/sw-precaching/test/browser-unit/data/response-types/cookie-revisioned-sw.js, packages/sw-precaching/test/browser-unit/data/response-types/cookie-unrevisioned-sw.js, packages/sw-precaching/test/browser-unit/data/test-data.js, packages/sw-runtime-caching/src/lib/constants.js, utils/server-instance.js
This is a step towards #145 although I need to spend a little more time thinking about best approach for cache names
=> Moves sw-precaching over to using requestWrapper

packages/sw-cacheable-response-behavior/src/index.js, packages/sw-cacheable-response-behavior/src/lib/behavior.js
=> Adding moar docs - this time for cachable-response-behavior

packages/sw-lib/src/index.js, packages/sw-lib/src/lib/router.js, packages/sw-lib/src/lib/sw-lib.js
This is a big set tweaks to docs for sw-lib but will hopefully be a bit easier to follow for readers.
=> Sw lib docs

packages/sw-runtime-caching/src/index.js, packages/sw-runtime-caching/src/lib/cache-first.js, packages/sw-runtime-caching/src/lib/cache-only.js, packages/sw-runtime-caching/src/lib/constants.js, packages/sw-runtime-caching/src/lib/handler.js, packages/sw-runtime-caching/src/lib/network-first.js, packages/sw-runtime-caching/src/lib/network-only.js, packages/sw-runtime-caching/src/lib/request-wrapper.js, packages/sw-runtime-caching/src/lib/stale-while-revalidate.js
Nearly done with a rough pass over all the docs.
JEFFFFFF Please note that I changes an 'await fetch().catch()' to a try {} catch (err) {} statement. Can you double check this is correct or am I missing a feature of await that means .catch will still work / acts differently to try and catch?
=> Updating sw-runtime docs

README.md, packages/sw-background-sync-queue/README.md, packages/sw-background-sync-queue/package.json, packages/sw-background-sync-queue/src/index.js, packages/sw-broadcast-cache-update/src/index.js, packages/sw-cache-expiration/src/index.js, packages/sw-cacheable-response-behavior/src/index.js, packages/sw-lib/src/index.js, packages/sw-precaching/src/index.js, packages/sw-routing/src/index.js, packages/sw-routing/src/lib/constants.js, packages/sw-routing/src/lib/express-route.js, packages/sw-routing/src/lib/regexp-route.js, packages/sw-routing/src/lib/route.js, packages/sw-routing/src/lib/router.js
=> Adding Titles of Modules and sw-routing docs

gulp-tasks/build.js, gulp-tasks/documentation.js, gulp-tasks/lint.js, packages/sw-appcache-behavior/build.js, packages/sw-background-sync-queue/build.js, packages/sw-broadcast-cache-update/build.js, packages/sw-cache-expiration/build.js, packages/sw-cacheable-response-behavior/build.js, packages/sw-cli/build.js, packages/sw-lib/build.js, packages/sw-offline-google-analytics/build.js, packages/sw-precaching/build.js, packages/sw-routing/build.js, packages/sw-runtime-caching/build.js, utils/build.js
=> Moves build-utils.js to build/utils.js

packages/sw-broadcast-cache-update/src/index.js, packages/sw-broadcast-cache-update/src/lib/behavior.js, packages/sw-broadcast-cache-update/src/lib/error-factory.js, packages/sw-broadcast-cache-update/src/lib/responses-are-same.js, packages/sw-broadcast-cache-update/test/.eslintrc, packages/sw-broadcast-cache-update/test/automated-test-suite.js, packages/sw-broadcast-cache-update/test/browser/index.html, packages/sw-broadcast-cache-update/test/browser/register-unit-tests.js, packages/sw-broadcast-cache-update/test/sw/behavior.js, packages/sw-broadcast-cache-update/test/sw/broadcast-update.js, packages/sw-broadcast-cache-update/test/sw/namespace.js, packages/sw-broadcast-cache-update/test/sw/responses-are-same.js
=> Unit tests for sw-broadcast-cache-update

packages/sw-background-sync-queue/src/lib/response-manager.js, packages/sw-background-sync-queue/test/unit/index.html, packages/sw-background-sync-queue/test/unit/response-manager.js
This PR adds the missing tests for response manager.
=> adding missing tests

packages/sw-cache-expiration/src/index.js, packages/sw-cache-expiration/src/lib/error-factory.js, packages/sw-cache-expiration/src/lib/plugin.js, packages/sw-cache-expiration/test/.eslintrc, packages/sw-cache-expiration/test/automated-test-suite.js, packages/sw-cache-expiration/test/browser/register-unit-tests.js, packages/sw-cache-expiration/test/sw/plugin.js
Unit tests for `sw-cache-expiration`. There's also a bug fix for an issue I found in the underlying library (yay testing!) and I'm exposing a few additional symbols that could be useful.
The unit tests are fairly in depth, so I'm not sure that I'm going to prioritize writing end-to-end tests. The in-depth-ness also means that they're a little gnarly, so please feel free to push back if it's too unclear what's going on.
=> sw-cache-expiration unit tests

packages/sw-build/src/index.js
=> Fix a typo.

packages/sw-cli/package.json
=> Make sw-cli public

README.md, templates/README.hbs
=> Fixes Readme Appveyor Badge

README.md, packages/sw-build/README.md
=> Regenerate documentation.

README.md, gulp-tasks/documentation.js, packages/sw-build/README.md, packages/sw-cli/README.md, packages/sw-lib/README.md, packages/sw-precaching/README.md, templates/Project-README.hbs, templates/README.hbs
Fixes #272 
Only add demo links when there is a demo to link to.
=> Adding a change that will only add demos to readme's when they exist

packages/sw-broadcast-cache-update/demo/service-worker.js, packages/sw-cache-expiration/demo/service-worker.js, packages/sw-lib/demo/service-worker.js, packages/sw-precaching/demo/service-worker.js, packages/sw-routing/demo/service-worker.js, packages/sw-runtime-caching/demo/service-worker.js
=> Use the unminified versions of local libs for demos

packages/sw-routing/demo/service-worker.js, packages/sw-routing/src/lib/route.js, packages/sw-routing/test/static/route.js, packages/sw-routing/test/sw/route.js
=> Support for a function as a Route's handler

docs/getting-started/sw-lib.md
=> sw-lib: minor revisions to doc

.travis.yml, package.json
I had this left on my local branch - minor rename of npm run script.
=> Remove doc build (Not important)

README.md, templates/README.hbs
=> Enhance the README.

packages/sw-routing/src/lib/route.js
=> JSDoc's request.mode should check for 'navigate'

packages/sw-lib/src/lib/router.js
This should make it possible to use the proper router while keeping the sw-lib nicety.
=> Use actual Router for sw-lib

README.md, docs/index.md, gulp-tasks/documentation.js, package.json, packages/sw-build/README.md, packages/sw-lib/README.md, packages/sw-precaching/README.md, templates/README.hbs
=> Readme fixes

packages/sw-routing/src/lib/router.js, packages/sw-routing/test/sw/regexp-route.js
This adds logging to the router - this is largely to help with debugging routers :-/
=> Adding logging for router

docs/examples.md
=> Small modification to the Examples page.

README.md
Also updated Copyright date (hope that's right!)
=> Minor tweaks to README text

packages/sw-build/src/index.js
=> Fix example formatting

package.json, packages/sw-build/package.json, packages/sw-cli/package.json
Fixes #340 
This fixes the problem - but it raises a worrying concern with sw-build and sw-cli being tied to the top level dependencies.
=> Fixing sw-build -> package.json

docs/getting-started/sw-lib.md
=> Fix formatting of procedure.

packages/sw-lib/src/lib/router.js, packages/sw-lib/src/lib/sw-lib.js, packages/sw-lib/test/static/sw/navigation-route.js, packages/sw-routing/src/lib/navigation-route.js
=> Use a specific cache name when finding the NavigationRoute response

package.json, packages/sw-build/test/dependency-check.js, packages/sw-cli/package.json, packages/sw-cli/test/dependency-check.js
=> Adding dependency checks to sw build and cli

packages/sw-lib/src/index.js, packages/sw-lib/src/lib/sw-lib.js
=> Fixes #355

gulp-tasks/lint.js, packages/sw-build/src/lib/errors.js, packages/sw-build/src/lib/generate-file-manifest.js, packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/get-file-manifest-entries.js, packages/sw-build/src/lib/utils/write-file-manifest.js, packages/sw-build/test/generate-file-manifest.js, packages/sw-build/test/generate-sw.js, packages/sw-build/test/get-file-manifest-entries.js
Fixes #389
Adds a set of checks on the inputs to generateSW(). TBH the tests are sloppy after the number of moving pieces (i.e. a CLI + a module than a seperate module and CLI).
=> Build input check

packages/sw-background-sync-queue/src/lib/constants.js, packages/sw-background-sync-queue/src/lib/request-manager.js
Fixes #384
Adds another constant tag for replaying the queue
=> add replay tag in bg sync queue

packages/sw-build/src/index.js
Fixes #*[407](https://github.com/GoogleChrome/sw-helpers/issues/407)*
=> Add service worker to globIngores in example.

packages/sw-build/src/index.js
=> Correct two examples.

packages/sw-build/src/lib/errors.js, packages/sw-cli/src/index.js, packages/sw-cli/src/lib/errors.js, packages/sw-cli/src/lib/questions/ask-extensions-to-cache.js, packages/sw-cli/test/node/cli-file-extensions.js
Fixes #396
Fixing an undefined error message,
=> Fixing up the error message in sw-cli. Fixes #396

package.json, packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/write-sw.js, packages/sw-lib/src/lib/error-factory.js, packages/sw-lib/src/lib/sw-lib.js, packages/sw-lib/test/sw/claim-clients-false.js, packages/sw-lib/test/sw/claim-clients-true.js, packages/sw-lib/test/sw/claim-clients.js, utils/server-instance.js, utils/test-runner.js
Add clientsClaim option to sw-build and sw-lib.
=> Clients claim

packages/sw-lib/src/lib/router.js, packages/sw-lib/src/lib/sw-lib.js, packages/sw-routing/src/lib/router.js, packages/sw-routing/test/browser/end-to-end.js, packages/sw-routing/test/static/router-handle-fetch-false.js
Adds the handleFetch param to sw-routing.
=> Adds handleFetch param to sw-router

packages/sw-lib/src/lib/error-factory.js, packages/sw-lib/src/lib/strategies.js, packages/sw-lib/src/lib/sw-lib.js, packages/sw-lib/test/sw/directory-index-custom.js, packages/sw-lib/test/sw/directory-index-default.js, packages/sw-lib/test/sw/directory-index-false.js, packages/sw-lib/test/sw/directory-index.js, packages/sw-runtime-caching/src/lib/request-wrapper.js
Fixes #334
I had to add some additional parameters to the cacheWillMatch method (i.e. request parameter wasn't being set before).
=> Directory index

packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/write-sw.js, packages/sw-build/test/node/lib-write-sw.js
=> Adding skipWaiting to sw-build

packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/write-sw.js, packages/sw-build/test/node/lib-write-sw.js
Adds directoryIndex to sw-build.
=> Adding directory index to sw-build

packages/sw-background-sync-queue/demo/sw.js, packages/sw-background-sync-queue/src/lib/background-sync-queue.js, packages/sw-background-sync-queue/test/browser/background-sync-queue.js
This adds `replayAll` method to instances of backgroundSyncQueue
I have also added the same in example `sw.js`
=> adding replay All functionality

package.json
=> Bootstrap lerna in the top-level postinstall

packages/sw-background-sync-queue/src/index.js, packages/sw-background-sync-queue/src/lib/background-sync-queue.js, packages/sw-background-sync-queue/src/lib/response-manager.js, packages/sw-lib/src/lib/sw-lib.js
Makes the JSDoc valid for the docs.
=> Patching up the bg sync queue

packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/write-sw.js, packages/sw-build/test/node/lib-write-sw.js
=> Adds handleFetch to sw-build

docs/index.md
=> Fix links on landing page.

docs/recipes/cdn-caching.md
=> Make a code example more helpful.

package.json, packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/templates/sw.js.tmpl, packages/sw-build/src/lib/write-sw.js, packages/sw-build/test/node/lib-write-sw.js
=> Nav fallback

packages/sw-lib/src/lib/sw-lib.js
=> Add cacheableResponse to the strategies documentation.

package.json, packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/get-file-manifest-entries.js, packages/sw-build/src/lib/utils/filter-files.js, packages/sw-build/src/lib/utils/modify-url-prefix.js, packages/sw-build/test/node/generate-sw-e2e.js, packages/sw-build/test/node/get-file-manifest-entries.js, packages/sw-cli/test/utils/e2e-sw-validator.js
Adds Maximum file size config....
=> Max file size config

packages/sw-background-sync-queue/test/browser/background-sync-queue.js
Fixes #484 
Two of the async tests did not returned the promise back, which was failing the assertion.
=> fixing async tests

packages/sw-build/src/lib/errors.js, packages/sw-build/src/lib/get-file-manifest-entries.js, packages/sw-build/test/node/get-file-manifest-entries.js
- Adds some tests to templatedUrls
- Improves error messages
- Adds dynamicUrlToDependencies support
=> Dynamic url to deps

packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/templates/sw.js.tmpl, packages/sw-build/src/lib/write-sw.js, packages/sw-build/test/node/lib-write-sw.js
Adds navigate fallback whitelist.
=> Adds navigateFallbackWhitelist

docs/sw-lib.md
=> Fix sw-lib-docs

packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/get-file-manifest-entries.js, packages/sw-build/src/lib/utils/filter-files.js, packages/sw-build/test/node/get-file-manifest-entries.js
Adds dontCacheBustURLsMatching parameter
=> Dont cache bust urls

packages/sw-build/src/lib/errors.js, packages/sw-build/src/lib/generate-sw.js, packages/sw-build/src/lib/templates/sw.js.tmpl, packages/sw-build/src/lib/write-sw.js, packages/sw-build/test/node/generate-sw.js, packages/sw-build/test/node/lib-write-sw.js
=> Runtimecaching

docs/index.md, docs/sw-cli.md
=> Explains why the config file is useful.

docs/sw-lib.md
=> Mention that minifiers must be ES6 aware.

packages/sw-lib/src/lib/sw-lib.js, packages/sw-lib/test/browser/ignore-url-params.js, packages/sw-lib/test/static/sw/ignore-url-params-custom.js, packages/sw-lib/test/static/sw/ignore-url-params.js
This just adds the logic to sw-lib, will hook up with sw-build in a seperate PR.
@jeffposnick could you check my logic isn't crazy different from yours in sw-precache.
=> Adding ignoreUrlParamsMatching to sw-lib

docs/recipes/rollup.md
Update as per Jeff's comment in #241 
This is a prelude to doing what that ticket asks.
=> Update identifiers in recipe.

docs/recipes/rollup.md, docs/sw-cli.md, docs/sw-lib.md
=> Update some function calls and other misc. fixes.

.eslintrc, docs/sw-build.md, lib/log-group.js, lib/log-helper.js, packages/sw-build-webpack-plugin/index.js, packages/sw-build/demo/index.js, packages/sw-build/src/index.js, packages/sw-build/src/lib/errors.js, packages/sw-build/src/lib/generate-file-manifest.js, packages/sw-build/src/lib/generate-sw.js, packages/sw-build/test/node/generate-file-manifest.js, packages/sw-build/test/node/generate-sw-e2e.js, packages/sw-build/test/node/generate-sw.js, packages/sw-build/test/node/injection-manifest.js, packages/sw-build/test/node/lib-write-sw.js, packages/sw-cli/src/index.js, packages/sw-cli/test/node/generate-sw-e2e.js, packages/sw-cli/test/utils/e2e-sw-validator.js
Fixes #513
swDest and manifestDest
=> Fixes #513 - Destination Keys

README.md, package.json, packages/workbox-background-sync/README.md, packages/workbox-broadcast-cache-update/README.md, packages/workbox-broadcast-cache-update/package.json, packages/workbox-build/README.md, packages/workbox-cache-expiration/README.md, packages/workbox-cache-expiration/package.json, packages/workbox-cacheable-response/README.md, packages/workbox-cacheable-response/package.json, packages/workbox-cli/README.md, packages/workbox-cli/package.json, packages/workbox-google-analytics/README.md, packages/workbox-google-analytics/package.json, packages/workbox-precaching/README.md, packages/workbox-precaching/package.json, packages/workbox-routing/README.md, packages/workbox-routing/package.json, packages/workbox-routing/src/lib/regexp-route.js, packages/workbox-runtime-caching/README.md, packages/workbox-runtime-caching/package.json, packages/workbox-sw/README.md, packages/workbox-sw/package.json, packages/workbox-sw/src/lib/workbox-sw.js, templates/Project-README.hbs, templates/README.hbs
=> Renaming sw-helpers to workbox

packages/workbox-background-sync/src/index.js, packages/workbox-broadcast-cache-update/src/index.js, packages/workbox-build/src/index.js, packages/workbox-cache-expiration/src/index.js, packages/workbox-cacheable-response/src/index.js, packages/workbox-google-analytics/src/index.js, packages/workbox-precaching/src/index.js, packages/workbox-routing/src/index.js, packages/workbox-runtime-caching/src/index.js, packages/workbox-sw/src/index.js
R: @jeffposnick @addyosmani @gauntface 
This seems like the best way to get them into the micro site.
=> Add install instructions to JSDocs.

gulp-tasks/build.js, gulp-tasks/test.js, utils/server-instance.js
R: @gauntface
This properly clears out the environment in between test runs.
=> Fix the lerna-publish pipeline.

lib/log-helper.js, packages/workbox-background-sync/package.json, packages/workbox-build/package.json, packages/workbox-sw/src/lib/workbox-sw.js, packages/workbox-webpack-plugin/package.json
Some additional "goog" & "sw-helpers" renaming.
=> More goog -> workbox & sw-helpers -> workbox

packages/workbox-broadcast-cache-update/src/index.js, packages/workbox-broadcast-cache-update/src/lib/broadcast-cache-update-plugin.js, packages/workbox-broadcast-cache-update/src/lib/broadcast-cache-update.js, packages/workbox-broadcast-cache-update/src/lib/broadcast-update.js, packages/workbox-broadcast-cache-update/src/lib/constants.js, packages/workbox-broadcast-cache-update/src/lib/responses-are-same.js
=> Minor tweaks to workbox-broadcast-cache-update

packages/workbox-build/src/index.js, packages/workbox-build/src/lib/generate-file-manifest.js, packages/workbox-build/src/lib/generate-sw.js, packages/workbox-build/src/lib/get-file-manifest-entries.js, packages/workbox-build/src/lib/inject-manifest.js, packages/workbox-precaching/test/static/routing-demo/index.html
R: @jeffposnick @addyosmani @jpmedley
=> Sweep of sw-build

packages/workbox-broadcast-cache-update/src/index.js, packages/workbox-cache-expiration/src/index.js, packages/workbox-cache-expiration/src/lib/cache-expiration-plugin.js, packages/workbox-cache-expiration/src/lib/cache-expiration.js
@jeffposnick is the updateTimestamp() useful in CacheExpiration class? If so, is there something more useful we can include in the docs?
=> Minor tweaks to cache-expiration-docs

packages/workbox-runtime-caching/src/index.js, packages/workbox-runtime-caching/src/lib/cache-first.js, packages/workbox-runtime-caching/src/lib/cache-only.js, packages/workbox-runtime-caching/src/lib/constants.js, packages/workbox-runtime-caching/src/lib/handler.js, packages/workbox-runtime-caching/src/lib/network-first.js, packages/workbox-runtime-caching/src/lib/network-only.js, packages/workbox-runtime-caching/src/lib/request-wrapper.js, packages/workbox-runtime-caching/src/lib/stale-while-revalidate.js
R: @jeffposnick @addyosmani @jpmedley
=> runtime-caching-sweep

packages/workbox-background-sync/demo/index.html, packages/workbox-background-sync/demo/sw.js, packages/workbox-background-sync/src/index.js, packages/workbox-background-sync/src/lib/background-sync-queue-plugin.js, packages/workbox-background-sync/src/lib/background-sync-queue.js
This adds better documentation to background-sync
P.S. it breaks a lint which I am not sure how to fix
=> better docs

packages/workbox-routing/src/index.js, packages/workbox-routing/src/lib/express-route.js, packages/workbox-routing/src/lib/navigation-route.js, packages/workbox-routing/src/lib/normalize-handler.js, packages/workbox-routing/src/lib/regexp-route.js, packages/workbox-routing/src/lib/route.js, packages/workbox-routing/src/lib/router.js, packages/workbox-runtime-caching/src/index.js, packages/workbox-sw/src/lib/router.js
R: @jeffposnick @addyosmani @jpmedley
=> Routing sweep

packages/workbox-google-analytics/src/index.js
R: @jeffposnick @addyosmani @jpmedley
=> Analytics Removing install instruction

packages/workbox-cacheable-response/src/index.js
R: @jeffposnick @addyosmani @jpmedley 
Also includes sweep for workbox-sw.
=> Minor doc changes to cachable-response

packages/workbox-build/demo/index.js, packages/workbox-build/src/index.js, packages/workbox-build/src/lib/errors.js, packages/workbox-build/src/lib/generate-file-manifest.js, packages/workbox-build/src/lib/generate-sw.js, packages/workbox-build/src/lib/get-file-manifest-entries.js, packages/workbox-build/src/lib/inject-manifest.js, packages/workbox-build/test/node/generate-file-manifest.js, packages/workbox-build/test/node/generate-sw-e2e.js, packages/workbox-build/test/node/generate-sw.js, packages/workbox-build/test/node/get-file-manifest-entries.js, packages/workbox-build/test/node/injection-manifest.js, packages/workbox-cli/src/index.js, packages/workbox-cli/test/node/cli-flags.js, packages/workbox-cli/test/static/example-cli-command/example-command.txt, packages/workbox-webpack-plugin/index.js
=> Add support for globPatterns, prefer it to staticFileGlobs.

.eslintrc, packages/workbox-background-sync/src/index.js, packages/workbox-background-sync/src/lib/background-sync-queue-plugin.js, packages/workbox-background-sync/src/lib/background-sync-queue.js, packages/workbox-background-sync/src/lib/broadcast-manager.js, packages/workbox-background-sync/src/lib/constants.js, packages/workbox-background-sync/src/lib/queue-utils.js, packages/workbox-background-sync/src/lib/request-manager.js, packages/workbox-background-sync/src/lib/request-queue.js, packages/workbox-background-sync/src/lib/response-manager.js, packages/workbox-background-sync/test/browser/background-sync-queue-plugin.js, packages/workbox-background-sync/test/browser/background-sync-queue.js, packages/workbox-background-sync/test/browser/broadcast-manager.js, packages/workbox-background-sync/test/browser/queue-utils.js, packages/workbox-background-sync/test/browser/request-manager.js, packages/workbox-background-sync/test/browser/response-manager.js, packages/workbox-webpack-plugin/index.js, packages/workbox-webpack-plugin/test/node/test.js
R: @jeffposnick @addyosmani @jpmedley @prateekbh 
Everything is still borked for sample code so no more tabs prateek and also minor tweaks to docs.
=> Doc sweep of bg-sync

packages/workbox-sw/src/index.js, packages/workbox-sw/src/lib/error-factory.js, packages/workbox-sw/src/lib/router.js, packages/workbox-sw/src/lib/strategies.js, packages/workbox-sw/src/lib/workbox-sw.js, packages/workbox-sw/test/sw/skip-waiting-false.js, packages/workbox-sw/test/sw/skip-waiting-true.js, packages/workbox-sw/test/sw/skip-waiting.js
R: @jeffposnick @addyosmani @jpmedley 
This also adds in skipWaiting support.
=> Workbox sw sweep

packages/workbox-build/src/lib/errors.js
=> Fixed - Minor typo

packages/workbox-sw/src/index.js
=> Fixes #585

packages/workbox-cli/src/lib/questions/ask-root-of-web-app.js, packages/workbox-cli/test/node/cli-root-dir.js
=> Stop hidden files being an option in the CLI

packages/workbox-build/src/lib/get-file-manifest-entries.js, packages/workbox-build/test/node/get-file-manifest-entries.js
=> Fixing #348. Return Promise from getFileManifestEntries

packages/workbox-build/src/lib/errors.js, packages/workbox-build/src/lib/write-sw.js, packages/workbox-build/test/node/lib-write-sw.js
=> Return a specific error when swDest is a directory.

packages/workbox-routing/src/lib/navigation-route.js, packages/workbox-routing/test/sw/navigation-route.js
=> Include the URL's search when matching the NavigationRoute white/blacklist

packages/workbox-precaching/src/lib/controllers/base-cache-manager.js, packages/workbox-precaching/src/lib/controllers/revisioned-cache-manager.js, packages/workbox-precaching/src/lib/controllers/unrevisioned-cache-manager.js, packages/workbox-precaching/src/lib/models/revision-details-model.js, packages/workbox-precaching/test/sw/revisioned-caching.js
=> Removes the IDB entry when a URL is removed from the precache list.

packages/workbox-background-sync/package.json, packages/workbox-background-sync/src/lib/background-sync-queue.js, packages/workbox-background-sync/src/lib/request-manager.js, packages/workbox-background-sync/test/browser/request-manager.js, packages/workbox-background-sync/test/config.json, packages/workbox-runtime-caching/src/lib/request-wrapper.js
R: @prateekbh @philipwalton 
Reverts GoogleChrome/workbox#648
=> Revert "Use requestWrapper.fetch() instead of fetch() in BSQ"

.gitignore
=> Minor cleanup of the gitignore file.

package-lock.json
=> Adds a current package-lock.json

package-lock.json, package.json, packages/workbox-build/src/lib/constants.js, packages/workbox-build/src/lib/generate-sw.js, packages/workbox-build/src/lib/get-file-manifest-entries.js, packages/workbox-build/src/lib/inject-manifest.js, packages/workbox-build/test/node/generate-sw.js, packages/workbox-build/test/node/get-file-manifest-entries.js, packages/workbox-cli/test/utils/validator/test-in-browser.js
Fixes #421
Sets default glob pattern to include js,css and html
=> Adding defaults to workbox-build

packages/workbox-build/src/lib/utils/copy-workbox-sw.js, packages/workbox-build/test/node/utils-copy-sw-lib.js
Fixes #625
Copy the sourcemap over with the js file.
=> Copies sourcemap over with source files

packages/workbox-build/src/lib/generate-sw.js
small typo just needs a quick fix
n/a
small typo
=> typo: fix small typo

.github/ISSUE_TEMPLATE.md
=> Link to [workbox] on SO.

package-lock.json, package.json, packages/workbox-build/test/node/utils-filter-files.js
Fixes #718
Adds a basic test to ensure we don't regress from a bug where custom manifestTransforms weren't being applied.
=> Adds a test to ensure manifest transforms can be applied

.github/PULL_REQUEST_TEMPLATE.md
=> Update to PR instructions

package-lock.json, package.json
Bumps the pr-bot which includes some gzip data.
=> Bumps pr-bot

package.json
=> V3 bot bump

.eslintrc.js, infra/pr-bot/aggregate-size-plugin.js, package-lock.json, package.json, pr-bot.config.js
Fixes #733 
This doesn't QUITE force the the 10KB limit briefly mentioned in the V3 doc, but it will show a warning when we start to get close (I need to add some minor tweaks to pr-bot to fail the status of the build.
in the mean time, see what you think of this code.
=> V3 force size

.eslintrc.js, .gitignore, gulp-tasks/test.js, gulp-tasks/utils/mocha-coverage-reporter.js, infra/pr-bot/aggregate-size-plugin.js, infra/utils/generate-variant-tests.js, package-lock.json, package.json, pr-bot.config.js, test/workbox-core/node/controllers/test-WorkboxCore.mjs, test/workbox-core/node/models/messages/testMessageGenerator.mjs, test/workbox-core/node/utils/test-LogHelper.mjs
This moves the current tests over to using @std/esm instead of the bundling I was doing before.
=> V3: @std/esm tests

packages/workbox-routing/src/lib/router.js
=> #782 add jsdoc for conflicting routes

package-lock.json, packages/workbox-core/_private.mjs, packages/workbox-core/index.mjs, packages/workbox-core/models/cacheNameProvider.mjs, packages/workbox-core/models/messages/messageGenerator.mjs, packages/workbox-core/models/messages/messages.mjs, packages/workbox-core/utils/cacheWrapper.mjs, packages/workbox-core/utils/fetchWrapper.mjs, test/workbox-core/node/controllers/test-WorkboxCore.mjs, test/workbox-core/node/utils/test-assert.mjs, test/workbox-core/node/utils/test-fetchWrapper.mjs, test/workbox-core/node/utils/test-logger.mjs
Fixes #800
Implement cache names as discussed. I think it should make this story easy to follow for developers and offer all the flexibility we would need / want to offer.
One thing I enforced that we didn't discuss was that the `precache` and `runtime` cache must be at least one character long. The `prefix` and `suffix` can be empty if the developer wants.
There are some additional tests / changes to logic just to improve code coverage a little.
=> V3 caching

.eslintrc.js, .gitattributes, infra/utils/generate-variant-tests.js, package-lock.json, package.json, packages/workbox-core/_private.mjs, packages/workbox-core/models/WorkboxError.mjs, packages/workbox-core/utils/cacheWrapper.mjs, packages/workbox-core/utils/indexDBHelper.mjs, packages/workbox-core/utils/indexedDBHelper.mjs, packages/workbox-precaching/controllers/PrecacheController.mjs, packages/workbox-precaching/models/PrecacheEntry.mjs, packages/workbox-precaching/models/PrecachedDetailsModel.mjs, test/workbox-core/node/controllers/test-WorkboxCore.mjs, test/workbox-core/node/utils/test-fetchWrapper.mjs, test/workbox-precaching/node/controllers/test-PrecacheController.mjs, test/workbox-precaching/node/models/test-PrecacheEntry.mjs, test/workbox-precaching/node/models/test-PrecachedDetailsModel.mjs, test/workbox-precaching/node/test-environment.mjs
This adds in our old school indexeddb helper into core and precaching uses it for it's model to track revision changes.
After this it should be relatively quick to finish off precaching and I'll make sure to tidy up any remaining todos.
=> V3 precaching reinstall

package-lock.json, packages/workbox-precaching/controllers/PrecacheController.mjs, packages/workbox-precaching/models/PrecachedDetailsModel.mjs, test/workbox-precaching/node/controllers/test-PrecacheController.mjs, test/workbox-precaching/node/models/test-PrecachedDetailsModel.mjs
This adds checks to pre-caching to ensure that on a second install, only the updated entries are cached / updated.
Also updated the tests for the revision details model to be more accurate (Using actual PrecacheEntry models rather than a fake object mimicking the model
=> V3 precaching model

.eslintrc.js, infra/utils/generate-variant-tests.js, package-lock.json, package.json, packages/workbox-build/src/lib/generate-file-manifest.js, packages/workbox-build/src/lib/utils/runtime-caching-converter.js, packages/workbox-build/src/lib/utils/warn-about-config.js, packages/workbox-routing/lib/Route.mjs
=> V3 valid jsdoc

packages/workbox-build/src/index.js, packages/workbox-build/src/lib/log-helper.js, packages/workbox-build/src/lib/utils/filter-files.js, packages/workbox-build/src/lib/utils/warn-about-config.js, packages/workbox-cli/src/index.js, packages/workbox-cli/src/lib/constants.js, packages/workbox-cli/src/lib/log-helper.js, packages/workbox-cli/src/lib/questions/ask-root-of-web-app.js, packages/workbox-google-analytics/src/index.js, packages/workbox-range-requests/src/lib/cached-range-response-plugin.js, packages/workbox-range-requests/src/lib/handle-range-request.js, packages/workbox-routing/src/lib/normalize-handler.js
This should be the last one regarding docs. A lot of this is just ensuring docs are private. JSDocs theme is more forgiving that the DevSite template :(
=> Fixing up more docs issues :(

gulp-tasks/docs.js, package.json, packages/workbox-build/src/index.js, packages/workbox-core/utils/fetchWrapper.mjs, packages/workbox-precaching/controllers/PrecacheController.mjs, packages/workbox-precaching/default-precaching-export.mjs, packages/workbox-precaching/index.mjs, test/workbox-precaching/node/test-precaching-module.mjs
This is the last piece of precaching. Small helper API for precaching to manage the install and activate step.
Also fixed a small JSDoc issue where it wasn't using my local copy.
=> V3 precaching default

.gitignore, gulp-tasks/publish-cdn.js, gulp-tasks/publish-github.js, gulp-tasks/utils/cdn-helper.js, gulp-tasks/utils/generate-release-files.js, gulp-tasks/utils/github-helper.js, infra/utils/sw-env.js, packages/workbox-sw/index.mjs, packages/workbox-sw/package.json, test/workbox-sw/node/test-WorkboxSW.mjs
=> V3 workbox-sw

gulp-tasks/test-integration.js, gulp-tasks/test-node.js, gulp-tasks/test.js, gulpfile.js, infra/testing/test-server.js, package.json, test/workbox-precaching/integration/precache-and-update.js
Far from perfect, but a start. Just wanted early feedback at the moment.
=> V3 integration test start

.eslintrc.js, gulp-tasks/build-browser-packages.js, gulp-tasks/test-integration.js, gulp-tasks/test-node.js, gulp-tasks/test-server.js, gulp-tasks/utils/build-browser-package.js, gulp-tasks/utils/constants.js, gulp-tasks/utils/rollup-helper.js, infra/testing/env-it.js, infra/testing/test-server.js, packages/workbox-core/index.mjs, test/workbox-core/node/controllers/test-WorkboxCore.mjs, test/workbox-core/node/models/messages/testMessageGenerator.mjs, test/workbox-precaching/node/test-environment.mjs
I think this addresses the first point on #851 
Still need to switch over a bunch of tests to devOnly and prodOnly (If people like that pattern).
=> Moving to a more consistent build types set up

packages/workbox-google-analytics/src/index.js, packages/workbox-sw/src/index.js
=> Fix docs in workbox-sw, workbox-google-analytics

packages/workbox-build/src/entry-points/inject-manifest.js, packages/workbox-build/src/lib/errors.js, test/workbox-build/node/entry-points/inject-manifest.js
=> Reject when swSrc and swDest are the same

packages/workbox-core/utils/cacheWrapper.mjs, packages/workbox-runtime-caching/CacheFirst.mjs, packages/workbox-runtime-caching/CacheOnly.mjs, packages/workbox-runtime-caching/index.mjs, test/workbox-runtime-caching/node/test-CacheFirst.mjs, test/workbox-runtime-caching/node/test-CacheOnly.mjs
=> V3 cache only

infra/testing/sw-env.js, packages/workbox-precaching/models/PrecacheEntry.mjs, packages/workbox-precaching/utils/printCleanupDetails.mjs, packages/workbox-precaching/utils/printInstallDetails.mjs, test/workbox-precaching/node/models/test-PrecacheEntry.mjs
Fixes #874
Super minor fixes to wording
=> V3 precaching logs

packages/workbox-runtime-caching/NetworkFirst.mjs, test/workbox-runtime-caching/node/test-NetworkFirst.mjs
Adds NetworkFirst caching strategy
=> Adding network first strategy

gulp-tasks/docs.js, packages/workbox-runtime-caching/CacheFirst.mjs, packages/workbox-runtime-caching/NetworkOnly.mjs, test/workbox-runtime-caching/node/test-NetworkOnly.mjs
Adding Network Only to runtime caching.
=> V3 network only

cdn-details.json, gulp-tasks/build-node-packages.js, gulp-tasks/build.js, gulp-tasks/publish-cdn.js, gulp-tasks/utils/cdn-helper.js, gulp-tasks/utils/rollup-helper.js, infra/utils/versioning.js, lerna.json, packages/workbox-build/package.json, packages/workbox-build/src/cdn-details.json, packages/workbox-build/src/lib/cdn-utils.js, packages/workbox-core/package.json, packages/workbox-precaching/package.json, packages/workbox-routing/package.json, packages/workbox-runtime-caching/package.json, packages/workbox-sw/index.mjs, packages/workbox-sw/package.json, test/workbox-sw/node/test-WorkboxSW.mjs
Hopefully this would allow you to use CDN in workbox-build. Let me know if not.
=> Adding helpers to workbox-build

gulp-tasks/docs.js, packages/workbox-core/index.mjs, packages/workbox-core/models/LogLevels.mjs, packages/workbox-core/models/messages/messages.mjs, packages/workbox-core/utils/cacheWrapper.mjs, packages/workbox-core/utils/fetchWrapper.mjs, test/workbox-core/node/controllers/test-WorkboxCore.mjs, test/workbox-core/node/models/messages/testMessageGenerator.mjs, test/workbox-core/node/utils/test-logger.mjs, test/workbox-sw/static/sw.js
Tidies docs, minor size wins.
Changes .logLevel setter to setLogLevel as it makes it a lot cleaner in the resulting docs.
=> V3 core sweep

packages/workbox-runtime-caching/NetworkFirst.mjs, packages/workbox-runtime-caching/StaleWhileRevalidate.mjs, packages/workbox-runtime-caching/plugins/CacheOkAndOpaquePlugin.mjs, test/workbox-runtime-caching/node/test-CacheOnly.mjs, test/workbox-runtime-caching/node/test-StaleWhileRevalidate.mjs
=> V3 stale while revalidate

packages/workbox-runtime-caching/CacheFirst.mjs, packages/workbox-runtime-caching/CacheOnly.mjs, packages/workbox-runtime-caching/NetworkFirst.mjs, packages/workbox-runtime-caching/NetworkOnly.mjs, packages/workbox-runtime-caching/index.mjs
=> V3 runtime caching docs

.travis.yml
As discussed with @philipwalton and @gauntface 
We're ditching the per-package build/tests and trying out a single build job on Travis CI.
=> Moves to a single gulp --test in Travis CI.

packages/workbox-core/index.mjs, packages/workbox-core/utils/logger.mjs, packages/workbox-core/workboxCore.mjs, test/workbox-core/static/logger.html
This adds the welcome message. To ensure the WorkboxCore class was instantiated before the logger tried to use, I had to move the class and instantiation into a seperate file.
=> Adds in the workbox welcome msg

packages/workbox-core/models/LogLevels.mjs, packages/workbox-core/utils/logger.mjs, packages/workbox-core/workboxCore.mjs, packages/workbox-sw/index.mjs, test/workbox-core/node/controllers/test-WorkboxCore.mjs, test/workbox-core/node/test-exports.mjs, test/workbox-core/node/utils/test-logger.mjs, test/workbox-core/static/logger.html, test/workbox-sw/static/sw.js
This PR makes console.debug messages the lowest priority and by default not get printed to the console.
=> V3 logging

gulp-tasks/publish-github.js, packages/workbox-routing/Route.mjs, packages/workbox-routing/Router.mjs, packages/workbox-routing/default-export.mjs, packages/workbox-routing/index.mjs, test/workbox-routing/node/Route.mjs, test/workbox-routing/node/Router.mjs
This is very rough, but it at least surfaces the available top level functions on the workbox-routing default export.
=> V3 routing docs

packages/workbox-runtime-caching/index.mjs
Adding stale while revalidate.
=> Export the style while revalidate

packages/workbox-cache-expiration/CacheExpirationManager.mjs, packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs, test/workbox-cache-expiration/node/test-CacheExpirationManager.mjs, test/workbox-cache-expiration/node/test-CacheTimestampsModel.mjs
Another baby steps PR for cache expiration. This finishes the expiration for max age, but doesn't clear the cache yet. Will do that along with the maximum entries clean up.
=> Adding some tests and getting expiration working

packages/workbox-cache-expiration/CacheExpirationManager.mjs, packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs, packages/workbox-core/utils/indexedDBHelper.mjs, test/workbox-cache-expiration/node/test-CacheExpirationManager.mjs, test/workbox-cache-expiration/node/test-CacheTimestampsModel.mjs
This implements the remove extra entries.
Return sorted timestamps in the models - makes everything a little cleaner in the Manager.
=> Cache Expiration Remove extra entries

packages/workbox-runtime-caching/CacheOnly.mjs, packages/workbox-runtime-caching/NetworkFirst.mjs
=> Fix assertion mismatch

infra/testing/sw-env-mocks/FetchEvent.js, infra/testing/sw-env.js, packages/workbox-core/utils/assert.mjs, test/workbox-core/node/utils/test-assert.mjs, test/workbox-precaching/node/test-environment.mjs, test/workbox-routing/node/test-Router.mjs, test/workbox-routing/node/test-environment.mjs, test/workbox-runtime-caching/node/test-CacheFirst.mjs, test/workbox-runtime-caching/node/test-CacheOnly.mjs, test/workbox-runtime-caching/node/test-NetworkFirst.mjs, test/workbox-runtime-caching/node/test-NetworkOnly.mjs, test/workbox-runtime-caching/node/test-StaleWhileRevalidate.mjs
=> Update FetchEvent mock to follow the spec

packages/workbox-cache-expiration/CacheExpirationManager.mjs, packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs, test/workbox-cache-expiration/node/test-CacheExpirationManager.mjs, test/workbox-cache-expiration/node/test-CacheTimestampsModel.mjs, test/workbox-cache-expiration/static/isURLExpired.html
Last piece of the CacheExpirationManager for now - will work on the plugin once this looks ok.
=> Expires cache entries

packages/workbox-cache-expiration/CacheExpiration.mjs, packages/workbox-cache-expiration/CacheExpirationPlugin.mjs, packages/workbox-cache-expiration/index.mjs, packages/workbox-core/models/messages/messages.mjs, test/workbox-cache-expiration/node/test-CacheExpiration.mjs, test/workbox-cache-expiration/node/test-CacheExpirationPlugin.mjs, test/workbox-cache-expiration/static/isURLExpired.html
- Adds plugin
- Moves CacheExpiration class back to original name
- Adds error if method `isURLExpired()`  is used when no maxAgeSecond is used.
=> Adding expiration plugin

demos/functions/views/demo/workbox-cache-expiration.hbs, demos/functions/views/demo/workbox-cache-expiration/sw.hbs, demos/functions/views/demo/workbox-core/sw.hbs, demos/functions/views/demo/workbox-precaching/sw-1.hbs, demos/functions/views/demo/workbox-precaching/sw-2.hbs, demos/functions/views/demo/workbox-routing/sw.hbs
Nothing too crazy in this one.
Fixed the demos to work with latest changes to workbox-sw and started work on cache-expiration demo.
=> Expiration Demo + Fixing Demos for Workbox-SW Changes

packages/workbox-precaching/_default.mjs
Writing up guide on precaching and realised the defaults were missing.
=> Noticed defaults were missing

packages/workbox-core/_private/assert.mjs, packages/workbox-core/models/messages/messages.mjs, packages/workbox-routing/NavigationRoute.mjs, packages/workbox-routing/_public.mjs, test/workbox-routing/node/test-NavigationRoute.mjs, test/workbox-routing/node/test-interface.mjs
Adds NavigationRoute to workbox-routing.
=> Adding navigation route

demos/functions/views/demo/workbox-core.hbs, demos/functions/views/demo/workbox-core/sw.hbs, packages/workbox-core/_default.mjs, packages/workbox-core/models/LogLevels.mjs
Just tidying up workbox-core docs and hopefully it'll be a little cleaner for developers to use.
=> Updating jsdocs to be a little cleaner

packages/workbox-precaching/_default.mjs, packages/workbox-precaching/index.mjs
R: @jeffposnick @addyosmani @surma 
Fixes #984 
Docs on precaching and `addRoute`
=> Adding some more context to the precaching docs

package-lock.json, packages/workbox-precaching/controllers/PrecacheController.mjs, packages/workbox-precaching/models/PrecachedDetailsModel.mjs, packages/workbox-precaching/utils/printCleanupDetails.mjs, test/workbox-precaching/node/controllers/test-PrecacheController.mjs
R: @jeffposnick @addyosmani @surma 
Fixes #985 Add docs for cleanup, fix cleanup tests (They actually broke from DBWrapper changes).
Fixes #986 with install result typedef.
Fixes #987 with precache entry typedef.
=> Precaching 985

packages/workbox-core/_default.mjs, packages/workbox-core/_private/cacheNames.mjs, test/workbox-core/node/_private/test-assert.mjs, test/workbox-core/node/controllers/test-WorkboxCore.mjs
Nothing crazy, just making sure coverage is up.
=> Minor code coverage improvement

demos/functions/views/demo/workbox-routing/sw.hbs, packages/workbox-routing/NavigationRoute.mjs, packages/workbox-routing/RegExpRoute.mjs, packages/workbox-routing/Route.mjs, packages/workbox-routing/Router.mjs, packages/workbox-routing/_default.mjs, packages/workbox-routing/index.mjs
More tweaks to docs now that Routing has relevant methods from workbox-sw. Only missing piece is the ExpressRoute.
=> Routing docs

packages/workbox-build/src/index.js, packages/workbox-routing/NavigationRoute.mjs, packages/workbox-routing/RegExpRoute.mjs, packages/workbox-routing/Route.mjs, packages/workbox-routing/Router.mjs, packages/workbox-routing/_default.mjs, packages/workbox-routing/_types.mjs, packages/workbox-routing/index.mjs, packages/workbox-routing/utils/constants.mjs, packages/workbox-routing/utils/normalizeHandler.mjs, packages/workbox-runtime-caching/CacheFirst.mjs, packages/workbox-runtime-caching/CacheOnly.mjs, packages/workbox-runtime-caching/NetworkFirst.mjs, packages/workbox-runtime-caching/NetworkOnly.mjs, packages/workbox-runtime-caching/StaleWhileRevalidate.mjs, test/workbox-routing/node/test-Router.mjs, test/workbox-routing/node/test-default.mjs
Just moving routing docs to routing namespace.
=> Fixing up routing namespace

packages/workbox-cache-expiration/CacheExpiration.mjs, packages/workbox-cache-expiration/CacheExpirationPlugin.mjs, packages/workbox-cache-expiration/index.mjs, packages/workbox-cache-expiration/models/CacheTimestampsModel.mjs, packages/workbox-core/models/messages/messages.mjs, test/workbox-cache-expiration/node/test-CacheExpiration.mjs, test/workbox-cache-expiration/node/test-CacheExpirationPlugin.mjs
Increases cache-expiration cover and fixes JSDocs (using namespaces).
=> Cache expiration coverage

demos/functions/views/demo/workbox-routing/sw.hbs, packages/workbox-routing/Router.mjs
Adds default and catch handler to routing demo.
=> Routing Default + Catch Error demo

test/workbox-sw/node/test-WorkboxSW.mjs
Minor test but gets coverage to 100%
=> 100% sw coverage

demos/functions/views/demo/workbox-runtime-caching/sw.hbs
I wanted to make the runtime-caching demo a little cleaner / easier to read.
=> Tidying up the strategies demo

packages/workbox-google-analytics/_default.mjs, packages/workbox-google-analytics/utils/constants.mjs, test/workbox-google-analytics/node/test-index.mjs
=> Add support for the new gtag.js script

infra/pr-bot/aggregate-size-plugin.js
=> Proper configuration for the AggregateSizePlugin

demos/functions/index.js, gulp-tasks/utils/build-browser-bundle.js, packages/workbox-build/src/entry-points/generate-sw.js, packages/workbox-build/src/lib/cdn-utils.js, packages/workbox-sw/package.json, test/workbox-build/node/entry-points/generate-sw.js, test/workbox-sw/static/sw.js
Fixes #969 
Assuming this is merged, I'll go through the CDN publishing steps from start to finish to confirm that everything works for me, and to get the new `workbox-sw.js` pushed out there.
=> Create a single (prod) build of workbox-sw.

jsdoc.conf, packages/workbox-background-sync/Queue.mjs, packages/workbox-background-sync/QueuePlugin.mjs, packages/workbox-background-sync/index.mjs, packages/workbox-background-sync/models/QueueStore.mjs
=> Fixing docs for bg sync and moving to namespace

packages/workbox-build/src/lib/copy-workbox-libraries.js
Correcting an error in build docs
=> Correcting build docs

jsdoc.conf
=> block cli docs

packages/workbox-google-analytics/_default.mjs, packages/workbox-google-analytics/index.mjs
R: @jeffposnick @addyosmani @philipwalton
=> Changing analytics module to namespace

test/workbox-routing/integration/routing-regex.js, test/workbox-routing/static/routing-regex/index.html, test/workbox-routing/static/routing-regex/sw.js
Some integration tests for workbox-routing. This just focuses on Regular Expression Options.
=> Adding regexp routing integration test

package-lock.json, packages/workbox-background-sync/QueuePlugin.mjs, packages/workbox-google-analytics/_default.mjs, test/workbox-background-sync/node/lib/test-Queue.mjs, test/workbox-background-sync/node/lib/test-QueuePlugin.mjs
Based on the discussion in #1057, this PR updates the `QueuePlugin` class to not take a `Queue` instance, but rather take the same parameters as `Queue` and instantiate one internally.
=> Update the QueuePlugin class to take Queue params

packages/workbox-cli/src/app.js, packages/workbox-cli/src/lib/errors.js, packages/workbox-cli/src/lib/help-text.js, test/workbox-cli/node/app.js
=> workbox-cli copyLibraries

demos/functions/cdn-details.json, gulp-tasks/publish-cdn.js, gulp-tasks/publish-demos.js, gulp-tasks/publish-github.js, gulp-tasks/publish-lerna.js, gulp-tasks/publish.js, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-sw/_version.mjs
=> Version bump and updates to publishing

infra/testing/validator/service-worker-runtime.js, packages/workbox-build/src/templates/sw-template.js, test/workbox-build/node/entry-points/generate-sw-string.js, test/workbox-build/node/entry-points/generate-sw.js, test/workbox-webpack-plugin/node/index.js
=> Add workbox.precaching.suppressWarnings() to the SW template.

demos/functions/index.js, demos/functions/views/demo/workbox-cacheable-response.hbs, demos/functions/views/demo/workbox-cacheable-response/sw.hbs, firebase.json, infra/testing/sw-env-mocks/Headers.js, packages/workbox-cacheable-response/CacheableResponse.mjs, packages/workbox-sw/controllers/WorkboxSW.mjs
- Adds cacheable response to workbox-sw (I need to auto-generate the list of namespaces to module names)
- Adds cachable response demo
- Prints out status and headers for a response for easier debugging
=> Adding cacheable response demo

packages/workbox-cli/src/app.js, packages/workbox-cli/src/lib/constants.js, packages/workbox-cli/src/lib/errors.js, packages/workbox-cli/src/lib/help-text.js, packages/workbox-cli/src/lib/questions/ask-config-location.js, test/workbox-cli/node/app.js
=> Use a default config file of workbox-config.js

demos/functions/views/demo/workbox-broadcast-cache-update.hbs, demos/functions/views/demo/workbox-broadcast-cache-update/sw.hbs, packages/workbox-sw/controllers/WorkboxSW.mjs
=> Adding broadcast channel demo

packages/workbox-google-analytics/_default.mjs, packages/workbox-google-analytics/utils/constants.mjs, test/workbox-google-analytics/node/test-index.mjs
=> Support experimental Measurement Protocol paths

demos/functions/cdn-details.json, gulp-tasks/publish-cdn.js, gulp-tasks/publish-demos.js, gulp-tasks/publish.js, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-sw/_version.mjs
Just doing this to ensure I don't break anything by mistake
=> alpha.2 release

gulp-tasks/publish-github.js
I realised the *actual* github publishing code was broken. Minor tweaks needed to get the same behavior with the "test" releases when I first wrote the code.
=> Github publish flow fixes.

demos/functions/index.js, demos/functions/views/demo/workbox-broadcast-cache-update.hbs, demos/functions/views/demo/workbox-broadcast-cache-update/sw.hbs, demos/functions/views/demo/workbox-cache-expiration.hbs, demos/functions/views/demo/workbox-cache-expiration/sw.hbs, demos/functions/views/demo/workbox-cacheable-response.hbs, demos/functions/views/demo/workbox-core.hbs, demos/functions/views/demo/workbox-core/sw.hbs, demos/functions/views/demo/workbox-strategies.hbs, demos/functions/views/demo/workbox-sw.hbs
Making sure we implement the expected guidance we give to developers.
=> No cache control and wait from window load

test/workbox-background-sync/node/lib/test-QueueStore.mjs, test/workbox-background-sync/node/test-Plugin.mjs
=> Rename QueuePlugin test to Plugin

packages/workbox-cache-expiration/CacheExpiration.mjs, packages/workbox-cache-expiration/Plugin.mjs, packages/workbox-precaching/models/PrecacheEntry.mjs, test/workbox-build/node/entry-points/generate-sw.js
Some errors thrown up by DevSite.
=> Found common typos

packages/workbox-precaching/controllers/PrecacheController.mjs, packages/workbox-precaching/models/PrecachedDetailsModel.mjs, test/workbox-precaching/node/controllers/test-PrecacheController.mjs, test/workbox-precaching/node/models/test-PrecachedDetailsModel.mjs
The indexedDB wrapper stuff changes but due to my bad tests, I didn't catch any of it. This should fix tests and ensure the format doesn't change in the future.
=> Precaching and IDB Issues

packages/workbox-precaching/models/PrecachedDetailsModel.mjs
Phil pointed out the issue was the version number. This bumps the number and cleans up the previous release.
Fixes #1109
=> Delete previous idb and upgrade for v3

packages/workbox-build/src/lib/populate-sw-template.js, packages/workbox-build/src/templates/sw-template.js
=> Clean up the service worker template.

packages/workbox-sw/controllers/WorkboxSW.mjs, test/workbox-sw/node/test-WorkboxSW.mjs
Adds a test to ensure workbox-sw supports all of the mappings for all modules.
=> A simple test to ensure modules have a mapping in workbox-sw

package-lock.json, package.json
R: @jeffposnick @prateekbh 
Fingers crossed this helps
=> Updating package

demos/functions/views/demo/workbox-sw/sw.hbs, package-lock.json, packages/workbox-cache-expiration/Plugin.mjs, test/workbox-cache-expiration/node/test-Plugin.mjs
Fixes #1168 
Apologies for the somewhat weird change set on this PR - Github got a bit confused.
I've just moved a test and added a test that accounts for when the cachedResponseWillBeUsed function returns null.
=> Handles scenario where no cached response will be used.

packages/workbox-cli/src/app.js, packages/workbox-cli/src/bin.js, packages/workbox-cli/src/lib/assert-valid-sw-src.js, packages/workbox-cli/src/lib/errors.js, packages/workbox-cli/src/lib/help-text.js, packages/workbox-cli/src/lib/questions/ask-questions.js, packages/workbox-cli/src/lib/questions/ask-sw-src.js, packages/workbox-cli/src/lib/run-wizard.js, test/workbox-cli/node/app.js, test/workbox-cli/node/lib/questions/ask-questions.js, test/workbox-cli/node/lib/questions/ask-sw-src.js, test/workbox-cli/node/lib/run-wizard.js
CC: @DavidScales @nasearle
Fixes #1052
```sh
workbox wizard --swSrc='/path/to/sw.js'
```
will work now.
=> Support --injectManifest in the workbox-cli wizard.

packages/workbox-build/src/lib/cdn-utils.js, packages/workbox-build/src/lib/errors.js, test/workbox-build/node/lib/cdn-utils.js
Fixes #1174
Added some missing tests for that module as well.
=> cdnUtils fix + tests.

test/workbox-core/integration/test-core.js, test/workbox-core/static/core-in-browser/index.html, test/workbox-core/static/core-in-browser/sw.js
Fixes #1192
A very basic integration test for workbox-core.
Wasn't sure what test beyond - is the API as we expected when loaded in the browser.
=> Adding workbox-core integration test

demos/functions/views/demo/workbox-google-analytics.hbs, demos/functions/views/demo/workbox-google-analytics/sw.hbs, package-lock.json
Adding demo for Google Analytics.
Fixes #1199
=> Adding an analytics demo

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-sw/_version.mjs
These were locally updated as part of the `gulp publish` process, and need to be checked in to `v3`.
=> Updates to CDN/_version.mjs for alpha 6

gulp-tasks/test-integration.js, packages/workbox-background-sync/Queue.mjs, packages/workbox-background-sync/models/StorableRequest.mjs, test/workbox-background-sync/integration/test-bg-sync.js, test/workbox-background-sync/static/basic-example/example.txt, test/workbox-background-sync/static/basic-example/index.html, test/workbox-background-sync/static/basic-example/sw.js
Very trivial bg sync test but ensures:
- loads in browser
- sync event is used
This doesn't test the offline to online sync event that is desirable, but that becomes difficult to test.
Fixes #1190
=> Basic bg sync test

packages/workbox-webpack-plugin/src/generate-sw.js, packages/workbox-webpack-plugin/src/inject-manifest.js, test/workbox-webpack-plugin/node/generate-sw.js, test/workbox-webpack-plugin/node/inject-manifest.js
=> Honor publicPath when determining the precache manifest URL.

packages/workbox-cli/src/bin.js
=> Show the --help message when there are no params.

packages/workbox-cli/src/lib/questions/ask-root-of-web-app.js
=> Tweak wording for root of web app question.

test/workbox-sw/integration/workbox-sw.js, test/workbox-sw/static/integration/index.html, test/workbox-sw/static/integration/invalid-sw.js, test/workbox-sw/static/integration/valid-sw.js
=> Workbox sw integration test

test/workbox-google-analytics/integration/basic-example.js, test/workbox-google-analytics/static/basic-example/index.html, test/workbox-google-analytics/static/basic-example/sw.js
An incredibly basic test but this will at least confirm everything loads and requests for analytics will go through the module without instantly failing.
Fixes #1193
=> Adding a basic integration test for analytics

packages/workbox-core/_private/cacheWrapper.mjs, packages/workbox-core/_private/fetchWrapper.mjs
Fixes #1206
This adds some additional checks to plugin return types and inputs.
=> Validate plugin input / output

demos/functions/views/demo/workbox-background-sync.hbs, demos/functions/views/demo/workbox-background-sync/sw.hbs, demos/public/demo/workbox-background-sync/example.txt, packages/workbox-background-sync/Queue.mjs
Fixes #1198 
Adds demo for background-sync
=> Bg sync demo

packages/workbox-background-sync/Queue.mjs, packages/workbox-background-sync/utils/constants.mjs, packages/workbox-google-analytics/utils/constants.mjs, test/workbox-background-sync/node/lib/test-Queue.mjs, test/workbox-background-sync/node/lib/test-QueueStore.mjs, test/workbox-background-sync/node/test-Plugin.mjs, test/workbox-background-sync/node/test-Queue.mjs
R: @jeffposnick @prateekbh  @gauntface
Fixes #1254
Also fixes some other uncaught testing issues and moves the `test-Queue.mjs` file into the correct folder.
=> Convert bg sync maxRetentionTime to minutes

gulp-tasks/test-integration.js, infra/testing/activate-sw.js, test/workbox-background-sync/integration/test-bg-sync.js, test/workbox-broadcast-cache-update/integration/broadcast-cache-update-plugin.js, test/workbox-cache-expiration/integration/expiration-plugin.js, test/workbox-cacheable-response/integration/test-cacheable-response-plugin.js, test/workbox-core/integration/test-core.js, test/workbox-google-analytics/integration/basic-example.js, test/workbox-range-requests/integration/range-requests-plugin.js, test/workbox-routing/integration/navigation-route.js, test/workbox-routing/integration/routing-basic.js, test/workbox-routing/integration/routing-regex.js, test/workbox-strategies/integration/test-cacheFirst.js, test/workbox-strategies/integration/test-cacheOnly.js, test/workbox-strategies/integration/test-networkFirst.js, test/workbox-strategies/integration/test-networkOnly.js, test/workbox-strategies/integration/test-staleWhileRevalidate.js, test/workbox-sw/integration/workbox-sw.js
Fixes #1251 
Don't merge for now; I want to try running this on Travis and tweak some things as needed.
=> Refactor intergration tests

packages/workbox-strategies/utils/messages.mjs
=> Fix typo in console log messages

gulp-tasks/test-integration.js, infra/testing/activate-sw-safari.js, infra/testing/activate-sw.js, infra/testing/clean-sw.js, package-lock.json, package.json, test/workbox-background-sync/integration/test-bg-sync.js, test/workbox-broadcast-cache-update/integration/broadcast-cache-update-plugin.js, test/workbox-cache-expiration/integration/expiration-plugin.js, test/workbox-cacheable-response/integration/test-cacheable-response-plugin.js, test/workbox-core/integration/test-core.js, test/workbox-google-analytics/integration/basic-example.js, test/workbox-precaching/integration/precache-and-update.js, test/workbox-precaching/static/precache-and-update/messenger.js, test/workbox-precaching/static/precache-and-update/sw-1.js, test/workbox-precaching/static/precache-and-update/sw-2.js, test/workbox-precaching/utils/getPrecachedIDBData-safari.js, test/workbox-precaching/utils/getPrecachedIDBData.js, test/workbox-range-requests/integration/range-requests-plugin.js, test/workbox-routing/integration/navigation-route.js, test/workbox-routing/integration/routing-basic.js, test/workbox-routing/integration/routing-regex.js, test/workbox-strategies/integration/test-cacheFirst.js, test/workbox-strategies/integration/test-cacheOnly.js, test/workbox-strategies/integration/test-networkFirst.js, test/workbox-strategies/integration/test-networkOnly.js, test/workbox-strategies/integration/test-staleWhileRevalidate.js
This makes the tests work on safari tech preview. I won't lie there could easily be stuff that isn't ideal in here but I've tried to seperate Safari from everything else. This will probably need local testing. I need to figure out a way to validate version in selenium-assistant if we need Safari 49.
=> Safari tech preview

test/workbox-precaching/integration/precache-and-update.js
Fixes #1299 
I think this should help with some of the failures like those seen in #1299.
Previously, the integration test loaded the test page multiple times (once via `cleanSWEnv()`, and then again explicitly via `global.__workbox.webdriver.get()` before the tests runs, and then one more time at the end), and had to factor in those multiple page loads into the request counter.
This change removes one of the initial double-loads, and resets the counters right before precaching happens. I think that should lead to a more isolated test, where we're only confirming test values that are tied directly to precaching, instead of having to take into account which requests were made to bootstrap the harness page.
=> Clean up precaching integration test flow.

packages/workbox-background-sync/Queue.mjs
This should fix: https://github.com/GoogleChrome/workbox/issues/1266
=> Adding assertion for addRequest

packages/workbox-build/src/templates/sw-template.js, packages/workbox-cli/src/lib/help-text.js, packages/workbox-cli/src/lib/run-wizard.js
Fixes #1072 
There are a couple of shortlinks that can point to more specific documentation pages now.
=> Update to some shortlinks to build config docs.

packages/workbox-broadcast-cache-update/BroadcastCacheUpdate.mjs, packages/workbox-broadcast-cache-update/broadcastUpdate.mjs, test/workbox-broadcast-cache-update/node/test-broadcastUpdate.mjs, test/workbox-broadcast-cache-update/static/index.html
=> Adds feature detection for BroadcastChannel

infra/testing/sw-env-mocks/Response.js, packages/workbox-core/_private/cacheWrapper.mjs, packages/workbox-core/_private/checkSWFileCacheHeaders.mjs, packages/workbox-core/models/messages/messages.mjs, test/workbox-core/node/_private/test-cacheWrapper.mjs, test/workbox-core/node/_private/test-checkSWFileCacheHeaders.mjs
Fixes #1223
Also added tests for checkSWFileCacheHeaders().
=> Adding error for caching POST requests

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-sw/_version.mjs
This just bumps version numbers etc.
=> New beta release

demos/functions/views/layouts/main.hbs, gulp-tasks/publish-demos.js, gulp-tasks/publish-github.js, gulp-tasks/utils/github-helper.js, gulp-tasks/utils/publish-helpers.js
I didn't open an Issue because this Pull Request fix only typo.
Replace `public a Github release.` with `publish a GitHub release.`.
=> some typo corrections

test/workbox-precaching/static/precache-and-update/messenger.js
Fixes #1383, by accounting for the change introduced in https://github.com/GoogleChrome/workbox/pull/1346
=> Use the correct IDB name in Safari's precaching integration test

.travis.yml, appveyor.yml, package-lock.json, packages/workbox-build/src/entry-points/generate-sw-string.js, packages/workbox-build/src/entry-points/generate-sw.js, packages/workbox-build/src/entry-points/get-manifest.js, packages/workbox-build/src/entry-points/inject-manifest.js, packages/workbox-range-requests/utils/calculateEffectiveBoundaries.mjs, packages/workbox-routing/utils/normalizeHandler.mjs, packages/workbox-webpack-plugin/src/lib/get-workbox-sw-imports.js, test/workbox-build/node/lib/runtime-caching-converter.js
See https://github.com/GoogleChrome/workbox/issues/1450
=> Explicitly use node v9 in our CI config

.github/PULL_REQUEST_TEMPLATE.md
=> Update the R: line of the PR template

package-lock.json, package.json
=> Update our IDB mocking library fork version

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs
Metadata updates for the `v3.3.0` release.
=> v3.3.0 metadata

packages/workbox-cli/src/app.js, test/workbox-cli/node/app.js
CC: @schorfES
Fixes #1541
Happy to iterate on the language a bit, but I think this should help.
=> Link to workbox.setConfig() docs after calling workbox copyLibraries

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs
Version bumps following the new release.
=> v3.3.1 metadata

demos/functions/cdn-details.json, package-lock.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/package-lock.json, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-cli/package-lock.json, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs, packages/workbox-webpack-plugin/package-lock.json
=> 3.4.1 metadata

package-lock.json, package.json, test/workbox-webpack-plugin/node/generate-sw.js, test/workbox-webpack-plugin/node/inject-manifest.js
Fixes #1622, ensuring that our integration tests work against Firefox 63.
=> Update the geckodriver devDependency

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs
=> 3.5.0 metadata.

infra/testing/activate-sw-safari.js
=> Fix local test failures in Safari

demos/functions/cdn-details.json, demos/functions/package-lock.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs
=> Update metadata for v3.6.1

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs
Just the standard post-release version bumps.
=> 3.6.2 metadata

gulp-tasks/publish-lerna.js
Prep for publishing the first alpha.
=> npm alpha tag

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs
=> 3.6.3 metadata

packages/workbox-precaching/controllers/PrecacheController.mjs, test/workbox-precaching/node/controllers/test-PrecacheController.mjs
=> Delete temporary precache after SW activation

packages/workbox-background-sync/Queue.mjs
=> workbox-background-sync logging fix

packages/workbox-core/models/messages/messages.mjs
Fixes #1573
Small change to improve the log message.
=> Improve conflicting revision details log message

packages/workbox-build/src/entry-points/options/defaults.js
Addresses part of the issue in https://github.com/GoogleChrome/workbox/issues/1830. Specifically [this section](https://docs.google.com/document/d/1xInIqp1IZZ8NG1H0Tbm1av28ej8N1obkMXnZ9ZPXWPc/edit#heading=h.4m9jr65nzf5r) of the changes proposal.
=> Make injectionPointRegexp more bundler friendly

demos/functions/cdn-details.json, gulp-tasks/utils/publish-helpers.js, package-lock.json
Includes `.mjs` files in the set of build files that get updated to the CDN.
=> Support mjs files being published

packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs, packages/workbox-window/_version.mjs
=> Update package version data

gulp-tasks/utils/version-module.js, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-cache-update/_version.mjs, packages/workbox-cache-expiration/_version.mjs, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs, packages/workbox-window/_version.mjs
Redoing https://github.com/GoogleChrome/workbox/pull/1839 ([correctly this time](https://github.com/GoogleChrome/workbox/pull/1845)) since it was merged into the wrong branch.
=> Correctly update package version data

package-lock.json, package.json, packages/workbox-background-sync/models/QueueStore.mjs, packages/workbox-google-analytics/initialize.mjs, test/workbox-core/node/_private/test-DBWrapper.mjs
Fixes #1751, which turned out to not be flakey but actually have a bug that wasn't caught due to our IDB mocks not being fully compliant.
This PR fixes the bug and updates to a fixed version of the mocks.
=> Fix bg-sync reply bug due to bad IDB mocks

packages/workbox-build/package.json, test/workbox-build/node/dependency-check.js, test/workbox-build/node/lib/copy-workbox-libraries.js
=> Include workbox-window in the copied libraries

packages/workbox-precaching/PrecacheController.mjs, test/workbox-precaching/node/test-PrecacheController.mjs
This addresses something that @prateekbh noticed while testing v4.
=> Pass request + event to cacheWillUpdate in workbox-precaching

infra/testing/validator/service-worker-runtime.js, packages/workbox-build/src/templates/sw-template.js, test/workbox-build/node/entry-points/generate-sw-string.js, test/workbox-build/node/entry-points/generate-sw.js
Weston noticed this was incorrect in our release notes, and when I did a search through the project I found these four incorrect instances.
=> Fix incorrect casing on getCacheKeyForURL

demos/functions/cdn-details.json, demos/functions/package-lock.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-expiration/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs, packages/workbox-window/_version.mjs
=> Update package metadata

packages/workbox-strategies/index.mjs
=> Fix missing space in deprecation message

packages/workbox-routing/index.mjs, packages/workbox-routing/setCatchHandler.mjs, packages/workbox-routing/setDefaultHandler.mjs, test/workbox-routing/node/test-registerRoute.mjs, test/workbox-routing/node/test-setCatchHandler.mjs, test/workbox-routing/node/test-setDefaultHandler.mjs
These were lost in the overall transition to top-level modules.
Fixes #1897
=> Adds workbox.routing.[setDefault,setCatch]Handler()

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-expiration/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs, packages/workbox-window/_version.mjs
=> Update package version metadata

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-update/_version.mjs, packages/workbox-build/src/cdn-details.json, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-expiration/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs, packages/workbox-window/_version.mjs
=> Update version metadata

gulp-tasks/publish-lerna.js
I believe this needs to be done before we release v4. Anything else?
=> Remove npm beta tag

packages/workbox-routing/index.mjs, packages/workbox-sw/index.mjs
Addresses #1921 (though we need to update the docs in https://github.com/google/WebFundamentals before it's fixed).
=> Add missing jsdoc namespace declarations

packages/workbox-window/messageSW.mjs
=> Fix JSDoc comment typo

packages/workbox-background-sync/package.json, packages/workbox-broadcast-update/package.json, packages/workbox-cacheable-response/package.json, packages/workbox-expiration/package.json, packages/workbox-range-requests/package.json
Small change to get the first-party plugins to show up in this search: https://www.npmjs.com/search?q=keywords%3Aworkbox-plugin
=> Add workbox-plugin keyword to package.json

packages/workbox-background-sync/Queue.mjs, packages/workbox-background-sync/lib/QueueStore.mjs, packages/workbox-broadcast-update/BroadcastCacheUpdate.mjs, packages/workbox-core/_private/DBWrapper.mjs, packages/workbox-expiration/models/CacheTimestampsModel.mjs, packages/workbox-window/utils/EventTargetShim.mjs, test/all/node/test-jsdocs.mjs
Fixes #1964 and adds a test to ensure at least no methods with an underscore appear in the generated docs.
=> Ensure all private members are properly marked

packages/workbox-expiration/Plugin.mjs
=> Update docs to better state what happens

demos/functions/cdn-details.json, packages/workbox-background-sync/_version.mjs, packages/workbox-broadcast-update/_version.mjs, packages/workbox-build/package-lock.json, packages/workbox-build/src/cdn-details.json, packages/workbox-cacheable-response/_version.mjs, packages/workbox-core/_version.mjs, packages/workbox-expiration/_version.mjs, packages/workbox-google-analytics/_version.mjs, packages/workbox-navigation-preload/_version.mjs, packages/workbox-precaching/_version.mjs, packages/workbox-range-requests/_version.mjs, packages/workbox-routing/_version.mjs, packages/workbox-strategies/_version.mjs, packages/workbox-streams/_version.mjs, packages/workbox-sw/_version.mjs, packages/workbox-window/_version.mjs
I neglected to commit this after the v4.3.0 release.
=> 4.3.0 metadata

.travis.yml, gulp-tasks/utils/build-node-package.js, packages/workbox-build/package.json, packages/workbox-cli/package.json, packages/workbox-webpack-plugin/package.json
Fixes #2094 for the v5 branch.
=> Require node v8.0.0 or higher

infra/type-overrides.d.ts, package-lock.json, package.json
=> Update type-overrides and link to tracking bugs

packages/workbox-strategies/src/CacheFirst.ts, packages/workbox-strategies/src/CacheOnly.ts, packages/workbox-strategies/src/NetworkFirst.ts, packages/workbox-strategies/src/NetworkOnly.ts, packages/workbox-strategies/src/StaleWhileRevalidate.ts, test/workbox-strategies/sw/test-CacheFirst.mjs, test/workbox-strategies/sw/test-CacheOnly.mjs, test/workbox-strategies/sw/test-NetworkFirst.mjs, test/workbox-strategies/sw/test-NetworkOnly.mjs, test/workbox-strategies/sw/test-StaleWhileRevalidate.mjs
=> Remove the makeRequest() method from strategies

demos/functions/views/demo/workbox-background-sync/sw.hbs
=> Update background-sync demo to work with v4

test/workbox-expiration/sw/test-CacheExpiration.mjs
Maybe this will help with our test flakiness? It definitely seems like there _should_ be `await`s there.
=> Adds some missing awaits to integration tests

gulp-tasks/transpile-typescript.js, packages/workbox-broadcast-update/src/Plugin.ts, packages/workbox-core/src/models/messages/messages.ts, packages/workbox-google-analytics/src/initialize.ts, packages/workbox-routing/src/Router.ts
R: @jeffposnick @philipwalton 👋 
This fixes a few typos in comments. Nothing too crazy.
=> Fixing typos

packages/workbox-window/src/utils/WorkboxEvent.ts
Just a small change for this Typescript error:
=> WorkboxEvent extends WorkboxEventProps

packages/workbox-window/src/utils/WorkboxEvent.ts, packages/workbox-window/src/utils/WorkboxEventTarget.ts
=> WorkboxEvent props also should be strictly typed

demos/functions/cdn-details.json, packages/workbox-background-sync/src/_version.ts, packages/workbox-broadcast-update/src/_version.ts, packages/workbox-build/src/cdn-details.json, packages/workbox-cacheable-response/src/_version.ts, packages/workbox-core/src/_version.ts, packages/workbox-expiration/src/_version.ts, packages/workbox-google-analytics/src/_version.ts, packages/workbox-navigation-preload/src/_version.ts, packages/workbox-precaching/src/_version.ts, packages/workbox-range-requests/src/_version.ts, packages/workbox-routing/src/_version.ts, packages/workbox-strategies/src/_version.ts, packages/workbox-streams/src/_version.ts, packages/workbox-sw/_version.mjs, packages/workbox-window/src/_version.ts
v5.0.0-alpha.2 versioning info
=> 5.0.0-alpha.2 metadata

packages/workbox-webpack-plugin/package-lock.json, packages/workbox-webpack-plugin/package.json, packages/workbox-webpack-plugin/src/lib/stringify-manifest.js
=> Switch to fast-json-stable-stringify

packages/workbox-build/src/lib/get-file-manifest-entries.js, packages/workbox-build/src/lib/transform-manifest.js, packages/workbox-webpack-plugin/src/generate-sw.js, packages/workbox-webpack-plugin/src/inject-manifest.js, packages/workbox-webpack-plugin/src/lib/get-manifest-entries-from-compilation.js, test/workbox-build/node/lib/transform-manifest.js
Fixes #2189 
Just throwing some `async` and `await` statements in there...
=> Support for async manifestTransform callbacks

demos/functions/cdn-details.json, packages/workbox-background-sync/src/_version.ts, packages/workbox-broadcast-update/src/_version.ts, packages/workbox-build/src/cdn-details.json, packages/workbox-cacheable-response/src/_version.ts, packages/workbox-core/src/_version.ts, packages/workbox-expiration/src/_version.ts, packages/workbox-google-analytics/src/_version.ts, packages/workbox-navigation-preload/src/_version.ts, packages/workbox-precaching/src/_version.ts, packages/workbox-range-requests/src/_version.ts, packages/workbox-routing/src/_version.ts, packages/workbox-strategies/src/_version.ts, packages/workbox-streams/src/_version.ts, packages/workbox-sw/_version.mjs, packages/workbox-window/src/_version.ts
=> 5.0.0-beta.0 metadata

packages/workbox-core/src/types.ts
Fixes #2205 
Also fixes some incorrect plugin callback types that I noticed while making these changes.
=> Fix incorrect types

packages/workbox-window/src/Workbox.ts, test/workbox-window/window/test-Workbox.mjs
Fixes #2201, fixes #2202 
This PR fixes #2202 by adding the message event listener to the constructor rather than the `register()` method, but it also awaits `this.getSW()` so it has time to ensure the service worker sending the message is one of its "own" service workers.
This PR also adds an instance property `this._ownSWs` set to fix #2201. This set contains all of the service workers that were ever considered "own" service workers during the lifetime of the `Workbox` instance—and ensures message sent by external service workers are not dispatched on this instance.
=> Move adding the message listener to the constructor

packages/workbox-range-requests/src/utils/calculateEffectiveBoundaries.ts, test/workbox-range-requests/sw/test-createPartialResponse.mjs, test/workbox-range-requests/sw/utils/test-calculateEffectiveBoundaries.mjs
=> Fixes calculateEffectiveBoundaries bug when start=0

packages/workbox-background-sync/src/lib/StorableRequest.ts, packages/workbox-broadcast-update/src/BroadcastUpdatePlugin.ts, packages/workbox-core/src/_private.ts, packages/workbox-core/src/_private/assert.ts, packages/workbox-core/src/_private/dontWaitFor.ts, packages/workbox-core/src/_private/timeout.ts, packages/workbox-core/src/setCacheNameDetails.ts, packages/workbox-expiration/src/CacheExpiration.ts, packages/workbox-expiration/src/ExpirationPlugin.ts, packages/workbox-routing/src/Router.ts, packages/workbox-streams/src/concatenate.ts, packages/workbox-window/src/Workbox.ts, test/workbox-broadcast-update/sw/test-BroadcastUpdatePlugin.mjs
Fixes a few TypeScript style issues.
=> Clean up TS style/linting issues

demos/functions/cdn-details.json, packages/workbox-background-sync/src/_version.ts, packages/workbox-broadcast-update/src/_version.ts, packages/workbox-build/src/cdn-details.json, packages/workbox-cacheable-response/src/_version.ts, packages/workbox-core/src/_version.ts, packages/workbox-expiration/src/_version.ts, packages/workbox-google-analytics/src/_version.ts, packages/workbox-navigation-preload/src/_version.ts, packages/workbox-precaching/src/_version.ts, packages/workbox-range-requests/src/_version.ts, packages/workbox-routing/src/_version.ts, packages/workbox-strategies/src/_version.ts, packages/workbox-streams/src/_version.ts, packages/workbox-sw/_version.mjs, packages/workbox-window/src/_version.ts
=> Update metadata for 5.0.0-rc.0

packages/workbox-navigation-preload/src/enable.ts
Just a small TypeScript issue that I bumped into.
=> Correct a TypeScript parameter definition

packages/workbox-window/src/Workbox.ts
=> Fix incorrect workbox-window doc links

demos/functions/cdn-details.json, packages/workbox-build/src/cdn-details.json
=> 5.0.0-rc.1 metadata

packages/workbox-background-sync/src/Queue.ts
Fixes #2305 (cc: @similicious)
=> Add more detailed onSync type definitions

packages/workbox-build/src/cdn-details.json
=> CDN details update

packages/workbox-build/src/_types.js, packages/workbox-build/src/generate-sw.js, packages/workbox-build/src/get-manifest.js, packages/workbox-build/src/inject-manifest.js, packages/workbox-build/src/lib/transform-manifest.js, packages/workbox-webpack-plugin/src/generate-sw.js, packages/workbox-webpack-plugin/src/inject-manifest.js
Fixes some issues identified on d.g.c. staging.
=> JSDoc cleanup

package-lock.json, package.json, test/workbox-webpack-plugin/node/generate-sw.js
Fixes #1456 by using `memory-fs` in one of our test cases.
=> Adds a memory-fs webpack test
